#!/usr/bin/env bash
set -uo pipefail
# pre-llm-tabular-detect.sh — Capa 1: detect tabular data before LLM call
# If prompt contains >5 lines of tabular data, replace with statistical profile

INPUT=$(cat)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILER="$SCRIPT_DIR/../../scripts/tabular-profile.py"
SUMMARIZER="$SCRIPT_DIR/../../scripts/tabular-summarize.sh"

# SE-297: detect .xlsx file path references in the prompt and profile them
# directly (before the inline line-count gate).
XLSX_PATH=$(echo "$INPUT" | grep -oE '[A-Za-z0-9_./-]+\.xlsx' 2>/dev/null | head -1 || true)
if [[ -n "$XLSX_PATH" && -f "$XLSX_PATH" ]]; then
  PROFILE=$(python3 "$PROFILER" "$XLSX_PATH" 2>/dev/null || echo "")
  if [[ -n "$PROFILE" && "$PROFILE" != *'"error"'* ]]; then
    cat <<OUTPUT
$INPUT

[STATISTICAL PROFILE — generated by tabular-profile.py from $XLSX_PATH. Numbers are exact. LLM: interpret, do NOT recompute.]
$PROFILE
OUTPUT
    exit 0
  fi
fi

# Quick heuristic: count lines that look like CSV or markdown tables
CSV_LINES=$(echo "$INPUT" | grep -cE '^[^|]*,{1,}[^,].*[0-9]' 2>/dev/null || echo 0)
MD_LINES=$(echo "$INPUT" | grep -cE '^\s*\|.+\|' 2>/dev/null || echo 0)
TOTAL_TABULAR=$((CSV_LINES + MD_LINES))

if [[ "$TOTAL_TABULAR" -lt 5 ]]; then
  echo "$INPUT"
  exit 0
fi

# Extract tabular portion and profile it
if [[ -x "$SUMMARIZER" ]]; then
  PROFILE=$(echo "$INPUT" | "$SUMMARIZER" - 2>/dev/null || echo "")
else
  PROFILE=$(echo "$INPUT" | python3 "$PROFILER" 2>/dev/null || echo "")
fi

if [[ -n "$PROFILE" && "$PROFILE" != *'"error"'* && "$PROFILE" != *'"detected":false'* ]]; then
  # Replace raw tabular data with profile in the prompt
  # Keep non-tabular parts of the original prompt
  NON_TABULAR=$(echo "$INPUT" | grep -vE '^\s*\|.+\||^[^|]*,{1,}[^,]' 2>/dev/null || echo "")
  
  cat <<OUTPUT
$NON_TABULAR

[STATISTICAL PROFILE — generated by tabular-profile.py. Numbers are exact. LLM: interpret, do NOT recompute.]
$PROFILE
OUTPUT
else
  echo "$INPUT"
fi
