#!/usr/bin/env bash
# SPEC-146 — Ecosystem watcher monthly run
# Invoked by: .github/workflows/ecosystem-watcher.yml (cron) or manually
# Output: output/research-skills-update-{YYYY-MM}.md
set -uo pipefail

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$REPO_ROOT" || exit 1

LIST="docs/rules/domain/ecosystem-watch-list.yaml"
SNAP_DIR=".savia-memory/ecosystem-snapshots"
OUT_DIR="output"
HIST="$OUT_DIR/ecosystem-watcher-history.jsonl"
RUN_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
RUN_YM="$(date -u +%Y-%m)"
REPORT="$OUT_DIR/research-skills-update-$RUN_YM.md"

mkdir -p "$SNAP_DIR" "$OUT_DIR"

# Use last-run.txt to compute since= window; default to 30 days ago
LAST_RUN_FILE="$SNAP_DIR/last-run.txt"
if [[ -f "$LAST_RUN_FILE" ]]; then
  SINCE="$(cat "$LAST_RUN_FILE")"
else
  SINCE="$(date -u -d '30 days ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v-30d +%Y-%m-%dT%H:%M:%SZ)"
fi

repos_checked=0
repos_failed=0
docs_checked=0
docs_failed=0

# --- Parse YAML (lightweight, no yq dependency) --------------------------
parse_repos() {
  awk '/^repos:/{flag=1; next} /^[a-z]/{flag=0} flag && /github:/{gsub(/.*github: */,""); print}' "$LIST"
}
parse_docs() {
  awk '/^docs:/{flag=1; next} /^[a-z]/{flag=0} flag && /url:/{gsub(/.*url: */,""); print}' "$LIST"
}

# --- Initialize report header --------------------------------------------
{
  echo "# Ecosystem watch — $RUN_YM"
  echo ""
  echo "> Generated by skill \`ecosystem-watcher\` (SPEC-146) at \`$RUN_TS\`."
  echo "> Since: \`$SINCE\`. Watch list: \`$LIST\`."
  echo ""
  echo "## High signal (acción recomendada)"
  echo ""
  echo "_To be classified by review pass._"
  echo ""
  echo "## Medium signal (informativo)"
  echo ""
} > "$REPORT"

# --- Iterate repos --------------------------------------------------------
for repo in $(parse_repos); do
  repos_checked=$((repos_checked+1))
  echo "### Repo: $repo" >> "$REPORT"
  if command -v gh >/dev/null 2>&1; then
    commits=$(gh api "repos/$repo/commits?since=$SINCE" --jq 'length' 2>/dev/null || echo "ERROR")
    releases=$(gh api "repos/$repo/releases?per_page=5" --jq '[.[] | select(.published_at >= "'"$SINCE"'") | .tag_name] | join(", ")' 2>/dev/null || echo "")
    if [[ "$commits" == "ERROR" ]]; then
      repos_failed=$((repos_failed+1))
      echo "- _failed to fetch (rate limit or network)_" >> "$REPORT"
    else
      echo "- commits since $SINCE: **$commits**" >> "$REPORT"
      [[ -n "$releases" ]] && echo "- new releases: $releases" >> "$REPORT"
      # Save snapshot
      snap_file="$SNAP_DIR/$(echo "$repo" | tr '/' '-')-$RUN_YM.md"
      gh api "repos/$repo" --jq '{stars: .stargazers_count, forks: .forks_count, updated: .updated_at, topics: .topics}' > "$snap_file" 2>/dev/null || true
    fi
  else
    repos_failed=$((repos_failed+1))
    echo "- _skipped: gh CLI not available_" >> "$REPORT"
  fi
  echo "" >> "$REPORT"
done

# --- Iterate docs URLs ----------------------------------------------------
echo "" >> "$REPORT"
echo "## Documentation snapshots" >> "$REPORT"
echo "" >> "$REPORT"
for url in $(parse_docs); do
  docs_checked=$((docs_checked+1))
  slug=$(echo "$url" | sed 's|https\?://||;s|/|-|g;s|\.|-|g')
  snap_file="$SNAP_DIR/${slug}-$RUN_YM.html"
  if command -v curl >/dev/null 2>&1; then
    if curl -fsSL --max-time 30 "$url" -o "$snap_file" 2>/dev/null; then
      size=$(wc -c < "$snap_file")
      echo "- \`$url\` — snapshot saved (${size} bytes)" >> "$REPORT"
    else
      docs_failed=$((docs_failed+1))
      echo "- \`$url\` — _failed to fetch_" >> "$REPORT"
    fi
  fi
done

# --- Footer + history -----------------------------------------------------
{
  echo ""
  echo "## Low signal (ruido)"
  echo ""
  echo "_See full snapshots in \`$SNAP_DIR\`._"
  echo ""
  echo "## Stats"
  echo ""
  echo "- repos checked: $repos_checked"
  echo "- repos failed: $repos_failed"
  echo "- docs checked: $docs_checked"
  echo "- docs failed: $docs_failed"
  echo "- since: $SINCE"
  echo "- run timestamp: $RUN_TS"
} >> "$REPORT"

# Update last-run marker
echo "$RUN_TS" > "$LAST_RUN_FILE"

# Append to history
printf '{"ts":"%s","report":"%s","repos_checked":%d,"repos_failed":%d,"docs_checked":%d,"docs_failed":%d}\n' \
  "$RUN_TS" "$REPORT" "$repos_checked" "$repos_failed" "$docs_checked" "$docs_failed" >> "$HIST"

echo "✓ Ecosystem watch complete. Report: $REPORT"
echo "  repos: $repos_checked checked, $repos_failed failed"
echo "  docs:  $docs_checked checked, $docs_failed failed"
