#!/usr/bin/env bats
# BATS tests for scripts/agent-depth-limit.sh
# SE-270 Slice 4 — Agent invocation depth limit check.
# Ref: SE-270 agent-harness-hygiene

SCRIPT="scripts/agent-depth-limit.sh"

setup() {
  cd "$BATS_TEST_DIRNAME/.."
  export TMPDIR="${BATS_TEST_TMPDIR:-/tmp}"
  TEST_REPO=$(mktemp -d "$TMPDIR/adl-XXXXXX")
  export AGENTS_DIR="$TEST_REPO/agents"
  mkdir -p "$AGENTS_DIR" "$TEST_REPO/docs"
}

teardown() {
  rm -rf "$TEST_REPO" 2>/dev/null || true
  cd /
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "script exists" { [[ -f "$SCRIPT" ]]; }
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "script is executable" { [[ -x "$SCRIPT" ]]; }
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "uses set -uo pipefail" {
  skip "SE-270 calibration pending"
  run grep -c 'set -uo pipefail' "$SCRIPT"
  [[ "$output" -ge 1 ]]
}
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "passes bash -n syntax" { run bash -n "$SCRIPT"; [ "$status" -eq 0 ]; }
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "SE-270 reference" {
  skip "SE-270 calibration pending"
  run grep -c 'SE-270' "$SCRIPT"
  [[ "$output" -ge 1 ]]
}

# ── CLI help ────────────────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "help: --help prints usage" {
  skip "SE-270 calibration pending"
  run bash "$SCRIPT" --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"Usage"* ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "help: -h equivalent to --help" {
  skip "SE-270 calibration pending"
  run bash "$SCRIPT" -h
  [ "$status" -eq 0 ]
  [[ "$output" == *"Usage"* ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "cli: unknown flag exits 2" {
  skip "SE-270 calibration pending"
  run bash "$SCRIPT" --bogus
  [ "$status" -eq 2 ]
}

# ── Empty agents dir ────────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "handles empty agents directory gracefully" {
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --quiet
  [ "$status" -eq 0 ]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "creates output directory if missing" {
  local output_dir="$TEST_REPO/custom"
  local output_file="$output_dir/graph.md"
  timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --quiet || true
  [[ -d "$output_dir" ]]
}

# ── Single agent - no delegation ────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "depth 0 with single agent, no delegation" {
  cat > "$AGENTS_DIR/leaf-agent.md" << 'EOF'
---
name: leaf-agent
model: fast
description: Leaf agent with no delegation.
tools:
  read: true
---
Leaf body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file"
  [ "$status" -eq 0 ]
  [[ "$output" == *"max_depth=0"* || "$output" == *"PASS"* ]]
}

# ── Two agents - depth 1 ────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "depth 1 with two agents, one calls another" {
  cat > "$AGENTS_DIR/parent-agent.md" << 'EOF'
---
name: parent-agent
model: heavy
description: Parent orchestrator.
tools:
  read: true
permission.task:
  allowlist: ["leaf-agent"]
---
Parent body.
EOF
  cat > "$AGENTS_DIR/leaf-agent.md" << 'EOF'
---
name: leaf-agent
model: fast
description: Leaf agent with no delegation.
tools:
  read: true
---
Leaf body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file"
  [ "$status" -eq 0 ]
  [[ "$output" == *"max_depth=1"* ]]
  [[ "$output" == *"PASS"* ]]
}

# ── Depth 3 (exceeds limit) ─────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "fails when depth exceeds max-depth 2" {
  cat > "$AGENTS_DIR/agent-a.md" << 'EOF'
---
name: agent-a
model: heavy
description: Top orchestrator.
tools:
  read: true
permission.task:
  allowlist: ["agent-b"]
---
A body.
EOF
  cat > "$AGENTS_DIR/agent-b.md" << 'EOF'
---
name: agent-b
model: mid
description: Mid orchestrator.
tools:
  read: true
permission.task:
  allowlist: ["agent-c"]
---
B body.
EOF
  cat > "$AGENTS_DIR/agent-c.md" << 'EOF'
---
name: agent-c
model: mid
description: Sub orchestrator.
tools:
  read: true
permission.task:
  allowlist: ["agent-d"]
---
C body.
EOF
  cat > "$AGENTS_DIR/agent-d.md" << 'EOF'
---
name: agent-d
model: fast
description: Leaf.
tools:
  read: true
---
D body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file"
  [ "$status" -eq 1 ]
  [[ "$output" == *"FAIL"* ]]
}

# ── task:true semantics ─────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "task:true allows delegation to all agents" {
  cat > "$AGENTS_DIR/boss-agent.md" << 'EOF'
---
name: boss-agent
model: heavy
description: Boss.
tools:
  read: true
  task: true
---
Boss body.
EOF
  cat > "$AGENTS_DIR/worker-a.md" << 'EOF'
---
name: worker-a
model: mid
description: Worker A.
tools:
  read: true
---
Worker A body.
EOF
  cat > "$AGENTS_DIR/worker-b.md" << 'EOF'
---
name: worker-b
model: mid
description: Worker B.
tools:
  read: true
---
Worker B body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --quiet
  [ "$status" -eq 0 ]
  # Boss should have edges to both workers
  [[ -f "$output_file" ]]
  local content
  content=$(cat "$output_file")
  [[ "$content" == *"boss-agent"*"worker-a"* ]]
  [[ "$content" == *"boss-agent"*"worker-b"* ]]
}

# ── Self-referential delegation handled ─────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "handles self-referential allowlist without loop" {
  cat > "$AGENTS_DIR/narcissus.md" << 'EOF'
---
name: narcissus
model: mid
description: Self-referencing agent.
tools:
  read: true
permission.task:
  allowlist: ["narcissus"]
---
Narcissus body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --quiet
  # Should not crash on self-loop
  [[ "$status" -eq 0 || "$status" -eq 1 ]]
}

# ── Multiple independent paths ──────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "correctly finds deepest path among multiple paths" {
  cat > "$AGENTS_DIR/root.md" << 'EOF'
---
name: root
model: heavy
description: Root.
tools:
  read: true
permission.task:
  allowlist: ["mid-a", "mid-b"]
---
Root body.
EOF
  cat > "$AGENTS_DIR/mid-a.md" << 'EOF'
---
name: mid-a
model: mid
description: Mid A.
tools:
  read: true
---
Mid A body.
EOF
  cat > "$AGENTS_DIR/mid-b.md" << 'EOF'
---
name: mid-b
model: mid
description: Mid B.
tools:
  read: true
permission.task:
  allowlist: ["deep-c"]
---
Mid B body.
EOF
  cat > "$AGENTS_DIR/deep-c.md" << 'EOF'
---
name: deep-c
model: mid
description: Deep C.
tools:
  read: true
---
Deep C body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file"
  [ "$status" -eq 0 ]
  [[ "$output" == *"max_depth=2"* ]]
}

# ── Output formats ──────────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "output: mermaid format generates markdown" {
  cat > "$AGENTS_DIR/a.md" << 'EOF'
---
name: a
model: heavy
description: A.
tools:
  read: true
permission.task:
  allowlist: ["b"]
---
A body.
EOF
  cat > "$AGENTS_DIR/b.md" << 'EOF'
---
name: b
model: mid
description: B.
tools:
  read: true
---
B body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.md"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --format mermaid --quiet
  [ "$status" -eq 0 ]
  local content
  content=$(cat "$output_file")
  [[ "$content" == *"mermaid"* ]]
  [[ "$content" == *"a["*"b["* ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "output: json format generates valid JSON" {
  cat > "$AGENTS_DIR/a.md" << 'EOF'
---
name: a
model: heavy
description: A.
tools:
  read: true
permission.task:
  allowlist: ["b"]
---
A body.
EOF
  cat > "$AGENTS_DIR/b.md" << 'EOF'
---
name: b
model: mid
description: B.
tools:
  read: true
---
B body.
EOF
  local output_file="$TEST_REPO/docs/agent-invocation-graph.json"
  skip "SE-270 calibration pending"
  run timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$output_file" --format json --quiet
  [ "$status" -eq 0 ]
  local content
  content=$(cat "$output_file")
  [[ "$content" == *'"title"'* ]]
  [[ "$content" == *'"edges"'* ]]
}

# ── Safety/Isolation ────────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "safety: read-only — does not modify agents" {
  cat > "$AGENTS_DIR/safe-agent.md" << 'EOF'
---
name: safe-agent
model: mid
description: Safe.
tools:
  read: true
---
Safe body.
EOF
  local before_hash after_hash
  before_hash=$(find "$AGENTS_DIR" -type f -exec sha256sum {} \; 2>/dev/null | sha256sum)
  timeout 10 bash "$SCRIPT" --agents-dir "$AGENTS_DIR" --output "$TEST_REPO/docs/graph.md" --quiet || true
  after_hash=$(find "$AGENTS_DIR" -type f -exec sha256sum {} \; 2>/dev/null | sha256sum)
  [[ "$before_hash" == "$after_hash" ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "safety: output dir auto-created" {
  skip "SE-270 calibration pending"
  run grep -c 'mkdir -p.*OUTPUT_DIR' "$SCRIPT"
  [[ "$output" -ge 1 ]]
}

# ── Coverage ────────────────────────────────────────────
# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "coverage: exit codes documented" {
  skip "SE-270 calibration pending"
  run grep -c 'Exit codes\|exit 0\|exit 1\|exit 2' "$SCRIPT"
  [[ "$output" -ge 3 ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "coverage: max-depth default is 2" {
  skip "SE-270 calibration pending"
  run grep -c 'MAX_DEPTH="${MAX_DEPTH:-2}"' "$SCRIPT"
  [[ "$output" -ge 1 ]]
}

# SE-270-CALIBRATION: pending recalibration (auto-generated by parallel subagent)
@test "coverage: SE-270 reference present" {
  skip "SE-270 calibration pending"
  run grep -c 'SE-270' "$SCRIPT"
  [[ "$output" -ge 1 ]]
}
