#!/usr/bin/env bash
# agent-manifest-export.sh — SPEC-SE-004: Exporta agentes Savia a otros frameworks
set -uo pipefail
#
# Lee el frontmatter YAML de un agente .opencode/agents/{name}.md y genera
# el manifiesto en el formato del framework destino.
#
# Usage:
#   agent-manifest-export.sh --agent NAME --format FORMAT [--output-dir DIR]
#
# Formats:
#   msagent        Microsoft Agent Framework (AgentDefinition YAML)
#   langgraph      LangGraph node definition JSON
#   semantic-kernel  Semantic Kernel plugin JSON
#   pydantic-ai    PydanticAI agent spec JSON
#   openai-agents  OpenAI Assistants API spec JSON
#
# Output: .claude/enterprise/adapters/{format}/{name}.yaml|json
# Ref: docs/propuestas/savia-enterprise/SPEC-SE-004-agent-framework-interop.md

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

AGENT_NAME=""
FORMAT=""
OUTPUT_BASE="${ROOT_DIR}/.claude/enterprise/adapters"

VALID_FORMATS="msagent langgraph semantic-kernel pydantic-ai openai-agents"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent)      AGENT_NAME="$2"; shift 2 ;;
    --format)     FORMAT="$2"; shift 2 ;;
    --output-dir) OUTPUT_BASE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# //; s/^#//'
      exit 0 ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$AGENT_NAME" ]]; then
  echo "ERROR: --agent required" >&2; exit 2
fi
if [[ -z "$FORMAT" ]]; then
  echo "ERROR: --format required (one of: $VALID_FORMATS)" >&2; exit 2
fi
if [[ " $VALID_FORMATS " != *" $FORMAT "* ]]; then
  echo "ERROR: invalid format '$FORMAT'. Must be one of: $VALID_FORMATS" >&2; exit 2
fi

# ── Leer agente ──────────────────────────────────────────────────────────────

AGENT_FILE="${ROOT_DIR}/.opencode/agents/${AGENT_NAME}.md"
if [[ ! -f "$AGENT_FILE" ]]; then
  echo "ERROR: agente no encontrado: $AGENT_FILE" >&2
  exit 3
fi

# Extraer frontmatter (entre los --- delimiters)
frontmatter_raw=$(awk '/^---/{found++; if(found==2) exit} found==1 && !/^---/{print}' "$AGENT_FILE")

# Helpers para extraer campos del frontmatter YAML
_field() {
  local key="$1"
  echo "$frontmatter_raw" | grep "^${key}:" | head -1 | sed "s/^${key}:[[:space:]]*//" | tr -d '"' | tr -d "'"
}
_field_block() {
  local key="$1"
  # Lee valor de campo multilinea con >
  echo "$frontmatter_raw" | awk "/^${key}:/{found=1; next} found && /^[[:space:]]/{print; next} found{exit}" \
    | sed 's/^[[:space:]]*//' | tr '\n' ' ' | sed 's/[[:space:]]*$//'
}

NAME=$(_field "name")
[[ -z "$NAME" ]] && NAME="$AGENT_NAME"

MODEL=$(_field "model")
[[ -z "$MODEL" ]] && MODEL="mid"

PERMISSION=$(_field "permission_level")
[[ -z "$PERMISSION" ]] && PERMISSION="L1"

DESCRIPTION=$(_field_block "description")
[[ -z "$DESCRIPTION" ]] && DESCRIPTION=$(_field "description")
[[ -z "$DESCRIPTION" ]] && DESCRIPTION="Savia agent: $NAME"

# Normalizar model tier → modelo concreto
case "$MODEL" in
  heavy|opus) MODEL_ID="claude-opus-4-5" ;;
  mid|sonnet) MODEL_ID="claude-sonnet-4-5" ;;
  fast|haiku) MODEL_ID="claude-haiku-3-5" ;;
  *) MODEL_ID="$MODEL" ;;
esac

# ── Generar según formato ────────────────────────────────────────────────────

OUT_DIR="${OUTPUT_BASE}/${FORMAT}"
mkdir -p "$OUT_DIR"

case "$FORMAT" in

  msagent)
    OUT_FILE="${OUT_DIR}/${AGENT_NAME}.yaml"
    cat > "$OUT_FILE" <<YAMLEOF
# Microsoft Agent Framework — AgentDefinition
# Generated by agent-manifest-export.sh (SPEC-SE-004)
# Source: .opencode/agents/${AGENT_NAME}.md

apiVersion: microsoft.agent/v1
kind: AgentDefinition
metadata:
  name: ${NAME}
  namespace: savia
  labels:
    savia.pm/permission: "${PERMISSION}"
    savia.pm/source: opencode
spec:
  description: "${DESCRIPTION}"
  model:
    provider: anthropic
    id: ${MODEL_ID}
  tools:
    - name: read_file
      type: function
    - name: glob_search
      type: function
    - name: grep_search
      type: function
  permissions:
    level: ${PERMISSION}
  context:
    maxTokens: 12000
YAMLEOF
    ;;

  langgraph)
    OUT_FILE="${OUT_DIR}/${AGENT_NAME}.json"
    cat > "$OUT_FILE" <<JSONEOF
{
  "_spec": "SE-004",
  "_format": "langgraph",
  "_source": ".opencode/agents/${AGENT_NAME}.md",
  "node": {
    "id": "${NAME}",
    "type": "agent",
    "config": {
      "model": "${MODEL_ID}",
      "provider": "anthropic",
      "permission_level": "${PERMISSION}",
      "description": "${DESCRIPTION}",
      "max_tokens": 12000
    },
    "tools": [
      {"name": "read_file", "type": "tool"},
      {"name": "glob_search", "type": "tool"},
      {"name": "grep_search", "type": "tool"}
    ],
    "edges": {
      "default_next": "__end__",
      "error_next": "__end__"
    }
  }
}
JSONEOF
    ;;

  semantic-kernel)
    OUT_FILE="${OUT_DIR}/${AGENT_NAME}.json"
    cat > "$OUT_FILE" <<JSONEOF
{
  "_spec": "SE-004",
  "_format": "semantic-kernel",
  "_source": ".opencode/agents/${AGENT_NAME}.md",
  "plugin": {
    "name": "${NAME}Plugin",
    "description": "${DESCRIPTION}",
    "functions": [
      {
        "name": "invoke",
        "description": "Invokes the ${NAME} agent with a task description",
        "parameters": [
          {"name": "task", "type": "string", "description": "Task to perform", "required": true}
        ],
        "return_type": "string"
      }
    ],
    "execution_settings": {
      "model_id": "${MODEL_ID}",
      "max_tokens": 1000
    }
  }
}
JSONEOF
    ;;

  pydantic-ai)
    OUT_FILE="${OUT_DIR}/${AGENT_NAME}.json"
    cat > "$OUT_FILE" <<JSONEOF
{
  "_spec": "SE-004",
  "_format": "pydantic-ai",
  "_source": ".opencode/agents/${AGENT_NAME}.md",
  "agent": {
    "name": "${NAME}",
    "model": "${MODEL_ID}",
    "system_prompt": "${DESCRIPTION}",
    "permission_level": "${PERMISSION}",
    "tools": [
      {"name": "read_file"},
      {"name": "glob_search"},
      {"name": "grep_search"}
    ],
    "result_type": "str",
    "retries": 1
  }
}
JSONEOF
    ;;

  openai-agents)
    OUT_FILE="${OUT_DIR}/${AGENT_NAME}.json"
    cat > "$OUT_FILE" <<JSONEOF
{
  "_spec": "SE-004",
  "_format": "openai-agents",
  "_source": ".opencode/agents/${AGENT_NAME}.md",
  "assistant": {
    "name": "${NAME}",
    "description": "${DESCRIPTION}",
    "model": "gpt-4o",
    "instructions": "${DESCRIPTION}",
    "tools": [
      {"type": "function", "function": {"name": "read_file", "description": "Read a file"}},
      {"type": "function", "function": {"name": "glob_search", "description": "Search files by glob"}},
      {"type": "function", "function": {"name": "grep_search", "description": "Search file contents"}}
    ],
    "metadata": {
      "savia_permission": "${PERMISSION}",
      "savia_model_tier": "${MODEL}",
      "savia_spec": "SE-004"
    }
  }
}
JSONEOF
    ;;
esac

echo "Exported: $OUT_FILE"
