#!/usr/bin/env bash
# mcp-server-stub.sh — SPEC-SE-003: Genera scaffold de un MCP server
#
# Genera la estructura de directorios y ficheros stub para un MCP server
# a partir de la entrada del catálogo (catalog.json).
#
# Usage:
#   mcp-server-stub.sh --server-id SERVER_ID [--output-dir DIR] [--catalog FILE]
#
# Args:
#   --server-id   ID del server en el catálogo (ej: savia-memory-mcp)
#   --output-dir  Directorio de salida (default: .claude/enterprise/mcp/)
#   --catalog     Path al catalog.json (default: output/mcp-catalog/catalog.json)
#
# Crea:
#   {output-dir}/{server-id}/README.md
#   {output-dir}/{server-id}/src/index.ts  (TypeScript stub MCP v1)
#   {output-dir}/{server-id}/package.json
#   {output-dir}/{server-id}/tests/golden.json
#
# Ref: docs/propuestas/savia-enterprise/SPEC-SE-003-mcp-catalog.md

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

SERVER_ID=""
OUTPUT_DIR="${ROOT_DIR}/.claude/enterprise/mcp"
CATALOG_FILE="${ROOT_DIR}/output/mcp-catalog/catalog.json"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-id)   SERVER_ID="$2"; shift 2 ;;
    --output-dir)  OUTPUT_DIR="$2"; shift 2 ;;
    --catalog)     CATALOG_FILE="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# //; s/^#//'
      exit 0 ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$SERVER_ID" ]]; then
  echo "ERROR: --server-id required" >&2
  exit 2
fi

# ── Leer entrada del catálogo ────────────────────────────────────────────────

if [[ ! -f "$CATALOG_FILE" ]]; then
  echo "ERROR: catalog.json no encontrado en $CATALOG_FILE" >&2
  echo "       Ejecuta primero: scripts/enterprise/mcp-catalog-generate.sh" >&2
  exit 3
fi

# Extraer metadatos básicos del server usando grep/sed (sin deps externas)
SERVER_LANG=$(grep -A5 "\"id\": \"$SERVER_ID\"" "$CATALOG_FILE" 2>/dev/null \
  | grep '"lang"' | head -1 | sed 's/.*"lang"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || echo "TypeScript")
SERVER_VALUE=$(grep -A6 "\"id\": \"$SERVER_ID\"" "$CATALOG_FILE" 2>/dev/null \
  | grep '"value"' | head -1 | sed 's/.*"value"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || echo "")
SERVER_CAPS=$(grep -A7 "\"id\": \"$SERVER_ID\"" "$CATALOG_FILE" 2>/dev/null \
  | grep '"capabilities"' | head -1 || echo "")

if [[ -z "$SERVER_LANG" ]]; then
  echo "ERROR: server-id '$SERVER_ID' no encontrado en el catálogo" >&2
  exit 4
fi

# ── Crear estructura ─────────────────────────────────────────────────────────

STUB_DIR="${OUTPUT_DIR}/${SERVER_ID}"
mkdir -p "${STUB_DIR}/src" "${STUB_DIR}/tests"

echo "Generando scaffold en $STUB_DIR ..."

# ── README.md ────────────────────────────────────────────────────────────────

cat > "${STUB_DIR}/README.md" <<MDEOF
# ${SERVER_ID}

> MCP Server stub generado por SPEC-SE-003.
> **Language:** ${SERVER_LANG} · **Protocol:** MCP v1
> **Status:** stub — sin lógica real, placeholder para implementación.

## Descripción

${SERVER_VALUE}

## Install

\`\`\`bash
npm install   # TypeScript
# o
dotnet restore  # .NET
# o
pip install -e .  # Python
\`\`\`

## Usage (Claude Desktop / MCP client)

\`\`\`json
{
  "mcpServers": {
    "${SERVER_ID}": {
      "command": "node",
      "args": ["dist/index.js"]
    }
  }
}
\`\`\`

## Demo

\`\`\`bash
# Run locally
npm run dev
\`\`\`

## Tests

\`\`\`bash
npm test
\`\`\`

## Contributing

MIT License. See [SPEC-SE-003](../../../../docs/propuestas/savia-enterprise/SPEC-SE-003-mcp-catalog.md).
MDEOF

# ── src/index.ts (TypeScript stub MCP v1) ────────────────────────────────────

cat > "${STUB_DIR}/src/index.ts" <<TSEOF
/**
 * ${SERVER_ID} — MCP Server stub
 * Generated by mcp-server-stub.sh (SPEC-SE-003)
 *
 * Implements MCP protocol v1 (tools/list, tools/call)
 * without real logic — placeholder for implementation.
 */

import { createServer, Tool, ToolResult } from "@modelcontextprotocol/sdk";

// ── Tool definitions (from catalog.json) ─────────────────────────────────────

const TOOLS: Tool[] = [
  {
    name: "stub_echo",
    description: "Stub tool — echoes the input. Replace with real implementation.",
    inputSchema: {
      type: "object",
      properties: {
        message: { type: "string", description: "Message to echo" },
      },
      required: ["message"],
    },
  },
];

// ── Tool handler ──────────────────────────────────────────────────────────────

async function handleToolCall(
  toolName: string,
  args: Record<string, unknown>
): Promise<ToolResult> {
  switch (toolName) {
    case "stub_echo":
      return {
        content: [
          {
            type: "text",
            text: \`[${SERVER_ID} stub] echo: \${args.message}\`,
          },
        ],
      };
    default:
      throw new Error(\`Unknown tool: \${toolName}\`);
  }
}

// ── Server bootstrap ──────────────────────────────────────────────────────────

const server = createServer({
  name: "${SERVER_ID}",
  version: "0.1.0-stub",
});

server.setRequestHandler("tools/list", async () => ({ tools: TOOLS }));

server.setRequestHandler("tools/call", async (request) => {
  const { name, arguments: args } = request.params;
  return handleToolCall(name, args as Record<string, unknown>);
});

// stdio transport (default for MCP)
server.connect(process.stdin, process.stdout);
TSEOF

# ── package.json ─────────────────────────────────────────────────────────────

PKG_NAME=$(echo "$SERVER_ID" | tr '[:upper:]' '[:lower:]')

cat > "${STUB_DIR}/package.json" <<JSONEOF
{
  "name": "@savia/${PKG_NAME}",
  "version": "0.1.0-stub",
  "description": "${SERVER_VALUE}",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "dev": "ts-node src/index.ts",
    "test": "jest tests/",
    "lint": "eslint src/"
  },
  "dependencies": {
    "@modelcontextprotocol/sdk": "^1.0.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0",
    "ts-node": "^10.9.0",
    "@types/node": "^20.0.0",
    "jest": "^29.0.0"
  },
  "keywords": ["mcp", "savia", "${SERVER_ID}", "model-context-protocol"],
  "license": "MIT",
  "spec": "SE-003"
}
JSONEOF

# ── tests/golden.json ─────────────────────────────────────────────────────────

cat > "${STUB_DIR}/tests/golden.json" <<GOLDEOF
{
  "_comment": "Golden set para ${SERVER_ID} — SPEC-SE-003",
  "_generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "server_id": "${SERVER_ID}",
  "protocol_version": "1.0",
  "golden_cases": [
    {
      "id": "gc-001",
      "description": "tools/list devuelve al menos 1 tool",
      "request": {"method": "tools/list", "params": {}},
      "expected": {"tools_count_min": 1}
    },
    {
      "id": "gc-002",
      "description": "stub_echo responde con texto",
      "request": {
        "method": "tools/call",
        "params": {"name": "stub_echo", "arguments": {"message": "hello"}}
      },
      "expected": {"content_type": "text", "contains": "echo"}
    }
  ]
}
GOLDEOF

echo "Scaffold generado:"
find "${STUB_DIR}" -type f | sort | sed "s|${OUTPUT_DIR}/||"
