#!/usr/bin/env bash
# otel-collector-config.sh — SPEC-SE-009: Genera configuración OTel Collector
set -uo pipefail
#
# Genera la configuración de OpenTelemetry Collector para el workspace Savia
# con el backend indicado. Produce también un docker-compose.observability.yml.
#
# Usage:
#   otel-collector-config.sh [--backend BACKEND] [--output-dir DIR]
#
# Backends:
#   prometheus   (default) — Prometheus + Grafana local
#   loki         — Loki + Grafana para logs
#   datadog      — Datadog exporter (opt-in, requiere API key)
#   newrelic     — New Relic exporter (opt-in)
#   elastic      — Elasticsearch + Kibana
#
# Output:
#   .claude/enterprise/observability/otel-config.yaml
#   .claude/enterprise/observability/docker-compose.observability.yml
#
# Ref: docs/propuestas/savia-enterprise/SPEC-SE-009-observability.md

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

BACKEND="prometheus"
OUTPUT_DIR="${ROOT_DIR}/.claude/enterprise/observability"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend)    BACKEND="$2"; shift 2 ;;
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# //; s/^#//'
      exit 0 ;;
    *) echo "ERROR: unknown arg: $1" >&2; exit 2 ;;
  esac
done

VALID_BACKENDS="prometheus loki datadog newrelic elastic"
if [[ " $VALID_BACKENDS " != *" $BACKEND "* ]]; then
  echo "ERROR: invalid backend '$BACKEND'. Must be one of: $VALID_BACKENDS" >&2; exit 2
fi

mkdir -p "$OUTPUT_DIR"

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── otel-config.yaml ─────────────────────────────────────────────────────────

cat > "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF
# OTel Collector Configuration — Savia Enterprise
# Generated by otel-collector-config.sh (SPEC-SE-009)
# Backend: ${BACKEND} · Generated: ${GENERATED_AT}
# Sovereign mode: all data stays local unless opt-in exporter is enabled.

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "savia-workspace"
          scrape_interval: 15s
          static_configs:
            - targets: ["localhost:9090"]

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
    send_batch_max_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  # PII scrubber — filtra N4 antes de exportar (SPEC-SE-009 §Privacy by design)
  attributes/pii_scrub:
    actions:
      - key: "prompt_content"
        action: delete
      - key: "response_content"
        action: delete
      - key: "user_input"
        action: delete

exporters:
  # ── Local (siempre activo) ────────────────────────────────────────────────
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "savia"
    resource_to_telemetry_conversion:
      enabled: true

  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

YAMLEOF

# Añadir exporter opt-in según backend
case "$BACKEND" in
  prometheus)
    # Ya incluido arriba — nada adicional
    ;;
  loki)
    cat >> "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF

  # Loki (opt-in, requiere Loki server)
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      resource:
        service.name: "service_name"
        service.namespace: "service_namespace"
YAMLEOF
    ;;
  datadog)
    cat >> "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF

  # Datadog (opt-in — requiere DD_API_KEY env var)
  datadog:
    api:
      key: \${env:DD_API_KEY}
    metrics:
      histograms:
        mode: counters
YAMLEOF
    ;;
  newrelic)
    cat >> "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF

  # New Relic (opt-in — requiere NR_API_KEY env var)
  otlp/newrelic:
    endpoint: "otlp.nr-data.net:4317"
    headers:
      api-key: \${env:NR_API_KEY}
YAMLEOF
    ;;
  elastic)
    cat >> "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF

  # Elasticsearch (opt-in — requiere ELASTIC_ENDPOINT env var)
  elasticsearch:
    endpoints:
      - \${env:ELASTIC_ENDPOINT}
    index: "savia-otel"
YAMLEOF
    ;;
esac

# Continuar otel-config con pipelines
cat >> "${OUTPUT_DIR}/otel-config.yaml" <<YAMLEOF

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, attributes/pii_scrub]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes/pii_scrub]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes/pii_scrub]
      exporters: [logging]

# ── Savia custom metrics namespace (SPEC-SE-009 §Métricas Savia estándar) ────
# savia_agent_invocations_total{agent,tenant,model}
# savia_agent_token_budget_used{agent,model}
# savia_agent_duration_seconds{agent,result}
# savia_spec_verification_score{spec,layer}
# savia_context_usage_ratio{session}
# savia_compliance_gate_blocks{gate,reason}
# savia_sovereignty_blocks{layer,pattern}
YAMLEOF

# ── docker-compose.observability.yml ─────────────────────────────────────────

cat > "${OUTPUT_DIR}/docker-compose.observability.yml" <<DCEOF
# Docker Compose — Observability Stack Savia Enterprise
# Generated by otel-collector-config.sh (SPEC-SE-009)
# Backend: ${BACKEND} · Generated: ${GENERATED_AT}
# Run: docker compose -f docker-compose.observability.yml up -d

version: "3.9"

services:
  # ── OTel Collector ───────────────────────────────────────────────────────────
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: savia-otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus metrics
    networks:
      - savia-obs
    restart: unless-stopped

  # ── Prometheus ───────────────────────────────────────────────────────────────
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: savia-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-remote-write-receiver"
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - savia-obs
    restart: unless-stopped

  # ── Grafana ──────────────────────────────────────────────────────────────────
  grafana:
    image: grafana/grafana:11.1.0
    container_name: savia-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=\${GRAFANA_ADMIN_PASSWORD:-savia-local}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - savia-obs
    depends_on:
      - prometheus
    restart: unless-stopped

DCEOF

# Añadir servicios opcionales según backend
case "$BACKEND" in
  loki)
    cat >> "${OUTPUT_DIR}/docker-compose.observability.yml" <<DCEOF
  # ── Loki ─────────────────────────────────────────────────────────────────────
  loki:
    image: grafana/loki:3.1.0
    container_name: savia-loki
    ports:
      - "3100:3100"
    networks:
      - savia-obs
    restart: unless-stopped

DCEOF
    ;;
  elastic)
    cat >> "${OUTPUT_DIR}/docker-compose.observability.yml" <<DCEOF
  # ── Elasticsearch + Kibana ───────────────────────────────────────────────────
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: savia-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - savia-obs
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: savia-kibana
    ports:
      - "5601:5601"
    networks:
      - savia-obs
    depends_on:
      - elasticsearch
    restart: unless-stopped

DCEOF
    ;;
esac

# Cerrar docker-compose
cat >> "${OUTPUT_DIR}/docker-compose.observability.yml" <<DCEOF
networks:
  savia-obs:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
DCEOF

case "$BACKEND" in
  elastic)
    echo "  elastic-data:" >> "${OUTPUT_DIR}/docker-compose.observability.yml"
    ;;
esac

echo "OTel config generado:"
echo "  ${OUTPUT_DIR}/otel-config.yaml"
echo "  ${OUTPUT_DIR}/docker-compose.observability.yml"
echo "Backend: $BACKEND"
