#!/usr/bin/env bash
# sovereign-activate.sh — Configure workspace for sovereign/air-gap deployment
set -uo pipefail
# SPEC: SPEC-SE-005 Sovereign Deployment
#
# Usage:
#   scripts/enterprise/sovereign-activate.sh \
#     --tenant SLUG \
#     --mode sovereign|air-gap|hybrid \
#     --llm-host URL
#
# Creates/updates: tenants/{slug}/deployment.yaml
# In air-gap mode: registers network-egress-guard.sh as a PreToolUse hook
#
# Output JSON: {mode, llm_host, egress_blocked: bool, deployment_yaml: str}

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
MANIFEST="$PROJECT_DIR/.claude/enterprise/manifest.json"
SETTINGS="$PROJECT_DIR/.claude/settings.json"
EGRESS_GUARD="$PROJECT_DIR/.claude/enterprise/hooks/network-egress-guard.sh"

# ---------- arg parsing ----------
TENANT_SLUG=""
MODE=""
LLM_HOST=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tenant)   TENANT_SLUG="$2"; shift 2 ;;
    --mode)     MODE="$2";        shift 2 ;;
    --llm-host) LLM_HOST="$2";   shift 2 ;;
    --help|-h)
      echo "Usage: sovereign-activate.sh --tenant SLUG --mode sovereign|air-gap|hybrid --llm-host URL"
      exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$TENANT_SLUG" || -z "$MODE" ]]; then
  echo '{"error":"--tenant and --mode are required"}' >&2
  exit 1
fi

case "$MODE" in
  sovereign|air-gap|hybrid|cloud) ;;
  *)
    echo "{\"error\":\"invalid mode '$MODE' — must be: sovereign, air-gap, hybrid, cloud\"}" >&2
    exit 1 ;;
esac

LLM_HOST="${LLM_HOST:-http://localhost:11434}"

# Determine egress settings
EGRESS_ALLOWED=true
if [[ "$MODE" == "air-gap" || "$MODE" == "sovereign" ]]; then
  EGRESS_ALLOWED=false
fi

TENANT_DIR="$PROJECT_DIR/tenants/$TENANT_SLUG"
if [[ ! -d "$TENANT_DIR" ]]; then
  mkdir -p "$TENANT_DIR/projects" "$TENANT_DIR/agent-memory" "$TENANT_DIR/secrets"
  cat > "$TENANT_DIR/secrets/.gitignore" << 'EOF'
*
!.gitignore
EOF
fi

DEPLOY_YAML="$TENANT_DIR/deployment.yaml"

# Write deployment.yaml
python3 - "$DEPLOY_YAML" "$TENANT_SLUG" "$MODE" "$LLM_HOST" "$EGRESS_ALLOWED" << 'PYEOF'
import sys
from datetime import datetime, timezone

deploy_path, slug, mode, llm_host, egress_str = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5]
egress_allowed = egress_str.lower() == 'true'

content = f"""# Sovereign Deployment Configuration
# Tenant: {slug}
# Generated by sovereign-activate.sh
# DO NOT commit if llm_host contains credentials

tenant: {slug}
mode: {mode}
configured_at: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}

llm:
  provider: {"anthropic" if mode in ("cloud", "hybrid") else "ollama"}
  host: {llm_host}
  models:
    agent: {"claude-opus-4-5" if mode in ("cloud", "hybrid") else "qwen2.5:32b"}
    mid: {"claude-sonnet-4-5" if mode in ("cloud", "hybrid") else "qwen2.5:7b"}
    fast: {"claude-haiku-3-5" if mode in ("cloud", "hybrid") else "qwen2.5:3b"}

network:
  egress_allowed: {str(egress_allowed).lower()}
  allowed_hosts: []
"""
with open(deploy_path, 'w') as f:
    f.write(content)
print("ok")
PYEOF

# Enable sovereign-deployment module in manifest
if [[ -f "$MANIFEST" ]]; then
  python3 - "$MANIFEST" << 'PYEOF'
import json, sys
path = sys.argv[1]
with open(path) as f:
    d = json.load(f)
d.setdefault('modules', {}).setdefault('sovereign-deployment', {})['enabled'] = True
with open(path, 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
PYEOF
fi

# Register network-egress-guard hook for air-gap mode
HOOK_REGISTERED=false
if [[ "$MODE" == "air-gap" && -f "$EGRESS_GUARD" && -f "$SETTINGS" ]]; then
  python3 - "$SETTINGS" "$EGRESS_GUARD" << 'PYEOF'
import json, sys, os
settings_path, guard = sys.argv[1], sys.argv[2]
with open(settings_path) as f:
    s = json.load(f)
hooks = s.setdefault('hooks', {})
pre = hooks.setdefault('PreToolUse', [])
for h in pre:
    if isinstance(h, dict):
        for hook in h.get('hooks', []):
            if isinstance(hook, dict) and hook.get('command') == guard:
                print("already-registered")
                sys.exit(0)
pre.append({
    "matcher": "Bash",
    "hooks": [{"type": "command", "command": guard}]
})
with open(settings_path, 'w') as f:
    json.dump(s, f, indent=2)
    f.write('\n')
print("registered")
PYEOF
  HOOK_REGISTERED=true
fi

# Output
python3 - "$MODE" "$LLM_HOST" "$EGRESS_ALLOWED" "$TENANT_SLUG" "$DEPLOY_YAML" "$HOOK_REGISTERED" << 'PYEOF'
import json, sys
mode, llm_host, egress_str, tenant, deploy_yaml, hook_str = \
    sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]
print(json.dumps({
    'mode': mode,
    'tenant': tenant,
    'llm_host': llm_host,
    'egress_blocked': egress_str.lower() != 'true',
    'egress_guard_registered': hook_str == 'true',
    'deployment_yaml': deploy_yaml,
    'sovereign_ready': mode in ('sovereign', 'air-gap')
}, indent=2))
PYEOF
