#!/usr/bin/env bash
# tenant-create.sh — Create a new Savia Enterprise tenant
set -uo pipefail
# SPEC: SE-002 Extension Points / SPEC-SE-002 Multi-Tenant
#
# Usage:
#   scripts/enterprise/tenant-create.sh --slug NAME --display "Display Name" [--admin-user USER]
#
# Creates:
#   tenants/{slug}/projects/
#   tenants/{slug}/agent-memory/
#   tenants/{slug}/secrets/        (gitignored)
#   tenants/{slug}/rbac.yaml       (3 roles: reader, developer, admin)
#
# Registers in .claude/enterprise/manifest.json if multi-tenant.enabled = true

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
MANIFEST="$PROJECT_DIR/.claude/enterprise/manifest.json"

# ---------- arg parsing ----------
SLUG=""
DISPLAY=""
ADMIN_USER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --slug)       SLUG="$2";       shift 2 ;;
    --display)    DISPLAY="$2";    shift 2 ;;
    --admin-user) ADMIN_USER="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: tenant-create.sh --slug SLUG --display NAME [--admin-user USER]"
      exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$SLUG" ]]; then
  echo '{"error":"--slug is required"}' >&2
  exit 1
fi

# Validate slug: lowercase alphanumeric + hyphens only
if ! echo "$SLUG" | grep -qE '^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$'; then
  echo "{\"error\":\"slug '$SLUG' is invalid — use lowercase alphanumeric and hyphens\"}" >&2
  exit 1
fi

TENANT_DIR="$PROJECT_DIR/tenants/$SLUG"
if [[ -d "$TENANT_DIR" ]]; then
  echo "{\"error\":\"tenant '$SLUG' already exists at $TENANT_DIR\"}" >&2
  exit 1
fi

# ---------- create structure ----------
mkdir -p \
  "$TENANT_DIR/projects" \
  "$TENANT_DIR/agent-memory" \
  "$TENANT_DIR/secrets"

# .gitignore for secrets
cat > "$TENANT_DIR/secrets/.gitignore" << 'EOF'
# Tenant secrets — never commit
*
!.gitignore
EOF

# rbac.yaml with 3 default roles
DISPLAY_VAL="${DISPLAY:-$SLUG}"
ADMIN_VAL="${ADMIN_USER:-}"

cat > "$TENANT_DIR/rbac.yaml" << RBAC
# Tenant: ${SLUG}
# Auto-generated by tenant-create.sh — edit to customise
tenant: ${SLUG}
display_name: "${DISPLAY_VAL}"

${ADMIN_VAL:+admin_user: ${ADMIN_VAL}
}
roles:
  reader:
    description: "Read-only access to sprint status and memory"
    commands:
      - sprint-status
      - help
      - memory-recall
    gates: []

  developer:
    description: "Standard development access"
    inherits: reader
    commands:
      - "spec-*"
      - "pbi-*"
      - "dev-session-*"
      - "daily-*"
    gates: []

  admin:
    description: "Full tenant administration"
    inherits: developer
    commands:
      - "tenant-*"
      - "rbac-*"
      - "backup-*"
      - "enterprise-*"
    gates:
      - confirm_destructive

users: {}
RBAC

# tenant metadata
cat > "$TENANT_DIR/tenant.yaml" << META
slug: ${SLUG}
display_name: "${DISPLAY_VAL}"
created_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
${ADMIN_VAL:+admin_user: ${ADMIN_VAL}}
META

# ---------- register in manifest if multi-tenant enabled ----------
REGISTERED=false
if [[ -f "$MANIFEST" ]] && command -v python3 >/dev/null 2>&1; then
  ENABLED=$(python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
print(str(d.get('modules', {}).get('multi-tenant', {}).get('enabled', False)).lower())
" "$MANIFEST" 2>/dev/null || echo "false")

  if [[ "$ENABLED" == "true" ]]; then
    python3 - "$MANIFEST" "$SLUG" "$DISPLAY_VAL" << 'PYEOF'
import json, sys
manifest_path, slug, display = sys.argv[1], sys.argv[2], sys.argv[3]
with open(manifest_path) as f:
    d = json.load(f)
tenants = d.setdefault('tenants', {})
tenants[slug] = {"display_name": display, "created_at": __import__('datetime').datetime.utcnow().isoformat() + 'Z'}
with open(manifest_path, 'w') as f:
    json.dump(d, f, indent=2)
    f.write('\n')
PYEOF
    REGISTERED=true
  fi
fi

# ---------- output ----------
python3 -c "
import json, sys
print(json.dumps({
  'created': True,
  'slug': sys.argv[1],
  'display_name': sys.argv[2],
  'tenant_dir': sys.argv[3],
  'directories': ['projects', 'agent-memory', 'secrets'],
  'rbac_roles': ['reader', 'developer', 'admin'],
  'registered_in_manifest': sys.argv[4] == 'true'
}, indent=2))
" "$SLUG" "$DISPLAY_VAL" "$TENANT_DIR" "$REGISTERED"
