#!/usr/bin/env bash
# index-docs.sh — Index Savia documentation into a SaviaVault context dome
# Creates a knowledge vault from the Savia workspace docs/ directory.
# Copyright (c) 2026 Savia. MIT License.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ROOT="${1:-$(git -C "$PROJECT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "$PROJECT_DIR/../..")}"
SAVIA_ROOT="${SAVIA_ROOT:-$ROOT}"
VAULT_PATH="${2:-${SAVIA_ROOT}/vaults/savia-docs}"
DOCS_DIR="${SAVIA_ROOT}/docs"

echo "==> Indexing Savia documentation into SaviaVaults dome"
echo "    Source: $DOCS_DIR"
echo "    Vault:  $VAULT_PATH"
echo ""

# ── Init vault ──
mkdir -p "$VAULT_PATH"
if [[ ! -d "$VAULT_PATH/.git" ]]; then
  cd "$VAULT_PATH" && git init && git config user.name "SaviaVaults" && git config user.email "vault@savia.local"
fi
cd "$VAULT_PATH"

# ── INDEX.md (content map) ──
cat > INDEX.md << 'INDEXEOF'
# Savia Documentation — Content Map

> Auto-generated by SaviaVaults index-docs.sh
> Source: docs/ directory of pm-workspace

## Structure

- **rules/** — Domain rules (25 critical rules)
- **specs/** — Technical specifications (SE-xxx)
- **decisions/** — Architecture Decision Records (ADR)
- **guides_es/** — Spanish guides
- **getting-started/** — Onboarding docs
- **propuestas/** — Proposals

## Key Documents

| Document | Description |
|---|---|
| critical-facts.md | Invariant workspace facts (SPEC-185) |
| ROADMAP.md | Unified roadmap (v6.24.4, 245+ specs) |
| STRUCTURE.md | Workspace directory layout |
| STYLE-GUIDE.md | Writing and formatting conventions |
| memory-system.md | Memory tier architecture (L0-L3) |
| corporate-model.md | Corporate governance model |
INDEXEOF

# ── MAP.md (routing table) ──
cat > MAP.md << 'MAPEOF'
# Savia Documentation — Routing Table

> Maps domain topics to document paths for AI agent navigation.

## Topic → Path

| Topic | Path | Keywords |
|---|---|---|
| Architecture | specs/ | architect, layers, patterns, SOLID |
| Security | rules/domain/ | OWASP, PII, credentials, secrets |
| Git Workflow | rules/domain/ | commit, branch, PR, merge |
| Memory System | memory-system.md | recall, save, L0-L3, MEMORY.md |
| Sprint Management | rules/domain/ | sprint, velocity, burndown, capacity |
| SDD Workflow | rules/domain/ | spec, implement, review, approve |
| Confidentiality | rules/domain/ | N1-N4b, PII, shield, sign |
| Autonomous Safety | rules/domain/ | overnight, agent, safety, reviewer |
| Skills Catalog | rules/domain/ | skill, SKILL.md, maturity, kanban |
| CI/CD | rules/domain/ | pipeline, gate, pr-plan, push |
| Knowledge Graph | rules/domain/ | entity, relation, SQLite, query |
| Ubiquitous Language | rules/domain/ | glossary, domain, term, CONTEXT.md |
MAPEOF

# ── Index all docs ──
INDEXED=0
SKIPPED=0

index_file() {
  local src="$1" rel="$2"
  if [[ "$rel" =~ \.(md|yaml|yml|json|txt)$ ]]; then
    local dst="$VAULT_PATH/$rel"
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    INDEXED=$((INDEXED + 1))
  else
    SKIPPED=$((SKIPPED + 1))
  fi
}

echo "    Copying documentation files..."
while IFS= read -r -d '' file; do
  rel="${file#$DOCS_DIR/}"
  index_file "$file" "docs/$rel"
done < <(find "$DOCS_DIR" -type f \( -name "*.md" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" -o -name "*.txt" \) \
  ! -path "*/.git/*" ! -path "*/node_modules/*" \
  -print0 2>/dev/null || true)

# ── Also index key root-level docs ──
echo "    Copying root-level documents..."
for f in "$SAVIA_ROOT"/{CLAUDE.md,SKILLS.md,AGENTS.md,README.md,README.es.md,CRITERIO.md,CONSTITUCION.md}; do
  if [[ -f "$f" ]]; then
    rel="root/$(basename "$f")"
    mkdir -p "$VAULT_PATH/root"
    cp "$f" "$VAULT_PATH/$rel"
    INDEXED=$((INDEXED + 1))
  fi
done

# ── Git commit ──
cd "$VAULT_PATH"
git add -A 2>/dev/null || true
git commit -m "index: Savia documentation snapshot ($(date +%Y-%m-%d))" 2>/dev/null || true

echo ""
echo "    Indexed: $INDEXED files"
echo "    Skipped: $SKIPPED files"
echo "    Vault:   $VAULT_PATH"
echo ""
echo "    Start server: cd $VAULT_PATH && savia-vaults serve --transport mcp"
