#!/usr/bin/env bash
# calibrate.sh — SPEC-125 Slice 3: derive feedback memories from followups.
#
# Reads audit records under output/recommendation-tribunal/<date>/*.json that
# have user_response_classification ∈ {fp, fn} and writes calibration feedback
# memories to ~/.claude/external-memory/auto/feedback_tribunal_calibration_*.md
# (one per record, named by draft_hash prefix).
#
# Calibration policy (no model retraining):
#   fp (false positive — tribunal vetoed correct advice):
#     -> emit a memory that documents the pattern that was overblocked, so
#        future judges relax the rule for the same domain or pattern.
#   fn (false negative — tribunal passed bad advice):
#     -> emit a memory that documents the missed pattern + which judge should
#        have caught it, so future judges raise sensitivity in that area.
#
# The memories live alongside the existing feedback_*.md files and are loaded
# lazily by the judges in subsequent turns. The tribunal "learns" via context,
# not via fine-tuning.
#
# Spec: docs/propuestas/SPEC-125-recommendation-tribunal-realtime.md sec 6.
# Rule: docs/rules/domain/tribunal-calibration.md.
#
# Usage:
#   calibrate.sh                      # process all records, emit memories
#   calibrate.sh --dry-run            # show what would be emitted, no writes
#   calibrate.sh --from YYYY-MM-DD    # filter
#   calibrate.sh --to YYYY-MM-DD
#   calibrate.sh --memory-dir <path>  # override default ~/.claude/external-memory/auto
#   calibrate.sh --audit-dir <path>   # override default

set -uo pipefail

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
AUDIT_DIR="${RECOMMENDATION_TRIBUNAL_AUDIT_DIR:-$ROOT_DIR/output/recommendation-tribunal}"
MEMORY_DIR="${RECOMMENDATION_TRIBUNAL_MEMORY_DIR:-$HOME/.claude/external-memory/auto}"
DRY_RUN=0
FROM_DATE=""
TO_DATE=""

usage() {
  cat <<EOF
Usage: $0 [--dry-run] [--from YYYY-MM-DD] [--to YYYY-MM-DD]
          [--audit-dir <path>] [--memory-dir <path>]
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)     DRY_RUN=1; shift ;;
    --from)        FROM_DATE="${2:-}"; shift 2 ;;
    --to)          TO_DATE="${2:-}"; shift 2 ;;
    --audit-dir)   AUDIT_DIR="${2:-}"; shift 2 ;;
    --memory-dir)  MEMORY_DIR="${2:-}"; shift 2 ;;
    -h|--help)     usage ;;
    *)             echo "ERROR: unknown argument: $1" >&2; usage ;;
  esac
done

[ -d "$AUDIT_DIR" ] || { echo "ERROR: audit-dir missing: $AUDIT_DIR" >&2; exit 3; }

if [ "$DRY_RUN" -eq 0 ]; then
  mkdir -p "$MEMORY_DIR" 2>/dev/null || { echo "ERROR: cannot create memory-dir: $MEMORY_DIR" >&2; exit 4; }
fi

date_in_range() {
  local d="$1"
  [ -z "$FROM_DATE" ] || [[ "$d" > "$FROM_DATE" || "$d" = "$FROM_DATE" ]] || return 1
  [ -z "$TO_DATE" ]   || [[ "$d" < "$TO_DATE"   || "$d" = "$TO_DATE"   ]] || return 1
  return 0
}

processed=0
emitted_fp=0
emitted_fn=0
skipped_neutral=0
skipped_no_followup=0

for date_dir in "$AUDIT_DIR"/*/; do
  [ -d "$date_dir" ] || continue
  d=$(basename "$date_dir")
  [[ "$d" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || continue
  date_in_range "$d" || continue
  for jf in "$date_dir"*.json; do
    [ -f "$jf" ] || continue
    processed=$((processed + 1))
    classif=$(python3 -c '
import json, sys
try:
  d = json.load(open(sys.argv[1], encoding="utf-8"))
  print(d.get("user_response_classification", "none"))
except Exception:
  print("none")
' "$jf")
    case "$classif" in
      none)    skipped_no_followup=$((skipped_no_followup + 1)); continue ;;
      neutral) skipped_neutral=$((skipped_neutral + 1)); continue ;;
      fp)      emitted_fp=$((emitted_fp + 1)) ;;
      fn)      emitted_fn=$((emitted_fn + 1)) ;;
      *)       continue ;;
    esac
    record=$(cat "$jf")
    short_hash=$(printf '%s' "$record" | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("draft_hash") or "unknown")[:12])')
    preview=$(printf '%s' "$record" | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("draft_preview") or "").replace(chr(10), " ").strip()[:160])')
    verdict=$(printf '%s' "$record" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("verdict") or d.get("final_verdict") or "?")')
    followup=$(printf '%s' "$record" | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("user_response_followup") or "").replace(chr(10), " ").strip()[:300])')
    risk=$(printf '%s' "$record" | python3 -c 'import json,sys; d=json.load(sys.stdin); c=d.get("classification") or {}; print(c.get("risk_class") or "?")')
    out_file="$MEMORY_DIR/feedback_tribunal_calibration_${classif}_${short_hash}.md"
    if [ "$DRY_RUN" -eq 1 ]; then
      echo "[dry-run] would emit: $out_file ($classif, risk=$risk)"
      continue
    fi
    {
      echo "# feedback_tribunal_calibration_${classif} — ${short_hash}"
      echo
      echo "<!-- generated by scripts/recommendation-tribunal/calibrate.sh — do not hand-edit. -->"
      echo "<!-- spec: SPEC-125 sec 6, rule: docs/rules/domain/tribunal-calibration.md -->"
      echo
      if [ "$classif" = "fp" ]; then
        echo "**Pattern**: tribunal vetoed an actually-correct recommendation. Future judges should relax sensitivity for this domain."
      else
        echo "**Pattern**: tribunal passed a recommendation the user later marked as wrong. Future judges should raise sensitivity for this domain."
      fi
      echo
      echo "## Original draft (preview)"
      echo
      echo "> $preview"
      echo
      echo "## Original verdict"
      echo
      echo "- verdict: \`$verdict\`"
      echo "- risk_class: \`$risk\`"
      echo
      echo "## User followup"
      echo
      echo "> $followup"
      echo
      echo "## Calibration directive for future judges"
      echo
      if [ "$classif" = "fp" ]; then
        echo "If a future draft matches the pattern above (same domain, same risk class)"
        echo "and the only veto trigger is the same rule that fired here, judges should"
        echo "downgrade VETO to WARN and surface the conflict for the user to resolve"
        echo "instead of blocking. Cite this calibration entry in the banner."
      else
        echo "If a future draft matches the pattern above, judges should treat the"
        echo "specific phrase or entity as a high-risk signal and demand explicit"
        echo "verification before passing. Cite this calibration entry in the banner."
      fi
    } > "$out_file"
  done
done

echo "calibrate: processed=$processed emitted_fp=$emitted_fp emitted_fn=$emitted_fn skipped_neutral=$skipped_neutral skipped_no_followup=$skipped_no_followup"
