#!/usr/bin/env bash
# Reporter: generic-alert.sh (SE-279)
# Generates a human-readable alert report from detector JSON output.
# Uses LLM (fast model) only if available, otherwise plain JSON dump.

set -uo pipefail

DETECTOR=""; DATA=""; OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --detector) DETECTOR="$2"; shift 2 ;;
    --data) DATA="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done

[[ -z "$DETECTOR" ]] && { echo '{"error":"--detector required"}' >&2; exit 1; }
[[ -z "$DATA" ]] && { echo '{"error":"--data required"}' >&2; exit 1; }
[[ -z "$OUTPUT" ]] && OUTPUT="/dev/stdout"

SUMMARY=$(echo "$DATA" | python3 -c "import sys,json; print(json.load(sys.stdin).get('summary','Alert triggered'))" 2>/dev/null || echo "Alert triggered")
ITEMS=$(echo "$DATA" | python3 -c "import sys,json; items=json.load(sys.stdin).get('items',[]); [print(f'- {i}') for i in items]" 2>/dev/null || echo "$DATA")

# Try LLM-enhanced report via savia-dual
ENHANCED=""
if command -v savia-dual &>/dev/null; then
  PROMPT="You are a monitoring reporter for Savia workspace. Generate a brief, direct alert report in Spanish based on this detector data. Format as Markdown. Be concise, zero filler.

Detector: $DETECTOR
Data: $DATA

Output format:
# [DETECTOR_NAME] Alert
**Date**: [date] | **Severity**: [info/warning/critical]
[1-2 sentence summary]
[Key items list]"

  ENHANCED=$(echo "$PROMPT" | savia-dual --model fast --json --timeout 30 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('content',''))" 2>/dev/null || true)
fi

{
  if [[ -n "$ENHANCED" ]]; then
    echo "$ENHANCED"
  else
    echo "# $DETECTOR — Alert"
    echo ""
    echo "**Date**: $(date) | **Detector**: $DETECTOR"
    echo ""
    echo "## Summary"
    echo ""
    echo "$SUMMARY"
    echo ""
    echo "## Details"
    echo ""
    echo '```json'
    echo "$DATA" | python3 -m json.tool 2>/dev/null || echo "$DATA"
    echo '```'
  fi
  echo ""
  echo "---"
  echo "*Generated by SE-279 always-on-runner.sh — read-only monitoring*"
} > "$OUTPUT"

echo "{\"reported\":true,\"detector\":\"$DETECTOR\",\"output\":\"$OUTPUT\"}"
