#!/usr/bin/env bash
# code-twin-init.sh — Scaffold estructura vacía de ACT para un proyecto
# Spec: SPEC-190 · Slice 1+2
# Usage:
#   bash scripts/code-twin-init.sh <projects/{slug}>
#   bash scripts/code-twin-init.sh --project <path> [--output <twin_dir>]
# Creates: {project}/code-twin/ (or --output dir) + index.md + manifest.yaml + layer subdirs + DRAFT stubs
# Exit: 0 OK | 1 dir exists | 2 usage error
set -uo pipefail

PROJECT_DIR=""
OUTPUT_DIR=""

# Parse arguments: support both positional and --project / --output flags
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      shift
      [[ $# -eq 0 ]] && { echo "ERROR: --project requires a value" >&2; exit 2; }
      PROJECT_DIR="$1"; shift
      ;;
    --project=*)
      PROJECT_DIR="${1#*=}"; shift
      ;;
    --output)
      shift
      [[ $# -eq 0 ]] && { echo "ERROR: --output requires a value" >&2; exit 2; }
      OUTPUT_DIR="$1"; shift
      ;;
    --output=*)
      OUTPUT_DIR="${1#*=}"; shift
      ;;
    -*)
      echo "ERROR: unknown option: $1" >&2; exit 2
      ;;
    *)
      if [[ -z "$PROJECT_DIR" ]]; then
        PROJECT_DIR="$1"
      else
        echo "ERROR: unexpected argument: $1" >&2; exit 2
      fi
      shift
      ;;
  esac
done

[[ -z "$PROJECT_DIR" ]] && { echo "Usage: code-twin-init.sh <projects/{slug}> | --project <path> [--output <dir>]" >&2; exit 2; }
[[ ! -d "$PROJECT_DIR" ]] && { echo "ERROR: project dir not found: $PROJECT_DIR" >&2; exit 2; }

# Determine twin directory
if [[ -n "$OUTPUT_DIR" ]]; then
  TWIN_DIR="$OUTPUT_DIR"
else
  TWIN_DIR="${PROJECT_DIR}/code-twin"
fi
[[ -d "$TWIN_DIR" ]] && { echo "ERROR: code-twin already exists: $TWIN_DIR" >&2; exit 1; }

SLUG="$(basename "$PROJECT_DIR")"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
DATE_ONLY="$(date -u +"%Y-%m-%d")"

# Detect main language (heuristic: most common source file extension)
detect_language() {
  local dir="$1"
  local py_count ts_count cs_count
  py_count=$(find "$dir" -name "*.py" 2>/dev/null | wc -l)
  ts_count=$(find "$dir" -name "*.ts" -o -name "*.tsx" 2>/dev/null | wc -l)
  cs_count=$(find "$dir" -name "*.cs" 2>/dev/null | wc -l)
  if [[ "$py_count" -ge "$ts_count" && "$py_count" -ge "$cs_count" ]]; then
    echo "python"
  elif [[ "$ts_count" -ge "$cs_count" ]]; then
    echo "typescript"
  elif [[ "$cs_count" -gt 0 ]]; then
    echo "csharp"
  else
    echo "unknown"
  fi
}

DETECTED_LANG="$(detect_language "$PROJECT_DIR")"

# Create directory structure
mkdir -p "${TWIN_DIR}/meta"
mkdir -p "${TWIN_DIR}/domain"
mkdir -p "${TWIN_DIR}/application"
mkdir -p "${TWIN_DIR}/infrastructure/db/seeds"
mkdir -p "${TWIN_DIR}/infrastructure/repos"
mkdir -p "${TWIN_DIR}/infrastructure/external"
mkdir -p "${TWIN_DIR}/api"
mkdir -p "${TWIN_DIR}/frontend"

# Create manifest.yaml
cat > "${TWIN_DIR}/manifest.yaml" << MANIFEST
# Code Twin Manifest — SPEC-190
version: "1.0.0"
created: "${DATE_ONLY}"
project: "${SLUG}"
language: "${DETECTED_LANG}"
modules: []
stale_after_days_default: 7
MANIFEST

# Create README.md
cat > "${TWIN_DIR}/README.md" << READMEFILE
# Application Code Twin — ${SLUG}

> Generated by code-twin-init.sh on ${DATE_ONLY} — SPEC-190

## What is this?

This directory contains a **Code Twin** (ACT) for project \`${SLUG}\`.
Code Twin Files (CTFs) describe the behaviour of application modules
without requiring agents to read full source code.

## Directory layout

\`\`\`
code-twin/
├── manifest.yaml          # Twin metadata (version, project, modules list)
├── README.md              # This file
├── index.md               # CTI — master lazy-load index (≤300 tokens)
├── meta/                  # tech-stack, architecture, constraints
├── domain/                # entities, value-objects, business-rules
├── application/           # use-cases, commands, queries
├── infrastructure/        # db/schema, repos, external clients, config
├── api/                   # routes, auth, dtos, errors
└── frontend/              # components, routing, store, api-contracts
\`\`\`

## Usage

\`\`\`bash
# Verify freshness
bash scripts/code-twin-sync-check.sh .code-twin/ --json

# Generate CTFs from source
python3 scripts/code-twin-generate.py --file src/service.py --output .code-twin/application/

# Lint a CTF
bash scripts/code-twin-lint.sh .code-twin/application/my-service.md
\`\`\`

## Rules

- CTFs marked \`status: DRAFT\` are rejected by the linter.
- Set \`status: STABLE\` only after human review.
- \`stale_after_days\` triggers a warning when exceeded — re-sync with source code.
- Never use a stale CTF for production decisions.
READMEFILE

# Create index.md (CTI)
cat > "${TWIN_DIR}/index.md" << CTI
---
total_modules: 0
total_token_cost: 0
last_full_sync: "${NOW}"
---
# Code Twin Index — ${SLUG}

| module_id | layer | path | provides | tokens |
|-----------|-------|------|----------|--------|

> Auto-generated by code-twin-init.sh · Update manually or via code-twin-extract.sh
> All CTFs must pass: bash scripts/code-twin-lint.sh --index ${TWIN_DIR}/index.md
CTI

# Create meta/tech-stack.md stub
cat > "${TWIN_DIR}/meta/tech-stack.md" << META
---
module_id: tech-stack
layer: meta
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 30
depends_on: []
provides:
  - tech-stack-summary
status: DRAFT
---
# Tech Stack — ${SLUG}

## Languages & Frameworks
<!-- Fill in: language, framework, version -->

## Key Dependencies
<!-- Fill in: name, version, purpose -->

## Architecture Pattern
<!-- Fill in: DDD/Clean/Hexagonal/Layered/etc -->
META

# Create domain DRAFT stubs
for stub in entities value-objects business-rules; do
  cat > "${TWIN_DIR}/domain/${stub}.md" << STUB
---
module_id: ${stub}
layer: domain
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 30
depends_on: []
provides:
  - TODO
status: DRAFT
---
# ${stub} — ${SLUG}

<!-- TODO: document domain ${stub} here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB
done

# Create application DRAFT stubs
for stub in use-cases commands queries; do
  cat > "${TWIN_DIR}/application/${stub}.md" << STUB
---
module_id: ${stub}
layer: application
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 14
depends_on: []
provides:
  - TODO
status: DRAFT
---
# ${stub} — ${SLUG}

<!-- TODO: document application ${stub} here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB
done

# Create infrastructure DRAFT stubs
cat > "${TWIN_DIR}/infrastructure/db/schema.md" << STUB
---
module_id: db-schema
layer: infrastructure
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 30
depends_on: []
provides:
  - TODO
status: DRAFT
---
# DB Schema — ${SLUG}

<!-- TODO: document tables, columns, types, constraints here -->
<!-- Format: ## Table: {name} | column | type | nullable | -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB

cat > "${TWIN_DIR}/infrastructure/repos/example-repository.md" << STUB
---
module_id: ExampleRepository
layer: infrastructure
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 14
depends_on:
  - domain-entities
provides:
  - TODO
status: DRAFT
---
# ExampleRepository — ${SLUG}

<!-- TODO: document repository methods, queries, side effects here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB

cat > "${TWIN_DIR}/infrastructure/external/example-client.md" << STUB
---
module_id: ExampleClient
layer: infrastructure
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 30
depends_on: []
provides:
  - TODO
status: DRAFT
---
# ExampleClient — ${SLUG}

<!-- TODO: document external HTTP client methods, endpoints, timeouts here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB

# Create api DRAFT stubs
for stub in routes error-codes; do
  cat > "${TWIN_DIR}/api/${stub}.md" << STUB
---
module_id: api-${stub}
layer: api
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 7
depends_on: []
provides:
  - TODO
status: DRAFT
---
# api-${stub} — ${SLUG}

<!-- TODO: document API ${stub} here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB
done

# Create frontend DRAFT stubs
cat > "${TWIN_DIR}/frontend/components.md" << STUB
---
module_id: frontend-components
layer: frontend
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 14
depends_on: []
provides:
  - TODO
status: DRAFT
---
# Frontend Components — ${SLUG}

<!-- TODO: document UI components, props, state, behaviour here -->
<!-- Approve and set status: STABLE before running code-twin-lint.sh -->
STUB

echo "OK: code-twin scaffold created at ${TWIN_DIR}"
echo "  layers: meta/ domain/ application/ infrastructure/ api/ frontend/"
echo "  domain stubs: entities.md value-objects.md business-rules.md (DRAFT)"
echo "  application stubs: use-cases.md commands.md queries.md (DRAFT)"
echo "  infrastructure stubs: db/schema.md repos/example-repository.md external/example-client.md (DRAFT)"
echo "  api stubs: routes.md error-codes.md (DRAFT)"
echo "  frontend stubs: components.md (DRAFT)"
echo "  next: edit stubs, set status: STABLE, then run code-twin-extract.sh"
exit 0
