#!/usr/bin/env bash
# code-twin-init.sh — Scaffold estructura vacía de ACT para un proyecto
# Spec: SPEC-190 · Slice 1
# Usage: bash scripts/code-twin-init.sh <projects/{slug}>
# Creates: {slug}/code-twin/ with index.md + layer subdirs
# Exit: 0 OK | 1 dir exists | 2 usage error
set -uo pipefail

PROJECT_DIR="${1:-}"
[[ -z "$PROJECT_DIR" ]] && { echo "Usage: code-twin-init.sh <projects/{slug}>" >&2; exit 2; }
[[ ! -d "$PROJECT_DIR" ]] && { echo "ERROR: project dir not found: $PROJECT_DIR" >&2; exit 2; }

TWIN_DIR="${PROJECT_DIR}/code-twin"
[[ -d "$TWIN_DIR" ]] && { echo "ERROR: code-twin already exists: $TWIN_DIR" >&2; exit 1; }

SLUG="$(basename "$PROJECT_DIR")"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Create directory structure
mkdir -p "${TWIN_DIR}/meta"
mkdir -p "${TWIN_DIR}/domain"
mkdir -p "${TWIN_DIR}/application"
mkdir -p "${TWIN_DIR}/infrastructure/db/seeds"
mkdir -p "${TWIN_DIR}/infrastructure/repos"
mkdir -p "${TWIN_DIR}/infrastructure/external"
mkdir -p "${TWIN_DIR}/api"
mkdir -p "${TWIN_DIR}/frontend"

# Create index.md (CTI)
cat > "${TWIN_DIR}/index.md" << CTI
---
total_modules: 0
total_token_cost: 0
last_full_sync: "${NOW}"
---
# Code Twin Index — ${SLUG}

| module_id | layer | path | provides | tokens |
|-----------|-------|------|----------|--------|

> Auto-generated by code-twin-init.sh · Update manually or via code-twin-extract.sh
> All CTFs must pass: bash scripts/code-twin-lint.sh --index ${TWIN_DIR}/index.md
CTI

# Create meta/tech-stack.md stub
cat > "${TWIN_DIR}/meta/tech-stack.md" << META
---
module_id: tech-stack
layer: meta
version: "0.1.0"
last_sync: "${NOW}"
token_budget: 300
stale_after_days: 30
depends_on: []
provides:
  - tech-stack-summary
status: DRAFT
---
# Tech Stack — ${SLUG}

## Languages & Frameworks
<!-- Fill in: language, framework, version -->

## Key Dependencies
<!-- Fill in: name, version, purpose -->

## Architecture Pattern
<!-- Fill in: DDD/Clean/Hexagonal/Layered/etc -->
META

echo "OK: code-twin scaffold created at ${TWIN_DIR}"
echo "  layers: meta/ domain/ application/ infrastructure/ api/ frontend/"
echo "  next: edit ${TWIN_DIR}/meta/tech-stack.md, then run code-twin-extract.sh"
exit 0
