#!/usr/bin/env bash
set -uo pipefail
# confidentiality-sign.sh — Generate/verify cryptographic signature after audit
#
# Sign: run locally on feature branch before push.
# Verify: runs in CI on PR. Adapts to GitHub Actions merge commit checkout.
#
# Usage:
#   bash scripts/confidentiality-sign.sh sign     # On feature branch
#   bash scripts/confidentiality-sign.sh verify    # In CI pipeline
#   bash scripts/confidentiality-sign.sh status    # Show current

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SIG_FILE="$ROOT_DIR/.confidentiality-signature"
SECRET_FILE="$HOME/.savia/confidentiality-key"
ACTION="${1:-status}"

get_diff_hash() {
  cd "$ROOT_DIR" || exit 2
  local diff=""
  # Strategy 1: PR context (feature branch vs origin/main)
  if git rev-parse --verify origin/main >/dev/null 2>&1; then
    local merge_base
    merge_base=$(git merge-base origin/main HEAD 2>/dev/null || echo "")
    if [ -n "$merge_base" ] && [ "$merge_base" != "$(git rev-parse HEAD)" ]; then
      diff=$(git diff "$merge_base"..HEAD -- . ':!.confidentiality-signature' 2>/dev/null)
    fi
  fi
  # Strategy 2: CI merge commit (GitHub checkout@v4 creates merge)
  if [ -z "$diff" ] && [ -n "${GITHUB_BASE_REF:-}" ]; then
    diff=$(git diff "origin/${GITHUB_BASE_REF}"...HEAD -- . ':!.confidentiality-signature' 2>/dev/null)
  fi
  # Strategy 3: staged changes (signing before first commit)
  if [ -z "$diff" ]; then
    diff=$(git diff --cached -- . ':!.confidentiality-signature' 2>/dev/null)
  fi
  # Strategy 4: last commit diff (post-merge on main)
  if [ -z "$diff" ]; then
    diff=$(git diff HEAD~1..HEAD -- . ':!.confidentiality-signature' 2>/dev/null)
  fi
  printf '%s' "$diff" | sha256sum | awk '{print $1}'
}

ensure_secret() {
  if [ ! -f "$SECRET_FILE" ]; then
    mkdir -p "$(dirname "$SECRET_FILE")"
    openssl rand -hex 32 > "$SECRET_FILE" 2>/dev/null \
      || head -c 32 /dev/urandom | xxd -p -c 64 > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE"
  fi
}

compute_hmac() {
  local key
  key=$(cat "$SECRET_FILE" 2>/dev/null)
  # HMAC only over diff_hash — NOT commit hash (changes with squash)
  printf '%s' "$1" | openssl dgst -sha256 -hmac "$key" 2>/dev/null \
    | awk '{print $NF}'
}

do_sign() {
  echo "Confidentiality Signature — Sign"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  ensure_secret
  local diff_hash branch head_commit timestamp signature
  diff_hash=$(get_diff_hash)
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  branch=$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
  head_commit=$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
  signature=$(compute_hmac "$diff_hash")

  cat > "$SIG_FILE" <<SIGEOF
# Confidentiality audit signature — DO NOT EDIT
# Generated by: scripts/confidentiality-sign.sh sign
# Commit this file with your PR. CI verifies it.
diff_hash=$diff_hash
timestamp=$timestamp
branch=$branch
head_commit=$head_commit
signature=$signature
SIGEOF

  echo "SIGNED"
  echo "  Diff hash:  ${diff_hash:0:16}..."
  echo "  Timestamp:  $timestamp"
  echo "  Branch:     $branch"
  echo "  Commit:     $head_commit"
  echo "  Signature:  ${signature:0:16}..."
  echo ""
  echo "Commit .confidentiality-signature with your PR."
}

do_verify() {
  echo "Confidentiality Signature — Verify"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  if [ ! -f "$SIG_FILE" ]; then
    echo "::error::FAILED: No .confidentiality-signature file."
    exit 1
  fi
  local saved_diff saved_sig
  saved_diff=$(grep '^diff_hash=' "$SIG_FILE" | cut -d= -f2)
  saved_sig=$(grep '^signature=' "$SIG_FILE" | cut -d= -f2)
  if [ -z "$saved_diff" ] || [ -z "$saved_sig" ]; then
    echo "::error::FAILED: Signature file is malformed."
    exit 1
  fi
  local current_diff
  current_diff=$(get_diff_hash)
  echo "  Saved diff hash:   ${saved_diff:0:16}..."
  echo "  Current diff hash: ${current_diff:0:16}..."
  if [ "$current_diff" != "$saved_diff" ]; then
    echo ""
    echo "  Saved:   $saved_diff"
    echo "  Current: $current_diff"
    echo "::error::FAILED: Code changed since audit. Re-sign."
    exit 1
  fi
  # Verify HMAC if secret available (CI may not have it)
  if [ -f "$SECRET_FILE" ]; then
    local expected_sig
    expected_sig=$(compute_hmac "$saved_diff")
    if [ "$expected_sig" != "$saved_sig" ]; then
      echo "::error::FAILED: HMAC signature mismatch."
      exit 1
    fi
    echo "  HMAC:              VERIFIED"
  else
    echo "  HMAC:              SKIPPED (no key in CI)"
  fi
  echo "  Diff hash:         MATCH"
  echo ""
  echo "VERIFIED: Signature valid."
}

do_status() {
  [ ! -f "$SIG_FILE" ] && echo "No signature." && exit 0
  echo "Current signature:"
  grep -v '^#' "$SIG_FILE" | grep -v '^$'
}

case "$ACTION" in
  sign)   do_sign ;;
  verify) do_verify ;;
  status) do_status ;;
  *)      echo "Usage: $0 {sign|verify|status}"; exit 2 ;;
esac
