#!/usr/bin/env bash
set -uo pipefail
# copilot-instructions-generate.sh — SPEC-127 Slice 1
#
# Generates .github/copilot-instructions.md from .claude/agents/*.md and
# CLAUDE.md critical rules. The file is the GitHub Copilot Enterprise
# canonical context — Copilot reads it on every chat session and feeds the
# top portion into the system prompt.
#
# Constraints (per AC-1.3):
#   - Max 120 lines (Copilot tolerates more but the system prompt slot is
#     scarce; keep it tight).
#   - No `@import`s — Copilot does not resolve them.
#   - Idempotent: same agent set + same CLAUDE.md → same output.
#
# Trinity: CLAUDE.md (Claude native) ↔ AGENTS.md (cross-frontend mirror) ↔
# .github/copilot-instructions.md (Copilot canonical). All three derive from
# the same source of truth (.claude/agents/*.md, .claude/skills/*/SKILL.md,
# docs/rules/domain/*).
#
# Usage:
#   bash scripts/copilot-instructions-generate.sh           # stdout (dry run)
#   bash scripts/copilot-instructions-generate.sh --apply   # write target
#   bash scripts/copilot-instructions-generate.sh --check   # exit 1 on drift
#
# Exit codes: 0 ok | 1 drift (--check) | 2 usage | 3 agents dir missing
#
# Reference: SPEC-127 Slice 1 AC-1.3
# Reference: docs/rules/domain/provider-agnostic-env.md

ROOT="${PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
AGENTS_DIR="${AGENTS_DIR:-${ROOT}/.claude/agents}"
TARGET="${COPILOT_INSTRUCTIONS:-${ROOT}/.github/copilot-instructions.md}"
MODE="generate"
MAX_LINES=120

usage() {
  cat <<USG
Usage: copilot-instructions-generate.sh [--apply | --check]

Modes:
  (default)  Print to stdout (dry run)
  --apply    Write atomically to ${TARGET}
  --check    Exit 1 if drift vs on-disk file

Env:
  AGENTS_DIR             default \${ROOT}/.claude/agents
  COPILOT_INSTRUCTIONS   default \${ROOT}/.github/copilot-instructions.md
USG
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)  MODE="apply"; shift ;;
    --check)  MODE="check"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -d "${AGENTS_DIR}" ]] || { echo "ERROR: agents dir not found: ${AGENTS_DIR}" >&2; exit 3; }

# Reuse the extraction primitives from agents-md-generate.sh by sourcing it
# in dry-run-friendly mode. The other script's CLI arg parsing is gated under
# `[[ $# -gt 0 ]]` over its own argv, so sourcing without args is safe.
GEN="${ROOT}/scripts/agents-md-generate.sh"
[[ -f "$GEN" ]] || { echo "ERROR: scripts/agents-md-generate.sh missing" >&2; exit 3; }

extract_field() {
  local file="$1" field="$2"
  awk -v field="^${field}:" '
    /^---$/ { c++; if (c>=2) exit; next }
    c==1 {
      if ($0 ~ field) {
        sub(field, ""); sub(/^[[:space:]]+/, ""); gsub(/^"|"$/, "")
        print; exit
      }
    }
  ' "$file"
}

count_resources() {
  local dir="$1" pattern="$2"
  find "$dir" -maxdepth 2 -name "$pattern" 2>/dev/null | wc -l | tr -d ' '
}

agents_count=$(count_resources "${ROOT}/.claude/agents" "*.md")
skills_count=$(find "${ROOT}/.claude/skills" -maxdepth 2 -name "SKILL.md" 2>/dev/null | wc -l | tr -d ' ')
hooks_count=$(count_resources "${ROOT}/.claude/hooks" "*.sh")
commands_count=$(count_resources "${ROOT}/.claude/commands" "*.md")

build() {
  cat <<HEADER
# Savia — GitHub Copilot Enterprise context

> Auto-generated from \`.claude/agents/*.md\` + workspace rules. Do not edit by hand.
> Source of truth: \`docs/rules/domain/agents-md-source-of-truth.md\` (SE-078).
> Trinity: CLAUDE.md (native) ↔ AGENTS.md (OpenCode) ↔ this file (Copilot).
> Generated by \`scripts/copilot-instructions-generate.sh\` (SPEC-127 Slice 1).

## Project identity

Savia is a PM workspace running ${agents_count} agents, ${skills_count} skills,
${hooks_count} hooks, and ${commands_count} workspace commands. The host code
is multi-language (16 packs). Branching follows \`agent/{topic}-{date}\` for
autonomous work; \`main\` is protected.

## Inviolable rules (PV-01 to PV-05 + workspace constants)

- **No hardcoded credentials.** Use \`\$(cat \$PAT_FILE)\` or env vars.
- **No \`assembleDebug\` for Savia mobile.** Use \`./gradlew buildAndPublish\`.
- **No autonomous merges.** PRs are Draft, AUTONOMOUS_REVIEWER assigned.
- **Workspace path resolution.** Use \`scripts/savia-env.sh\` —
  \`SAVIA_WORKSPACE_DIR\` instead of \`CLAUDE_PROJECT_DIR\`.
- **Provider-agnostic agents.** Frontmatter uses canonical model names
  (\`claude-opus-4-7\`, \`claude-sonnet-4-6\`, \`claude-haiku-4-5-20251001\`);
  runtime resolves to Copilot via \`docs/rules/domain/model-alias-table.md\`.

## Reduced surface caveats (Copilot Enterprise specifics)

Copilot Enterprise differs from Claude Code in three structural ways. Honest
reroutes are documented in SPEC-127 — do not assume Claude-Code primitives:

- **No real-time hook events.** PreToolUse / PostToolUse / Stop are
  unavailable. Safety checks moved to git pre-commit (\`.husky/\`) and CI.
- **No subagent fan-out (Task tool).** Orchestrators run single-shot;
  subagent prompts inline into the parent context (Slice 4).
- **No workspace slash commands.** The 534 \`.claude/commands/\` are exposed
  via MCP server — invoke as MCP tools rather than \`/command-name\` (Slice 3).

## Premium request hygiene (Copilot quota)

Tool attachments inflate premium request count (issue #8030). When acting
under Copilot Enterprise: prefer single-batch reads over many small ones,
use Bash \`grep\`/\`find\` over multiple Read calls, and respect any session
budget warning emitted by \`scripts/copilot-quota-tracker.sh\` (Slice 5).

## Conventions

- **PR titles**: conventional commits (feat/fix/docs/...). Spec PRs use
  \`docs(specs):\`.
- **CHANGELOG**: fragments in \`CHANGELOG.d/\`, one per batch.
- **Tests**: BATS for structural; xUnit/NUnit/MSTest for .NET.
- **Comments**: rare, only for non-obvious WHY.
- **Spec workflow**: PROPOSED → APPROVED → IMPLEMENTED. No agent code without
  approved spec (autonomous-safety §SDD).

## Agents

| Name | Model | Description |
|---|---|---|
HEADER

  # Iterate agents — alphabetical, dedup README — output 3-column compact form
  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    [[ "$(basename "$f")" == "README.md" ]] && continue
    local name model desc
    name=$(extract_field "$f" "name")
    [[ -z "$name" ]] && continue
    model=$(extract_field "$f" "model")
    [[ -z "$model" ]] && model="—"
    desc=$(extract_field "$f" "description")
    desc=$(echo "$desc" | tr -s '[:space:]' ' ' | sed -E 's/^ +| +$//g; s/\|/\\|/g')
    [[ ${#desc} -gt 80 ]] && desc="${desc:0:77}..."
    printf '| %s | %s | %s |\n' "$name" "$model" "$desc"
  done < <(find "${AGENTS_DIR}" -maxdepth 1 -type f -name '*.md' | sort)

  cat <<'FOOTER'

## References

- SPEC-127 (`docs/propuestas/SPEC-127-savia-opencode-copilot-enterprise-compat.md`)
- `docs/rules/domain/provider-agnostic-env.md`
- `docs/rules/domain/model-alias-table.md`
- `docs/rules/domain/autonomous-safety.md`
FOOTER
}

GENERATED=$(build)

# Enforce 120-line cap (AC-1.3) — fail if exceeded; force a regen with
# tighter agent table or reduce footer.
ACTUAL_LINES=$(printf '%s\n' "$GENERATED" | wc -l | tr -d ' ')
if [[ "$ACTUAL_LINES" -gt "$MAX_LINES" ]]; then
  # Truncate agents table — keep top 30 agents alphabetically + footer
  # to stay under cap. The full registry is in AGENTS.md anyway.
  HEADER_LINES=$(printf '%s\n' "$GENERATED" | grep -nE '^## Agents' | head -1 | cut -d: -f1)
  FOOTER_START=$(printf '%s\n' "$GENERATED" | grep -nE '^## References' | head -1 | cut -d: -f1)
  if [[ -n "$HEADER_LINES" && -n "$FOOTER_START" ]]; then
    head_part=$(printf '%s\n' "$GENERATED" | sed -n "1,$((HEADER_LINES + 2))p")
    table_rows=$(printf '%s\n' "$GENERATED" | sed -n "$((HEADER_LINES + 3)),$((FOOTER_START - 2))p" | head -25)
    note_row="| ... | ... | full agent registry in AGENTS.md |"
    footer_part=$(printf '%s\n' "$GENERATED" | sed -n "${FOOTER_START},\$p")
    GENERATED=$(printf '%s\n%s\n%s\n\n%s' "$head_part" "$table_rows" "$note_row" "$footer_part")
  fi
fi

case "$MODE" in
  generate) printf '%s\n' "$GENERATED" ;;
  apply)
    mkdir -p "$(dirname "$TARGET")"
    tmp=$(mktemp)
    printf '%s\n' "$GENERATED" > "$tmp"
    mv "$tmp" "$TARGET"
    echo "wrote ${TARGET} ($(wc -l < "$TARGET") lines)"
    ;;
  check)
    if [[ ! -f "$TARGET" ]]; then
      echo "drift: ${TARGET} missing — run --apply" >&2
      exit 1
    fi
    if diff -u "$TARGET" <(printf '%s\n' "$GENERATED") >/dev/null; then
      echo "in sync"
    else
      echo "drift detected:" >&2
      diff -u "$TARGET" <(printf '%s\n' "$GENERATED") | head -40 >&2
      exit 1
    fi
    ;;
esac
