#!/usr/bin/env bash
# generate-propuestas-index.sh — SE-222 S2: auto-generate docs/propuestas/index.md
#
# Scans all .md files in docs/propuestas/ (root + savia-enterprise/ subdir only,
# non-recursive otherwise) and generates an index table sorted by status:
#   APPROVED → PROPOSED → IMPLEMENTED → ARCHIVED → (other)
#
# Usage:
#   bash scripts/generate-propuestas-index.sh          # generate/overwrite index.md
#   bash scripts/generate-propuestas-index.sh --check  # exit 1 if index is stale
#   bash scripts/generate-propuestas-index.sh --help
#
# Exit codes:
#   0 — success (generate: index written; check: index is up-to-date)
#   1 — check mode: index is stale or missing
#   2 — usage error
#
# Ref: SE-222 S2 OKF Adoptable Patterns (index.md progressive disclosure)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${PROPUESTAS_ROOT_OVERRIDE:-$(cd "$SCRIPT_DIR/.." && pwd)}"
PROPUESTAS_DIR="${PROPUESTAS_DIR_OVERRIDE:-$ROOT_DIR/docs/propuestas}"
INDEX_FILE="${INDEX_FILE_OVERRIDE:-$PROPUESTAS_DIR/index.md}"

# ── helpers ──────────────────────────────────────────────────────────────────

usage() {
  cat <<EOF
Usage: bash scripts/generate-propuestas-index.sh [--check] [--help]

  (no args)   Generate/overwrite $INDEX_FILE
  --check     Exit 1 if the existing index.md is stale (diff vs generated)
  --help      Show this help

Environment overrides (for tests):
  PROPUESTAS_DIR_OVERRIDE   Override propuestas directory
  INDEX_FILE_OVERRIDE       Override output index.md path
  PROPUESTAS_ROOT_OVERRIDE  Override project root
EOF
}

# Extract a frontmatter field from a file.
# Usage: extract_field FILE FIELD
# Returns the value or empty string.
extract_field() {
  local file="$1" field="$2"
  # Only search within the first frontmatter block (between --- delimiters)
  awk -v field="$field" '
    /^---/ { if (in_fm) exit; in_fm=1; next }
    in_fm && $0 ~ "^" field ":" {
      sub("^" field ":[ \t]*", "")
      # Strip surrounding quotes
      gsub(/^["'"'"']|["'"'"']$/, "")
      print
      exit
    }
  ' "$file"
}

# Return sort weight for a status value (lower = first)
status_weight() {
  case "$1" in
    APPROVED)     echo 1 ;;
    PROPOSED)     echo 2 ;;
    IMPLEMENTED)  echo 3 ;;
    ARCHIVED)     echo 4 ;;
    DISCARDED)    echo 5 ;;
    DEPRECATED)   echo 6 ;;
    *)            echo 9 ;;
  esac
}

# ── argument parsing ──────────────────────────────────────────────────────────

MODE="generate"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) MODE="check" ;;
    --help)  usage; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

# ── scan specs ────────────────────────────────────────────────────────────────

if [[ ! -d "$PROPUESTAS_DIR" ]]; then
  echo "ERROR: propuestas directory not found: $PROPUESTAS_DIR" >&2
  exit 1
fi

# Collect .md files: root dir + savia-enterprise/ subdir (1 level deep)
declare -a SPEC_FILES=()
for f in "$PROPUESTAS_DIR"/*.md; do
  [[ -f "$f" ]] || continue
  # Skip the index itself and TEMPLATE
  base="$(basename "$f")"
  [[ "$base" == "index.md" ]] && continue
  SPEC_FILES+=("$f")
done
if [[ -d "$PROPUESTAS_DIR/savia-enterprise" ]]; then
  for f in "$PROPUESTAS_DIR/savia-enterprise"/*.md; do
    [[ -f "$f" ]] || continue
    SPEC_FILES+=("$f")
  done
fi

# ── build rows ────────────────────────────────────────────────────────────────

# Each row: weight|id|title|status|priority|file
declare -a ROWS=()

for f in "${SPEC_FILES[@]}"; do
  # Check file has a frontmatter block
  if ! head -1 "$f" 2>/dev/null | grep -q "^---"; then
    continue
  fi

  # Extract fields — try both spec_id and id
  id="$(extract_field "$f" "spec_id")"
  if [[ -z "$id" ]]; then
    id="$(extract_field "$f" "id")"
  fi
  if [[ -z "$id" ]]; then
    # Fallback: use filename without extension
    id="$(basename "$f" .md)"
  fi

  title="$(extract_field "$f" "title")"
  [[ -z "$title" ]] && title="(no title)"

  status="$(extract_field "$f" "status")"
  [[ -z "$status" ]] && status="UNKNOWN"
  status="${status^^}"  # uppercase

  priority="$(extract_field "$f" "priority")"
  [[ -z "$priority" ]] && priority="—"

  weight="$(status_weight "$status")"
  ROWS+=("${weight}|${id}|${title}|${status}|${priority}")
done

# Sort rows by weight (numeric), then by id (alphabetic)
IFS=$'\n' SORTED_ROWS=($(printf '%s\n' "${ROWS[@]}" | sort -t'|' -k1,1n -k2,2))
unset IFS

SPEC_COUNT="${#SORTED_ROWS[@]}"
TODAY="$(date +%Y-%m-%d)"

# ── generate content ──────────────────────────────────────────────────────────

generate_content() {
  echo "<!-- @generated by scripts/generate-propuestas-index.sh — DO NOT EDIT -->"
  echo "# Propuestas Index — auto-generado ${TODAY} · ${SPEC_COUNT} specs"
  echo ""
  echo "| id | title | status | priority |"
  echo "|---|---|---|---|"

  for row in "${SORTED_ROWS[@]}"; do
    IFS='|' read -r _weight id title status priority <<< "$row"
    # Escape pipe characters in title
    title="${title//|/\|}"
    echo "| ${id} | ${title} | ${status} | ${priority} |"
  done

  echo ""
  echo "---"
  echo ""
  echo "_Source: scripts/generate-propuestas-index.sh_"
}

# ── execute mode ──────────────────────────────────────────────────────────────

GENERATED="$(generate_content)"

if [[ "$MODE" == "check" ]]; then
  if [[ ! -f "$INDEX_FILE" ]]; then
    echo "CHECK FAIL: index.md does not exist at $INDEX_FILE" >&2
    exit 1
  fi
  CURRENT="$(cat "$INDEX_FILE")"
  if [[ "$CURRENT" == "$GENERATED" ]]; then
    echo "CHECK OK: index.md is up-to-date (${SPEC_COUNT} specs)"
    exit 0
  else
    echo "CHECK FAIL: index.md is stale — regenerate with: bash scripts/generate-propuestas-index.sh" >&2
    # Show a brief diff hint
    diff <(echo "$CURRENT") <(echo "$GENERATED") | head -20 >&2 || true
    exit 1
  fi
fi

# generate mode: write the file
printf '%s\n' "$GENERATED" > "$INDEX_FILE"
echo "Generated: $INDEX_FILE (${SPEC_COUNT} specs, ${TODAY})"
exit 0
