#!/usr/bin/env bash
# kpi-review-report.sh — SE-272 S2 Periodic KPI review report
# Period review: evolution, anomalies, proposed amendments, decisions.
# KPI amendment requires dual signatures, versions catalog.
#
# Usage:
#   kpi-review-report.sh generate
#     --engagement CLIENT/ENGAGEMENT
#     --period YYYY-MM
#     [--output-dir DIR]
#   kpi-review-report.sh amend
#     --engagement CLIENT/ENGAGEMENT
#     --kpi-id KPI_ID
#     --field KEY --old-value OLD --new-value NEW
#     --signature-1 "NAME,ROLE" --signature-2 "NAME,ROLE"
#     [--justification "text"]
#   kpi-review-report.sh version-catalog
#     --engagement CLIENT/ENGAGEMENT

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

usage() {
  cat <<'USAGE'
kpi-review-report.sh — SE-272 S2 Periodic KPI review report

Usage:
  kpi-review-report.sh generate
    --engagement CLIENT/ENGAGEMENT
    --period YYYY-MM
    [--output-dir DIR]

  kpi-review-report.sh amend
    --engagement CLIENT/ENGAGEMENT
    --kpi-id KPI_ID
    --field KEY --old-value OLD --new-value NEW
    --signature-1 "NAME,ROLE" --signature-2 "NAME,ROLE"
    [--justification "text"]

  kpi-review-report.sh version-catalog
    --engagement CLIENT/ENGAGEMENT

Period review with evolution, anomalies, amendments, decisions.
Amendments require dual signatures and version tracking.
USAGE
  exit 0
}

die() { echo "ERROR: $*" >&2; exit 1; }

sha256_str() {
  printf '%s' "$1" | sha256sum | cut -d' ' -f1
}

timestamp_utc() {
  date -u +%Y-%m-%dT%H:%M:%SZ
}

get_prev_hash() {
  local file="$1"
  if [[ ! -f "$file" ]] || [[ ! -s "$file" ]]; then
    echo "0000000000000000000000000000000000000000000000000000000000000000"
    return
  fi
  local h
  h="$(grep -o '"hash":"[^"]*"' "$file" | tail -1 | cut -d'"' -f4)"
  echo "${h:-0000000000000000000000000000000000000000000000000000000000000000}"
}

# ── Subcommand: generate ────────────────────────────────────────────

cmd_generate() {
  local engagement="" period="" output_dir=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --engagement) engagement="$2"; shift 2 ;;
      --period)     period="$2";     shift 2 ;;
      --output-dir) output_dir="$2"; shift 2 ;;
      *) die "generate: unknown argument: $1" ;;
    esac
  done

  [[ -z "$engagement" ]] && die "generate: --engagement is required"
  [[ -z "$period"     ]] && die "generate: --period is required"

  local client_eng="${engagement%/*}"
  local eng_slug="${engagement#*/}"
  local eng_dir="${REPO_ROOT}/engagements/${client_eng}/${eng_slug}"
  local kpis_file="${eng_dir}/kpis.yaml"
  local chain_file="${eng_dir}/kpi-chain.jsonl"
  local amend_file="${eng_dir}/kpi-amendments.jsonl"

  if [[ -z "$output_dir" ]]; then
    output_dir="${REPO_ROOT}/output/kpi-review/${client_eng}/${eng_slug}"
  fi
  mkdir -p "$output_dir"

  local ts
  ts="$(timestamp_utc)"
  local report_file="${output_dir}/review-${period}.md"

  # Collect data
  local kpi_count=0 chain_count=0 amend_count=0
  if [[ -f "$kpis_file" ]]; then
    kpi_count="$(grep -cE '^  - id:' "$kpis_file" 2>/dev/null || echo 0)"
  fi
  if [[ -f "$chain_file" ]]; then
    chain_count="$(grep -c . "$chain_file" 2>/dev/null || echo 0)"
  fi
  if [[ -f "$amend_file" ]]; then
    amend_count="$(grep -c . "$amend_file" 2>/dev/null || echo 0)"
  fi

  cat > "$report_file" <<MDEOF
# KPI Review Report — ${engagement}
## Period: ${period}

**Generated:** ${ts}
**Generated by:** scripts/kpi-review-report.sh (SE-272 S2)

---

## Summary

| Metric | Value |
|--------|-------|
| KPIs defined | ${kpi_count} |
| Chain entries | ${chain_count} |
| Amendments (total) | ${amend_count} |
| Period | ${period} |

## KPI Catalog

MDEOF

  if [[ -f "$kpis_file" ]]; then
    echo '```yaml' >> "$report_file"
    cat "$kpis_file" >> "$report_file"
    echo '```' >> "$report_file"
  else
    echo "No KPI catalog defined." >> "$report_file"
  fi

  cat >> "$report_file" <<MDEOF

## Chain Status

MDEOF

  if [[ -f "$chain_file" ]]; then
    local last_hash
    last_hash="$(get_prev_hash "$chain_file")"
    echo "- Entries in chain: ${chain_count}" >> "$report_file"
    echo "- Last chain hash: \`sha256:${last_hash:0:32}...\`" >> "$report_file"
  else
    echo "No chain data." >> "$report_file"
  fi

  cat >> "$report_file" <<MDEOF

## Amendments

MDEOF

  if [[ -f "$amend_file" ]] && [[ -s "$amend_file" ]]; then
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      local a_ts a_kpi a_field a_old a_new a_sig1 a_sig2 a_hash
      a_ts="$(echo "$line"   | grep -o '"ts":"[^"]*"'         | head -1 | cut -d'"' -f4)"
      a_kpi="$(echo "$line"  | grep -o '"kpi_id":"[^"]*"'    | head -1 | cut -d'"' -f4)"
      a_field="$(echo "$line" | grep -o '"field":"[^"]*"'    | head -1 | cut -d'"' -f4)"
      a_old="$(echo "$line"  | grep -o '"old_value":"[^"]*"' | head -1 | cut -d'"' -f4)"
      a_new="$(echo "$line"  | grep -o '"new_value":"[^"]*"' | head -1 | cut -d'"' -f4)"
      a_hash="$(echo "$line" | grep -o '"hash":"[^"]*"'     | head -1 | cut -d'"' -f4)"

      echo "- **${a_ts}** | KPI: \`${a_kpi}\` | Field: \`${a_field}\`" >> "$report_file"
      echo "  - \`${a_old}\` → \`${a_new}\`" >> "$report_file"
      echo "  - Hash: \`${a_hash}\`" >> "$report_file"
    done < "$amend_file"
  else
    echo "No amendments recorded." >> "$report_file"
  fi

  cat >> "$report_file" <<MDEOF

## Decisions

- [ ] Review period data with client
- [ ] Validate antagonist pairs still aligned
- [ ] Check for anomalous improvements
- [ ] Propose amendments if thresholds need adjustment
- [ ] Obtain dual signatures for any amendments

## Sign-off

| Role | Name | Date | Approved |
|------|------|------|----------|
| Client authority |   |   | [ ] |
| Provider authority |   |   | [ ] |
MDEOF

  local report_hash
  report_hash="sha256:$(sha256_str "$(cat "$report_file")")"

  echo "Review report generated: ${report_file}"
  echo "  Hash: ${report_hash}"
}

# ── Subcommand: amend ───────────────────────────────────────────────

cmd_amend() {
  local engagement="" kpi_id="" field="" old_value="" new_value=""
  local sig1="" sig2="" justification=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --engagement)   engagement="$2";   shift 2 ;;
      --kpi-id)       kpi_id="$2";       shift 2 ;;
      --field)        field="$2";        shift 2 ;;
      --old-value)    old_value="$2";    shift 2 ;;
      --new-value)    new_value="$2";    shift 2 ;;
      --signature-1)  sig1="$2";         shift 2 ;;
      --signature-2)  sig2="$2";         shift 2 ;;
      --justification) justification="$2"; shift 2 ;;
      *) die "amend: unknown argument: $1" ;;
    esac
  done

  [[ -z "$engagement" ]] && die "amend: --engagement is required"
  [[ -z "$kpi_id"     ]] && die "amend: --kpi-id is required"
  [[ -z "$field"      ]] && die "amend: --field is required"
  [[ -z "$old_value"  ]] && die "amend: --old-value is required"
  [[ -z "$new_value"  ]] && die "amend: --new-value is required"
  [[ -z "$sig1"       ]] && die "amend: --signature-1 is required (NAME,ROLE)"
  [[ -z "$sig2"       ]] && die "amend: --signature-2 is required (NAME,ROLE)"

  local client_eng="${engagement%/*}"
  local eng_slug="${engagement#*/}"
  local eng_dir="${REPO_ROOT}/engagements/${client_eng}/${eng_slug}"
  mkdir -p "$eng_dir"
  local amend_file="${eng_dir}/kpi-amendments.jsonl"

  local ts
  ts="$(timestamp_utc)"
  local prev_hash
  prev_hash="$(get_prev_hash "$amend_file")"

  local chain_input="${ts}${engagement}${kpi_id}${field}${old_value}${new_value}${sig1}${sig2}${prev_hash}"
  local hash
  hash="sha256:$(sha256_str "$chain_input")"

  local entry
  entry="{\"ts\":\"${ts}\",\"engagement\":\"${engagement}\",\"kpi_id\":\"${kpi_id}\",\"field\":\"${field}\",\"old_value\":\"${old_value}\",\"new_value\":\"${new_value}\",\"justification\":\"${justification}\",\"sig1\":\"${sig1}\",\"sig2\":\"${sig2}\",\"prev_hash\":\"${prev_hash}\",\"hash\":\"${hash}\"}"

  echo "$entry" >> "$amend_file"

  printf '{\n'
  printf '  "ts": "%s",\n' "$ts"
  printf '  "kpi_id": "%s",\n' "$kpi_id"
  printf '  "field": "%s",\n' "$field"
  printf '  "old_value": "%s",\n' "$old_value"
  printf '  "new_value": "%s",\n' "$new_value"
  printf '  "sig1": "%s",\n' "$sig1"
  printf '  "sig2": "%s",\n' "$sig2"
  printf '  "hash": "%s"\n' "$hash"
  printf '}\n'

  echo "OK: amendment recorded"
  echo "    File: ${amend_file}"

  # Update version catalog
  local version_file="${eng_dir}/kpi-versions.jsonl"
  local version_entry
  version_entry="{\"ts\":\"${ts}\",\"kpi_id\":\"${kpi_id}\",\"field\":\"${field}\",\"new_value\":\"${new_value}\",\"hash\":\"${hash}\"}"

  local current_version=1
  if [[ -f "$version_file" ]]; then
    local prev_versions
    prev_versions="$(grep -c "\"kpi_id\":\"${kpi_id}\"" "$version_file" 2>/dev/null || echo 0)"
    current_version=$(( prev_versions + 1 ))
  fi

  echo "$version_entry" >> "$version_file"
  echo "    Version bumped to: ${current_version}"
}

# ── Subcommand: version-catalog ─────────────────────────────────────

cmd_version_catalog() {
  local engagement=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --engagement) engagement="$2"; shift 2 ;;
      *) die "version-catalog: unknown argument: $1" ;;
    esac
  done

  [[ -z "$engagement" ]] && die "version-catalog: --engagement is required"

  local client_eng="${engagement%/*}"
  local eng_slug="${engagement#*/}"
  local version_file="${REPO_ROOT}/engagements/${client_eng}/${eng_slug}/kpi-versions.jsonl"

  if [[ ! -f "$version_file" ]]; then
    echo "No version history for ${engagement}"
    exit 0
  fi

  echo "# KPI Version Catalog — ${engagement}"
  echo ""
  printf "%-22s %-12s %-16s %-20s %s\n" "Timestamp" "KPI ID" "Field" "New Value" "Version"
  printf "%-22s %-12s %-16s %-20s %s\n" "---------" "------" "-----" "---------" "-------"

  local kpi_versions
  declare -A kpi_versions

  local line_num=0
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    line_num=$(( line_num + 1 ))
    local a_ts a_kpi a_field a_new
    a_ts="$(echo "$line"    | grep -o '"ts":"[^"]*"'      | head -1 | cut -d'"' -f4)"
    a_kpi="$(echo "$line"   | grep -o '"kpi_id":"[^"]*"'  | head -1 | cut -d'"' -f4)"
    a_field="$(echo "$line" | grep -o '"field":"[^"]*"'   | head -1 | cut -d'"' -f4)"
    a_new="$(echo "$line"   | grep -o '"new_value":"[^"]*"' | head -1 | cut -d'"' -f4)"

    local key="${a_kpi}"
    local ver="${kpi_versions[$key]:-1}"
    kpi_versions["$key"]=$(( ver + 1 ))

    printf "%-22s %-12s %-16s %-20s v%s\n" "${a_ts}" "${a_kpi}" "${a_field}" "${a_new}" "${kpi_versions[$key]}"
  done < "$version_file"
}

# ── Dispatch ─────────────────────────────────────────────────────────

if [[ $# -eq 0 ]]; then usage; fi

subcmd="$1"; shift

case "$subcmd" in
  generate)        cmd_generate "$@" ;;
  amend)           cmd_amend "$@" ;;
  version-catalog) cmd_version_catalog "$@" ;;
  -h|--help)       usage ;;
  *) echo "ERROR: unknown subcommand: ${subcmd}" >&2; exit 2 ;;
esac
