#!/usr/bin/env bash
# propuestas-index-gen.sh — SE-222 S2: auto-generate INDEX.md for docs/propuestas/
#
# Scans docs/propuestas/*.md, extracts frontmatter (spec_id, title, status,
# priority, effort, era), and generates an INDEX.md grouped by status.
#
# The INDEX.md is marked @generated and should NOT be hand-edited. It is
# regenerated on demand or by a PostToolUse hook (post-spec-edit-reindex.sh).
#
# Sentinel compatibility (SPEC-180): the INDEX.md includes a `@generated`
# marker so other tools know not to touch it.
#
# Modes:
#   default       Generate INDEX.md (overwrites existing)
#   --dry-run     Print to stdout, don't write file
#   --check       Exit 1 if INDEX.md exists but is stale (different from
#                 what would be generated); used by CI
#
# Usage:
#   bash scripts/propuestas-index-gen.sh
#   bash scripts/propuestas-index-gen.sh --dry-run
#   bash scripts/propuestas-index-gen.sh --check
#
# Exit codes:
#   0 — Success (or --check passes)
#   1 — --check failed (stale)
#   2 — Usage error
#
# Ref: SE-222 S2 OKF Adoptable Patterns (index.md progressive disclosure)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROPUESTAS_DIR="${PROPUESTAS_DIR_OVERRIDE:-$PROJECT_ROOT/docs/propuestas}"
INDEX_FILE="${INDEX_FILE_OVERRIDE:-$PROPUESTAS_DIR/INDEX.md}"

MODE="generate"

usage() {
  cat <<EOF
Usage: $0 [--dry-run|--check]

Generate or verify $INDEX_FILE from spec files in $PROPUESTAS_DIR.

Modes:
  default       Generate INDEX.md (overwrites)
  --dry-run     Print to stdout, don't write
  --check       Exit 1 if INDEX.md is stale (different from generated)

Exit codes:
  0  Success / not stale
  1  --check found drift
  2  Usage error

Ref: SE-222 S2 OKF Adoptable Patterns
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) MODE="dry-run"; shift ;;
    --check)   MODE="check"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; usage >&2; exit 2 ;;
  esac
done

[[ ! -d "$PROPUESTAS_DIR" ]] && { echo "ERROR: $PROPUESTAS_DIR not found" >&2; exit 2; }

# Extract a YAML frontmatter field from a file. Returns empty string if absent.
get_field() {
  local file="$1" field="$2"
  awk -v fld="$field" '
    NR==1 && $0 != "---" { exit }
    NR==1 { in_fm=1; next }
    in_fm && /^---$/ { exit }
    in_fm && $0 ~ "^"fld"[[:space:]]*:" {
      sub("^"fld"[[:space:]]*:[[:space:]]*", "")
      gsub(/^"|"$/, "")
      print
      exit
    }
  ' "$file"
}

# Status categories (display order)
STATUSES=(PROPOSED DRAFT APPROVED ACCEPTED IN_PROGRESS IMPLEMENTED DONE DEPRECATED REJECTED DISCARDED SUPERSEDED UNLABELED)

# Normalize a status string to one of the canonical categories (case-insensitive)
normalize_status() {
  local s="$1"
  s="${s^^}"  # uppercase
  for canonical in "${STATUSES[@]}"; do
    [[ "$s" == "$canonical" ]] && { printf '%s' "$canonical"; return; }
  done
  # Special cases
  case "$s" in
    PROPOSED*|PROPUESTO*) printf 'PROPOSED' ;;
    DRAFT*) printf 'DRAFT' ;;
    APPROVED*|APROBADO*) printf 'APPROVED' ;;
    ACCEPTED*|ACEPTADO*) printf 'ACCEPTED' ;;
    IN_PROGRESS*|EN_PROGRESO*) printf 'IN_PROGRESS' ;;
    IMPLEMENTED*|IMPLEMENTADO*|DONE*) printf 'IMPLEMENTED' ;;
    REJECTED*|RECHAZADO*) printf 'REJECTED' ;;
    DEPRECATED*) printf 'DEPRECATED' ;;
    DISCARDED*|DESCARTADO*) printf 'DISCARDED' ;;
    SUPERSEDED*) printf 'SUPERSEDED' ;;
    *) printf 'UNLABELED' ;;
  esac
}

# Generate the INDEX.md content to stdout
generate_index() {
  local total_count=0
  local timestamp
  timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  printf '<!-- @generated by scripts/propuestas-index-gen.sh — DO NOT EDIT -->\n'
  printf '<!-- Last regenerated: %s -->\n' "$timestamp"
  printf '# Specs Index\n\n'
  printf '> Auto-generated index of specs in docs/propuestas/, grouped by status.\n'
  printf '> Ref: SE-222 S2 OKF Adoptable Patterns (index.md progressive disclosure).\n'
  printf '> To regenerate: `bash scripts/propuestas-index-gen.sh`\n\n'

  # Build a sortable table: status|spec_id|title|priority|effort|era|filename
  local tmp
  tmp="$(mktemp)"
  while IFS= read -r -d '' file; do
    # Skip non-spec files (LOG.md, INDEX.md, README.md, etc.)
    local basename_f
    basename_f="$(basename "$file")"
    case "$basename_f" in
      LOG.md|INDEX.md|README.md|index.md|log.md|_template*.md) continue ;;
    esac

    # Skip files without frontmatter
    local first_line
    first_line="$(head -1 "$file" 2>/dev/null)"
    [[ "$first_line" != "---" ]] && continue

    local spec_id title status priority effort era
    spec_id="$(get_field "$file" "spec_id")"
    title="$(get_field "$file" "title")"
    status="$(get_field "$file" "status")"
    priority="$(get_field "$file" "priority")"
    effort="$(get_field "$file" "effort")"
    era="$(get_field "$file" "era")"

    # Fallback: derive spec_id from filename or alternative field "id:"
    if [[ -z "$spec_id" ]]; then
      spec_id="$(get_field "$file" "id")"
    fi
    if [[ -z "$spec_id" ]]; then
      # Extract first SE-NNN or SPEC-NNN pattern from filename
      spec_id="$(basename "$file" .md | grep -oE '^(SE|SPEC)-[A-Z0-9]+(-[0-9]+)?' | head -1)"
    fi
    if [[ -z "$spec_id" ]]; then
      # Use filename as ID (truncated to 25 chars)
      spec_id="$(basename "$file" .md | cut -c1-25)"
    fi

    # Fallback: derive status
    status_norm="$(normalize_status "${status:-UNLABELED}")"

    # Sanitize for table (strip pipe chars, escape backticks)
    title="${title//|/-}"
    priority="${priority//|/-}"
    effort="${effort//|/-}"

    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$status_norm" "$spec_id" "$title" "$priority" "$effort" "$era" "$basename_f" >> "$tmp"
    total_count=$((total_count + 1))
  done < <(find "$PROPUESTAS_DIR" -maxdepth 2 -type f -name "*.md" -print0 | sort -z)

  # Per-status sections (rendered via python to handle empty fields correctly)
  for st in "${STATUSES[@]}"; do
    local count
    count=$(awk -F'\t' -v s="$st" '$1==s' "$tmp" | wc -l)
    [[ "$count" -eq 0 ]] && continue
    printf '## %s (%d)\n\n' "$st" "$count"
    printf '| ID | Title | Priority | Effort | Era | File |\n'
    printf '|---|---|---|---|---|---|\n'
    awk -F'\t' -v s="$st" '$1==s' "$tmp" | sort | python3 -c '
import sys
for line in sys.stdin:
    parts = line.rstrip("\n").split("\t")
    while len(parts) < 7:
        parts.append("")
    _, sid, title, prio, eff, era, fname = parts[:7]
    title = title or "—"
    prio = prio or "—"
    eff = eff or "—"
    era = era or "—"
    if fname:
        print(f"| {sid} | {title} | {prio} | {eff} | {era} | [{fname}](./{fname}) |")
    else:
        print(f"| {sid} | {title} | {prio} | {eff} | {era} | — |")
'
    printf '\n'
  done

  printf -- '---\n\n'
  printf '**Total specs**: %d\n' "$total_count"
  printf '**Source**: `%s`\n' "${PROPUESTAS_DIR#$PROJECT_ROOT/}"

  rm -f "$tmp"
}

case "$MODE" in
  generate)
    generate_index > "$INDEX_FILE.tmp"
    mv "$INDEX_FILE.tmp" "$INDEX_FILE"
    echo "Wrote: $INDEX_FILE"
    ;;
  dry-run)
    generate_index
    ;;
  check)
    current=""
    [[ -f "$INDEX_FILE" ]] && current="$(cat "$INDEX_FILE")"
    generated="$(generate_index)"
    # Strip the timestamp line for comparison
    current_no_ts="$(printf '%s' "$current" | grep -v '^<!-- Last regenerated:')"
    generated_no_ts="$(printf '%s' "$generated" | grep -v '^<!-- Last regenerated:')"
    if [[ "$current_no_ts" != "$generated_no_ts" ]]; then
      echo "STALE: $INDEX_FILE differs from generated (excluding timestamp)" >&2
      echo "Run: bash scripts/propuestas-index-gen.sh" >&2
      exit 1
    fi
    echo "OK: $INDEX_FILE is up-to-date"
    ;;
esac
