#!/usr/bin/env bash
# rules-index-generate.sh — SE-097
set -uo pipefail
# Scans docs/rules/domain/*.md (excluding archive/ subdirs) and generates
# docs/rules/INDEX.md with a Markdown table ordered by context_tier (L1 first).
#
# Usage:
#   bash scripts/rules-index-generate.sh            # generate/update INDEX.md
#   bash scripts/rules-index-generate.sh --check    # exit 1 if stale
#
# Header format:
#   # Rules Index — auto-generated YYYY-MM-DD · N rules
#
# Table columns: context_tier | file | title | spec
#
# Ref: SE-097
# Safety: read-only (except INDEX.md write), set -uo pipefail.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CHECK_MODE=false
[[ "${1:-}" == "--check" ]] && CHECK_MODE=true

RULES_DIR="$PROJECT_ROOT/docs/rules/domain"
INDEX_FILE="$PROJECT_ROOT/docs/rules/INDEX.md"

[[ ! -d "$RULES_DIR" ]] && { echo "ERROR: rules dir not found: $RULES_DIR" >&2; exit 2; }

TODAY=$(date +%Y-%m-%d)

# Generate INDEX content via Python (handles frontmatter extraction cleanly)
TMP_INDEX=$(mktemp)
trap 'rm -f "$TMP_INDEX"' EXIT

python3 - "$RULES_DIR" "$TODAY" > "$TMP_INDEX" <<'PY'
import sys, re, os
from collections import defaultdict

rules_dir, today = sys.argv[1], sys.argv[2]

# Tier order for sorting
TIER_ORDER = {"L1": 0, "L2": 1, "L3": 2, "L4": 3, "": 4}

def parse_frontmatter(content):
    """Extract key/value pairs from YAML frontmatter block."""
    fm = {}
    if not content.startswith("---"):
        return fm
    end = content.find("\n---", 3)
    if end == -1:
        return fm
    block = content[4:end]
    for line in block.splitlines():
        m = re.match(r'^(\w[\w_-]*):\s*(.+)$', line)
        if m:
            fm[m.group(1)] = m.group(2).strip().strip('"\'')
    return fm

def extract_title(content, fm):
    """Get H1 title from content, falling back to frontmatter title key."""
    if "title" in fm:
        return fm["title"]
    # Strip frontmatter
    body = content
    if content.startswith("---"):
        end = content.find("\n---", 3)
        if end != -1:
            body = content[end + 4:]
    for line in body.splitlines()[:30]:
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()[:120]
        if line.startswith("> ") and len(line) > 10:
            return line[2:].strip()[:120]
    return "(no title)"

rows = []
for fname in sorted(os.listdir(rules_dir)):
    if not fname.endswith(".md"):
        continue
    if fname == "INDEX.md":
        continue
    path = os.path.join(rules_dir, fname)
    try:
        with open(path) as fh:
            content = fh.read()
    except Exception:
        continue

    fm = parse_frontmatter(content)

    # Skip archived rules
    if fm.get("archived", "").lower() == "true":
        continue

    tier = fm.get("context_tier", "")
    spec = fm.get("spec_id", fm.get("spec", ""))
    title = extract_title(content, fm)
    # Escape pipes
    title = title.replace("|", "\\|")
    spec_disp = spec.replace("|", "\\|") if spec else "—"

    rows.append((TIER_ORDER.get(tier, 4), tier or "—", fname, title, spec_disp))

rows.sort(key=lambda r: (r[0], r[2]))  # sort by tier then filename

print(f"# Rules Index — auto-generated {today} · {len(rows)} rules")
print()
print("<!-- Generated by scripts/rules-index-generate.sh (SE-097). Do not edit by hand. -->")
print("<!-- Excludes: archived rules (archived: true in frontmatter). -->")
print()
print("| context_tier | file | title | spec |")
print("|---|---|---|---|")

for _, tier, fname, title, spec_disp in rows:
    print(f"| {tier} | [{fname}](domain/{fname}) | {title} | {spec_disp} |")
PY

if $CHECK_MODE; then
    if [[ -f "$INDEX_FILE" ]] && diff -q "$INDEX_FILE" "$TMP_INDEX" >/dev/null 2>&1; then
        echo "OK: docs/rules/INDEX.md is up-to-date"
        exit 0
    else
        echo "FAIL: docs/rules/INDEX.md is stale — run 'bash scripts/rules-index-generate.sh' to regenerate" >&2
        if [[ -f "$INDEX_FILE" ]]; then
            diff "$INDEX_FILE" "$TMP_INDEX" | head -20 >&2
        else
            echo "  INDEX.md does not exist yet" >&2
        fi
        exit 1
    fi
else
    cp "$TMP_INDEX" "$INDEX_FILE"
    line_count=$(wc -l < "$INDEX_FILE")
    rule_count=$(grep -c '^| ' "$INDEX_FILE" || true)
    echo "Generated $INDEX_FILE ($line_count lines, ~$rule_count rule rows)"
fi
