#!/usr/bin/env bash
set -uo pipefail
# Force C locale for deterministic sort + awk text handling across machines
export LC_ALL=C
# skills-md-generate.sh — generate SKILLS.md cross-frontend skills catalog
#
# Mirror of scripts/agents-md-generate.sh for skills. Generates a flat
# catalog of all .opencode/skills/*/SKILL.md so that any frontend (OpenCode,
# Codex, Cursor, ...) can load it as a single instruction file. Supports
# the same modes (default print, --apply, --check) as the agents version.
#
# Reference: SE-078 cross-frontend mirror pattern
# Reference: SPEC-127 OpenCode bootstrap

ROOT="${PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
SKILLS_DIR="${SKILLS_DIR:-${ROOT}/.opencode/skills}"
TARGET="${SKILLS_MD:-${ROOT}/SKILLS.md}"
MODE="generate"
MANIFEST=false
MANIFEST_FILE="${SKILLS_MANIFEST:-${ROOT}/skills-manifest.json}"

usage() {
  cat <<USG
Usage: skills-md-generate.sh [--apply | --check] [--manifest]

Modes:
  (default)  Print SKILLS.md content to stdout (dry run)
  --apply    Write SKILLS.md atomically
  --check    Exit 1 if generated content differs from on-disk SKILLS.md
  --manifest Also generate skills-manifest.json (JSON format, machine-readable)
USG
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)    MODE="apply"; shift ;;
    --check)    MODE="check"; shift ;;
    --manifest) MANIFEST=true; shift ;;
    --help|-h)  usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -d "$SKILLS_DIR" ]] || { echo "ERROR: skills dir not found: $SKILLS_DIR" >&2; exit 3; }

# SE-371: congelación en sesión activa — regenerar SKILLS.md a mitad de una
# conversación invalida el prefijo de instrucciones (prompt cache).
# Sesión activa = env SAVIA_SESSION_ACTIVE=1 o marker del hook cache-hygiene.
if [[ "${MODE:-print}" == "apply" ]]; then
  _cache_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  if [[ "${SAVIA_SESSION_ACTIVE:-0}" == "1" || -f "$_cache_root/data/.cache-session-active" ]]; then
    echo "SKIP: sesión activa (SE-371) — regeneración de SKILLS.md congelada." >&2
    exit 3
  fi
fi

extract_field() {
  local file="$1" field="$2"
  # SE-333 dual-read: canonical metadata.savia.<field> takes precedence;
  # falls back to legacy top-level <field>.
  local savia_key="savia.${field}"
  local v
  v=$(awk -v key="$savia_key" '
    /^---$/ { c++; if (c>=2) exit; next }
    c==1 && $0 ~ key {
      sub(/.*'"${savia_key}"'[[:space:]]*:/, "")
      sub(/^[[:space:]]+/, "")
      gsub(/^"|"$/, "")
      gsub(/^'"'"'|'"'"'$/, "")
      print; exit
    }
  ' "$file")
  if [[ -n "$v" ]]; then
    echo "$v"
    return 0
  fi
  awk -v field="^${field}:" '
    /^---$/ { c++; if (c>=2) exit; next }
    c==1 {
      if ($0 ~ field) {
        sub(field, ""); sub(/^[[:space:]]+/, "")
        if ($0 ~ /^[>|]/) { collecting = 1; buf = ""; next }
        gsub(/^"|"$/, ""); print; exit
      }
      if (collecting) {
        if ($0 ~ /^[[:alpha:]_][^[:space:]]*:/) {
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf); print buf
          collecting = 0; exit
        }
        gsub(/^[[:space:]]+|[[:space:]]+$/, "")
        if ($0 != "") buf = buf " " $0
      }
    }
    END {
      if (collecting) { gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf); print buf }
    }
  ' "$file"
}

# Truncate to $2 characters (not bytes) under LC_ALL=C: longer strings keep
# $2-3 characters plus "...". UTF-8 continuation bytes (0x80-0xBF) do not
# start a character, so the cut never splits a multibyte sequence.
truncate_chars() {
  local s="$1" max="$2" len i n=0 cut=0 b
  len=${#s}
  if [[ $len -le $max ]]; then printf '%s' "$s"; return 0; fi
  for ((i = 0; i < len; i++)); do
    b="${s:i:1}"
    if [[ "$b" < $'\x80' || ! "$b" < $'\xc0' ]]; then
      n=$((n + 1))
      [[ $n -eq $((max - 2)) ]] && cut=$i
    fi
  done
  if [[ $n -gt $max ]]; then printf '%s...' "${s:0:cut}"; else printf '%s' "$s"; fi
}

# Collapse whitespace and truncate; plain text for the JSON manifest.
normalise() {
  local s="$1"
  s=$(printf '%s' "$s" | tr -s '[:space:]' ' ' | sed -E 's/^ +| +$//g')
  truncate_chars "$s" 100
}

# Markdown table cell: normalised text with pipes escaped.
sanitise() {
  local s
  s=$(normalise "$1")
  printf '%s' "${s//|/\\|}"
}

json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

build() {
  cat <<'HEADER'
# SKILLS.md

> Auto-generated from `.opencode/skills/*/SKILL.md`. **Do not edit by hand.**
> Cross-frontend skills catalog. Generated by `scripts/skills-md-generate.sh`.

## How to use

This is the cross-frontend mirror of Savia's skills registry. Claude Code
reads `.opencode/skills/*/SKILL.md` directly; OpenCode v1.14, Codex, Cursor
and other frontends can load this `SKILLS.md` as freeform context. Source
of truth is each individual `SKILL.md`; this index is regenerated when a
skill is added or modified.

To use a skill: read `<path>` and follow its instructions.

## Skills

| Name | Path | Description |
|---|---|---|
HEADER
  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    local name desc rel
    name=$(extract_field "$f" "name")
    [[ -z "$name" ]] && {
      # Fallback: derive name from parent directory
      name=$(basename "$(dirname "$f")")
    }
    desc=$(extract_field "$f" "description")
    desc=$(sanitise "$desc")
    [[ -z "$desc" ]] && desc="—"
    rel="${f#${ROOT}/}"
    printf '| %s | `%s` | %s |\n' "$name" "$rel" "$desc"
  done < <(find -L "${SKILLS_DIR}" -mindepth 2 -maxdepth 4 -name "SKILL.md" -type f ! -path '*/_template/*' | LC_ALL=C sort)
}

# --- Manifest JSON generation (SE-277) ---
build_manifest() {
  local first=true
  printf '{\n'
  printf '  "version": "1.0",\n'
  printf '  "generated_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '  "source": ".opencode/skills/*/SKILL.md",\n'
  printf '  "skills": {\n'

  find -L "${SKILLS_DIR}" -mindepth 2 -maxdepth 4 -name "SKILL.md" -type f ! -path '*/_template/*' | LC_ALL=C sort | while IFS= read -r f; do
    local name desc maturity
    name=$(extract_field "$f" "name")
    [[ -z "$name" ]] && name=$(basename "$(dirname "$f")")
    desc=$(extract_field "$f" "description")
    [[ -z "$desc" ]] && desc="—"
    desc=$(normalise "$desc")
    maturity=$(extract_field "$f" "maturity")
    [[ -z "$maturity" ]] && maturity="unknown"
    local rel="${f#${ROOT}/}"

    $first && first=false || printf ',\n'
    printf '    "%s": {\n' "$(json_escape "$name")"
    printf '      "path": "%s",\n' "$(json_escape "$rel")"
    printf '      "description": "%s",\n' "$(json_escape "$desc")"
    printf '      "maturity": "%s"\n' "$(json_escape "$maturity")"
    printf '    }'
  done

  printf '\n  }\n}\n'
}

GENERATED=$(build)

# Atomic write: temp file in the target directory (same filesystem, so mv is a
# rename) with umask permissions; mktemp alone would leave it 0600.
write_atomic() {
  local dest="$1" tmp
  tmp=$(mktemp "${dest}.tmp.XXXXXX") || { echo "ERROR: cannot create temp file next to $dest" >&2; return 1; }
  cat > "$tmp"
  chmod "$(printf '%o' $(( 0666 & ~$(umask) )))" "$tmp"
  mv "$tmp" "$dest"
}

# generated_at changes on every run; drift is about content only.
strip_timestamp() { grep -v '^  "generated_at": '; }

case "$MODE" in
  generate) printf '%s\n' "$GENERATED" ;;
  apply)
    printf '%s\n' "$GENERATED" | write_atomic "$TARGET" || exit 1
    echo "wrote ${TARGET} ($(wc -l < "$TARGET") lines)"

    if $MANIFEST; then
      build_manifest | write_atomic "$MANIFEST_FILE" || exit 1
      echo "wrote ${MANIFEST_FILE} ($(wc -l < "$MANIFEST_FILE") lines)"
    fi
    ;;
  check)
    exit_code=0
    if [[ ! -f "$TARGET" ]]; then
      echo "drift: $TARGET missing — run --apply" >&2
      exit_code=1
    elif ! diff -u "$TARGET" <(printf '%s\n' "$GENERATED") >/dev/null; then
      echo "drift detected in SKILLS.md — run --apply" >&2
      exit_code=1
    else
      echo "SKILLS.md: in sync"
    fi

    if $MANIFEST; then
      if [[ ! -f "$MANIFEST_FILE" ]]; then
        echo "drift: $MANIFEST_FILE missing — run --apply --manifest" >&2
        exit_code=1
      elif ! diff -u <(strip_timestamp < "$MANIFEST_FILE") <(build_manifest | strip_timestamp) >/dev/null; then
        echo "drift detected in skills-manifest.json — run --apply --manifest" >&2
        exit_code=1
      else
        echo "skills-manifest.json: in sync"
      fi
    fi

    exit $exit_code
    ;;
esac
