#!/usr/bin/env bash
# skill-maturity-audit.sh — SE-167 Skill Maturity Kanban
#
# Classifies every skill in .claude/skills/ into one of:
#   Deprecated  : frontmatter `deprecated: true`
#   Calibrated  : SKILL+DOMAIN ok + has tests/evals + maturity=stable
#   Incomplete  : SKILL+DOMAIN ok but missing tests OR maturity!=stable
#   Stub        : missing DOMAIN.md, SKILL <50 lines, or no body
#
# Usage:
#   bash scripts/skill-maturity-audit.sh                 # writes TSV + markdown
#   bash scripts/skill-maturity-audit.sh --tsv-only      # TSV only
#   bash scripts/skill-maturity-audit.sh --markdown-only # markdown kanban only
#
# Outputs:
#   output/skill-maturity-audit-YYYYMMDD.tsv
#   output/skill-maturity-kanban-YYYYMMDD.md

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$ROOT/.claude/skills"
TESTS_DIR="$ROOT/tests"
OUTPUT_DIR="$ROOT/output"
DATE_STAMP="$(date +%Y%m%d)"
TSV_FILE="$OUTPUT_DIR/skill-maturity-audit-$DATE_STAMP.tsv"
MD_FILE="$OUTPUT_DIR/skill-maturity-kanban-$DATE_STAMP.md"

EMIT_TSV=true
EMIT_MD=true
case "${1:-}" in
  --tsv-only) EMIT_MD=false ;;
  --markdown-only) EMIT_TSV=false ;;
  --help|-h)
    sed -n '2,15p' "$0" | sed 's/^# //'
    exit 0 ;;
esac

mkdir -p "$OUTPUT_DIR"

classify_skill() {
  local dir="$1"
  local name
  name="$(basename "$dir")"
  local skill_md="$dir/SKILL.md"
  local domain_md="$dir/DOMAIN.md"

  # _template excluded (scaffolding, not deployable)
  if [[ "$name" == "_template" ]]; then
    echo "EXCLUDED"
    return
  fi

  # Deprecated: explicit frontmatter marker
  if [[ -f "$skill_md" ]] && grep -qE '^deprecated:\s*true' "$skill_md"; then
    echo "Deprecated"
    return
  fi

  # Stub: missing DOMAIN.md or SKILL <50 lines
  if [[ ! -f "$domain_md" ]]; then
    echo "Stub"
    return
  fi
  local skill_lines=0
  [[ -f "$skill_md" ]] && skill_lines=$(wc -l < "$skill_md")
  if (( skill_lines < 50 )); then
    echo "Stub"
    return
  fi

  # Quality signals
  local maturity
  maturity=$(grep -E '^maturity:' "$skill_md" 2>/dev/null | head -1 | sed 's/^maturity:[[:space:]]*//;s/["'\''"]//g' | tr -d '[:space:]')
  local has_test=false
  if ls "$TESTS_DIR/test-${name}".bats >/dev/null 2>&1 || ls "$TESTS_DIR/evals/"*"${name}"*.bats >/dev/null 2>&1; then
    has_test=true
  fi

  # Calibrated: stable + has test
  if [[ "$maturity" == "stable" && "$has_test" == "true" ]]; then
    echo "Calibrated"
    return
  fi

  # Incomplete: everything else with both files
  echo "Incomplete"
}

# Collect classifications
declare -a STUB=() INCOMPLETE=() CALIBRATED=() DEPRECATED=()

if "$EMIT_TSV"; then
  printf "skill\tstate\tmaturity\thas_test\tskill_lines\n" > "$TSV_FILE"
fi

for dir in "$SKILLS_DIR"/*/; do
  [[ -d "$dir" ]] || continue
  name="$(basename "$dir")"
  state="$(classify_skill "$dir")"
  [[ "$state" == "EXCLUDED" ]] && continue

  skill_md="$dir/SKILL.md"
  maturity="-"
  if [[ -f "$skill_md" ]]; then
    m=$(grep -E '^maturity:' "$skill_md" 2>/dev/null | head -1 | sed 's/^maturity:[[:space:]]*//;s/["'\''"]//g' | tr -d '[:space:]')
    [[ -n "$m" ]] && maturity="$m"
  fi
  has_test="false"
  if ls "$TESTS_DIR/test-${name}".bats >/dev/null 2>&1 || ls "$TESTS_DIR/evals/"*"${name}"*.bats >/dev/null 2>&1; then
    has_test="true"
  fi
  skill_lines=0
  [[ -f "$skill_md" ]] && skill_lines=$(wc -l < "$skill_md")

  if "$EMIT_TSV"; then
    printf "%s\t%s\t%s\t%s\t%d\n" "$name" "$state" "$maturity" "$has_test" "$skill_lines" >> "$TSV_FILE"
  fi

  case "$state" in
    Stub) STUB+=("$name") ;;
    Incomplete) INCOMPLETE+=("$name") ;;
    Calibrated) CALIBRATED+=("$name") ;;
    Deprecated) DEPRECATED+=("$name") ;;
  esac
done

if "$EMIT_MD"; then
  {
    echo "# Skill Maturity Kanban — $DATE_STAMP"
    echo
    echo "> Auto-generated by \`scripts/skill-maturity-audit.sh\` (SE-167)."
    echo "> Input: \`.claude/skills/*/SKILL.md\` + \`tests/test-<skill>.bats\`."
    echo
    echo "## Summary"
    echo
    echo "| State | Count |"
    echo "|---|---|"
    echo "| Calibrated | ${#CALIBRATED[@]} |"
    echo "| Incomplete | ${#INCOMPLETE[@]} |"
    echo "| Stub | ${#STUB[@]} |"
    echo "| Deprecated | ${#DEPRECATED[@]} |"
    echo
    echo "## Calibrated (stable + tests + DOMAIN.md)"
    echo
    if (( ${#CALIBRATED[@]} == 0 )); then echo "_(none)_"; else
      for s in "${CALIBRATED[@]}"; do echo "- $s"; done
    fi
    echo
    echo "## Incomplete (missing tests or non-stable maturity)"
    echo
    if (( ${#INCOMPLETE[@]} == 0 )); then echo "_(none)_"; else
      for s in "${INCOMPLETE[@]}"; do echo "- $s"; done
    fi
    echo
    echo "## Stub (missing DOMAIN.md or <50 lines)"
    echo
    if (( ${#STUB[@]} == 0 )); then echo "_(none)_"; else
      for s in "${STUB[@]}"; do echo "- $s"; done
    fi
    echo
    echo "## Deprecated"
    echo
    if (( ${#DEPRECATED[@]} == 0 )); then echo "_(none)_"; else
      for s in "${DEPRECATED[@]}"; do echo "- $s"; done
    fi
  } > "$MD_FILE"
fi

# Stdout summary
total=$(( ${#CALIBRATED[@]} + ${#INCOMPLETE[@]} + ${#STUB[@]} + ${#DEPRECATED[@]} ))
echo "Skill Maturity Kanban — $DATE_STAMP"
echo "  Total: $total"
echo "  Calibrated: ${#CALIBRATED[@]}"
echo "  Incomplete: ${#INCOMPLETE[@]}"
echo "  Stub: ${#STUB[@]}"
echo "  Deprecated: ${#DEPRECATED[@]}"
if "$EMIT_TSV"; then echo "  TSV: $TSV_FILE"; fi
if "$EMIT_MD"; then echo "  Kanban: $MD_FILE"; fi
exit 0
