#!/usr/bin/env bash
# SPEC-156 Slice 2 prep — migrate flat token_budget to nested object.
# Source of truth: .claude/agents/*.md. .opencode/agents/ regenerated by converter.
set -euo pipefail

ROOT="${SAVIA_WORKSPACE_DIR:-$(git rev-parse --show-toplevel)}"
AGENTS_DIR="$ROOT/.claude/agents"
DRY_RUN="${DRY_RUN:-0}"

# Tier defaults per SPEC-156: per_invocation / context_window_target / escalation_policy
declare -A PER_INV=( [fast]=30000  [mid]=60000  [heavy]=100000 )
declare -A CTX_TGT=( [fast]=8000   [mid]=15000  [heavy]=20000 )
declare -A POLICY=(  [fast]=escalate [mid]=escalate [heavy]=block )

migrated=0; skipped=0; tier_missing=0

for f in "$AGENTS_DIR"/*.md; do
  name=$(basename "$f" .md)
  model=$(awk '/^model:/{print $2; exit}' "$f" | tr -d '"')
  if [[ -z "${PER_INV[$model]:-}" ]]; then
    echo "skip $name: unknown tier '$model'"
    tier_missing=$((tier_missing+1)); continue
  fi

  # Already nested? (next line after token_budget: starts with spaces+per_invocation)
  if grep -q "^token_budget:$" "$f" 2>/dev/null; then
    skipped=$((skipped+1)); continue
  fi

  existing=$(awk '/^token_budget:/{print $2; exit}' "$f")
  ctx="${existing:-${CTX_TGT[$model]}}"
  per="${PER_INV[$model]}"
  pol="${POLICY[$model]}"

  block=$(printf 'token_budget:\n  per_invocation: %s\n  context_window_target: %s\n  escalation_policy: %s' "$per" "$ctx" "$pol")

  if [[ "$DRY_RUN" == "1" ]]; then
    echo "would migrate $name (tier=$model): per=$per ctx=$ctx policy=$pol"
    migrated=$((migrated+1)); continue
  fi

  if grep -q "^token_budget:" "$f"; then
    # Replace existing line
    python3 - "$f" "$block" <<'PY'
import sys, re, pathlib
path = pathlib.Path(sys.argv[1])
block = sys.argv[2]
text = path.read_text()
text = re.sub(r'^token_budget:.*$', block.replace('\n', '\\n'), text, count=1, flags=re.MULTILINE)
text = text.replace('\\n', '\n')
path.write_text(text)
PY
  else
    # Inject before closing --- of frontmatter
    python3 - "$f" "$block" <<'PY'
import sys, pathlib
path = pathlib.Path(sys.argv[1])
block = sys.argv[2]
lines = path.read_text().splitlines(keepends=True)
# locate frontmatter end
if not lines or not lines[0].startswith('---'):
    sys.exit(0)
for i in range(1, len(lines)):
    if lines[i].startswith('---'):
        lines.insert(i, block + '\n')
        break
path.write_text(''.join(lines))
PY
  fi
  migrated=$((migrated+1))
done

echo "migrated=$migrated skipped=$skipped tier_missing=$tier_missing"
