# analysis — Savia Capability Map (L1)
> 50 resources

- **Trace Optimize** (cmd): Optimize trace spans and sampling rates across distributed services
- **agent-activity** (cmd): Show structured activity log of recent agent executions
- **agent-activity** (script): agent-activity.sh — Agent activity dashboard
- **agent-budget-lookup** (script): agent-budget-lookup.sh — Extract token budget from agent frontmatter
- **agent-code-map** (skill): Usar cuando un agente necesita conocer la arquitectura del proyecto sin leer ficheros completos.
- **agent-cost** (cmd): Coste estimado de uso de agentes por sprint/proyecto
- **agent-degradation-canary** (script): agent-degradation-canary.sh — SE-040
- **agent-file-map** (skill): Usar cuando se trabaja con ficheros externos al workspace que los agentes deben localizar.
- **agent-gate** (script): agent-gate.sh — SE-216 Slice 2: inherited quality gates for agent runs
- **agent-hook-runner** (script): agent-hook-runner.sh — SE-202: semantic LLM gate for hooks
- **agent-journal** (script): agent-journal.sh — Append-only JSONL journal para agent-runs autónomos.
- **agent-memory** (cmd): Inspect and manage persistent memory fragments for subagents.
- **agent-run** (cmd): Launch a Claude agent on a Spec or batch of pending specs
- **agent-run-log** (script): agent-run-log.sh — SE-217 Slice 1: append-only agent experiment log
- **agent-run-logger** (script): agent-run-logger.sh — SE-148: AgentRunSummary telemetry logger
- **agent-run-report** (script): agent-run-report.sh — SE-148: AgentRunSummary report generator
- **agent-scratchpad** (script): agent-scratchpad.sh — SE-216 Slice 1: shared state document for parallel agents
- **agent-size-audit** (script): agent-size-audit.sh — SE-038 Slice 1 probe: measure size of every agent.
- **agent-size-remediation-plan** (script): agent-size-remediation-plan.sh — SE-052 Slice 1 agent-size analyzer.
- **agent-surface-guard** (script): agent-surface-guard.sh — SE-217 Slice 3: declared editable surface for agent runs
- **agent-tick** (script): agent-tick.sh — SE-219 S5: light/heavy tick separation (abtop tick_no_summaries pattern)
- **agent-time-budget** (script): agent-time-budget.sh — SE-217 Slice 2: time-budgeted command runner
- **agent-wait-idle** (script): agent-wait-idle.sh — SE-206: detect when an AI agent process is idle
- **bus-factor-report** (script): bus-factor-report.sh -- Informe ejecutivo del scan de Bus Factor.
- **case-recompute** (cmd): Recompute NPV, IRR, and risk-adjusted NPV for a business case
- **ceo-report** (cmd): Informe ejecutivo multi-proyecto para dirección — portfolio, riesgo, equipo, delivery
- **completeness-judge** (agent): Truth Tribunal judge — report covers what its title/abstract promises
- **debt-analyze** (cmd): >
- **debt-track** (cmd): >
- **enterprise-dashboard** (cmd): Enterprise analytics — portfolio metrics, team health, risk matrix, forecasting
- **enterprise/billing-report** (script): billing-report.sh — SE-018 Project Billing (IFRS 15)
- **enterprise/client-health-report** (script): client-health-report.sh — SE-024 Client Health Intelligence
- **eval-improvement-suggest** (script): eval-improvement-suggest.sh — SE-215: generate skill improvement proposals from eval reports
- **executive-reporting** (skill): Usar cuando se genera un informe ejecutivo multi-proyecto para dirección.
- **kpi-dashboard** (cmd): Muestra el dashboard completo con todos los KPIs definidos en docs/kpis-equipo.md.
- **kpi-dora** (cmd): >
- **reconciliation-stats** (script): reconciliation-stats.sh — Append/report reconciliation classification metrics
- **report-capacity** (cmd): Muestra el estado de capacidades del equipo — disponibilidad, asignación y alertas de sobre-carga.
- **report-executive** (cmd): Genera el informe ejecutivo multi-proyecto para dirección en formato Word o PowerPoint.
- **report-hours** (cmd): Genera el informe de imputación de horas del sprint actual o especificado.
- **report-verify** (cmd): Convene the Truth Tribunal (7 judges) to evaluate a report's reliability
- **risk-predict** (cmd): Predicción de riesgo del sprint basada en datos históricos y señales tempranas
- **risk-scoring** (skill): Usar cuando se calcula el riesgo de una tarea para decidir el nivel de revisión requerido.
- **rules-traceability** (skill): Usar cuando se mapean reglas de negocio a PBIs para trazabilidad completa.
- **scope-trace-gate** (script): scope-trace-gate.sh — G13 Scope-trace gate (standalone runner)
- **source-traceability-judge** (agent): Truth Tribunal judge — every claim must have a verifiable @ref citation
- **time-tracking-report** (skill): Usar cuando se generan informes de imputación de horas en Excel o Word.
- **trace-pattern-extractor** (script): trace-pattern-extractor.sh — SPEC-044 Phase 1: analyze agent traces
- **truth-tribunal** (script): truth-tribunal.sh — Orchestrate 7-judge reliability evaluation of reports.
- **weekly-report** (skill): Usar cuando se genera el informe semanal de estado del proyecto.
