# analysis — Savia Capability Map (L1)
> 60 resources

- **/a11y-report** (cmd): Reporte de conformidad de accesibilidad para stakeholders y legal. Tres formatos: ejecutivo (resumen + score), técnico (detalles completos + código), legal (declaración VPAT/Section 508). Tracking de tendencias. Exportable.
- **Trace Optimize** (cmd): Optimize trace spans and sampling rates across distributed services
- **Trace Search** (cmd): Buscar y filtrar trazas across multiple observability platforms with natural language support
- **agent-activity** (cmd): Show structured activity log of recent agent executions
- **agent-activity** (script): agent-activity.sh — Agent activity dashboard
- **agent-budget-lookup** (script): agent-budget-lookup.sh — Extract token budget from agent frontmatter
- **agent-code-map** (skill): Usar cuando un agente necesita conocer la arquitectura del proyecto sin leer ficheros completos.
- **agent-cost** (cmd): Coste estimado de uso de agentes por sprint/proyecto
- **agent-efficiency** (cmd): Ratio de eficiencia de agentes — specs completadas, re-work y tiempos
- **agent-file-map** (skill): Usar cuando se trabaja con ficheros externos al workspace que los agentes deben localizar.
- **agent-journal** (script): agent-journal.sh — Append-only JSONL journal para agent-runs autónomos.
- **agent-memory** (cmd): Inspect and manage persistent memory fragments for subagents.
- **agent-notes-archive** (cmd): >
- **agent-run** (cmd): Launch a Claude agent on a Spec or batch of pending specs
- **agent-run-logger** (script): agent-run-logger.sh — SE-148: AgentRunSummary telemetry logger
- **agent-run-report** (script): agent-run-report.sh — SE-148: AgentRunSummary report generator
- **agent-size-audit** (script): agent-size-audit.sh — SE-038 Slice 1 probe: measure size of every agent.
- **agent-size-remediation-plan** (script): agent-size-remediation-plan.sh — SE-052 Slice 1 agent-size analyzer.
- **agent-trace** (cmd): Dashboard de trazas de ejecución de agentes con tokens, duración y resultado
- **ai-risk-assessment** (cmd): Evaluación de riesgo de agentes según categorías EU AI Act
- **async-standup** (cmd): Recogida asíncrona de standups — cada dev reporta cuando quiera, Savia compila
- **case-recompute** (cmd): Recompute NPV, IRR, and risk-adjusted NPV for a business case
- **ceo-report** (cmd): Informe ejecutivo multi-proyecto para dirección — portfolio, riesgo, equipo, delivery
- **completeness-judge** (agent): Truth Tribunal judge — report covers what its title/abstract promises
- **debt-analyze** (cmd): >
- **debt-budget** (cmd): >
- **debt-prioritize** (cmd): >
- **debt-track** (cmd): >
- **enterprise-dashboard** (cmd): Enterprise analytics — portfolio metrics, team health, risk matrix, forecasting
- **eval-report** (cmd): Generate evaluation report with scoring and analysis
- **excel-report** (cmd): Generar plantillas Excel interactivas con Claude-in-Excel para reporting
- **executive-reporting** (skill): Usar cuando se genera un informe ejecutivo multi-proyecto para dirección.
- **impact-metric** (cmd): >
- **kpi-dashboard** (cmd): Muestra el dashboard completo con todos los KPIs definidos en docs/kpis-equipo.md.
- **kpi-dora** (cmd): >
- **network-incident** (cmd): Gestión del ciclo de vida de incidentes de red con reporte, clasificación, escalado y resolución
- **order-track** (cmd): Gestiona pedidos: crear, actualizar estado, cumplir, procesar devoluciones y reportes
- **org-metrics** (cmd): Métricas DORA y de delivery agregadas a nivel de organización
- **prevention-metrics** (cmd): Métricas de prevención: bugs prevenidos vs encontrados, shift-left effectiveness, early detection rate. Paradigma QA de prevención sobre detección.
- **promotion-engine** (cmd): Gestiona promociones: crear, activar, desactivar, evaluar, reportes
- **reconciliation-stats** (script): reconciliation-stats.sh — Append/report reconciliation classification metrics
- **report-capacity** (cmd): Muestra el estado de capacidades del equipo — disponibilidad, asignación y alertas de sobre-carga.
- **report-executive** (cmd): Genera el informe ejecutivo multi-proyecto para dirección en formato Word o PowerPoint.
- **report-hours** (cmd): Genera el informe de imputación de horas del sprint actual o especificado.
- **report-verify** (cmd): Convene the Truth Tribunal (7 judges) to evaluate a report's reliability
- **risk-assess** (cmd): Calculate and display risk score for a task with breakdown and review recommendations
- **risk-log** (cmd): >
- **risk-policy** (cmd): Display and manage risk scoring thresholds and policies
- **risk-predict** (cmd): Predicción de riesgo del sprint basada en datos históricos y señales tempranas
- **risk-scoring** (skill): Usar cuando se calcula el riesgo de una tarea para decidir el nivel de revisión requerido.
- **rules-traceability** (skill): Usar cuando se mapean reglas de negocio a PBIs para trazabilidad completa.
- **sheets-report** (cmd): Generate report and sync to Google Sheets
- **solvency-report** (cmd): >
- **source-traceability-judge** (agent): Truth Tribunal judge — every claim must have a verifiable @ref citation
- **stakeholder-report** (cmd): Informe para stakeholders — progreso por epics, roadmap visual, riesgos
- **stakeholder-view** (cmd): Generate stakeholder-focused reporting view
- **time-tracking-report** (skill): Usar cuando se generan informes de imputación de horas en Excel o Word.
- **trace-pattern-extractor** (script): trace-pattern-extractor.sh — SPEC-044 Phase 1: analyze agent traces
- **truth-tribunal** (script): truth-tribunal.sh — Orchestrate 7-judge reliability evaluation of reports.
- **weekly-report** (skill): Usar cuando se genera el informe semanal de estado del proyecto.
