# development — Savia Capability Map (L1)
> 196 resources

- **/a11y-monitor** (cmd): Monitorización continua de regresiones de accesibilidad. Integración en CI/CD. Alertas cuando score baja por debajo de threshold. Digest semanal. Previene regresiones bloqueando deploys con fallos a11y.
- **/speckit.checklist** (cmd): Alias spec-kit compatible. Gate de calidad final con verification-lattice multi-capa. Invoca skill verification-lattice. Compatible con github/spec-kit.
- **/speckit.clarify** (cmd): Alias spec-kit compatible. Preguntas dirigidas para cerrar ambigüedad en una spec. Invoca skill context-interview-conductor. Compatible con github/spec-kit.
- **/speckit.constitution** (cmd): Alias spec-kit compatible. Declara los principios inmutables de un proyecto (constitution). Invoca skill savia-identity con args para constituir un proyecto. Compatible con github/spec-kit (>100k stars).
- **/speckit.implement** (cmd): Alias spec-kit compatible. Implementación supervisada de una spec aprobada. Invoca dev-orchestrator. Compatible con github/spec-kit.
- **/speckit.plan** (cmd): Alias spec-kit compatible. Diseño técnico de una spec ya capturada. Invoca skill spec-driven-development sección Plan. Compatible con github/spec-kit.
- **/speckit.specify** (cmd): Alias spec-kit compatible. Captura el what inicial de una spec (JTBD + PRD). Invoca skill product-discovery de Savia. Compatible con github/spec-kit.
- **/speckit.tasks** (cmd): Alias spec-kit compatible. Descomposición de spec en tasks accionables. Invoca skill pbi-decomposition. Compatible con github/spec-kit.
- **Trace Analyze** (cmd): Análisis profundo de trazas específicas con detección de cuellos de botella y cadenas de errores
- **UA Analyze** (cmd): Analyze codebase with Understand-Anything to generate knowledge graph
- **UA Diff** (cmd): Analyze impact of uncommitted changes on the codebase knowledge graph
- **UA Domain** (cmd): Extract business domain concepts and processes from any codebase
- **agents-opencode-convert** (script): agents-opencode-convert.sh — SPEC-127 Slice 2b-ii (final migration prep)
- **arch-compare** (cmd): Comparar dos patrones de arquitectura para toma de decisiones
- **arch-detect** (cmd): Detectar el patrón de arquitectura de un repositorio o proyecto
- **arch-fitness** (cmd): Ejecutar fitness functions de arquitectura para verificar integridad
- **arch-health** (cmd): Salud arquitectónica — fitness functions, drift detection, coupling metrics
- **arch-recommend** (cmd): Recomendar la mejor arquitectura para un proyecto nuevo
- **arch-suggest** (cmd): Sugerir mejoras de arquitectura basadas en detección previa
- **ast-quality-gate** (script): ast-quality-gate.sh — Language-agnostic code quality meta-analyzer
- **best-practices-check** (cmd): Evaluate workspace against Claude Code best practices
- **block-pat-file-write** (script): block-pat-file-write.sh — SPEC-SE-036 Slice 2: block writes to PAT file paths
- **budget-guard** (script): budget-guard.sh — Context budget monitor (SPEC-022 F1)
- **build-azdo-schema-graph** (script): build-azdo-schema-graph.sh — SE-076 Slice 2
- **build-skill-manifest** (script): build-skill-manifest.sh — Genera manifesto de skills desde frontmatter
- **calendar-focus** (cmd): Crear bloque de focus para una tarea especifica — Deep Work protegido
- **caveman** (skill): Strips all sugar-coating and marketing. Gives the brutally honest truth in the fewest possible words. Use when you suspect self-deception, before committing, or before shipping.
- **check-coherence** (cmd): Validate that a spec, report, or code output actually matches its stated objective
- **code-comprehension-report** (skill): Usar cuando se ha completado una implementación SDD y se necesita documentar el modelo mental.
- **code-improve** (cmd): Launch autonomous code improvement loop — detects opportunities, applies improvements, creates PRs for review
- **code-improvement-loop** (skill): Usar cuando se quiere ejecutar mejora autónoma de código en segundo plano con PRs para revisión.
- **code-patterns** (cmd): Catálogo de patterns del proyecto con ejemplos del propio código del equipo
- **code-reviewer** (agent): >
- **code-twin-agent** (agent): >
- **code-twin-anonymize** (script): code-twin-anonymize.sh — SPEC-190 Slice 8 (AC-14)
- **code-twin-extract** (script): code-twin-extract.sh — SPEC-190 Slice 7
- **code-twin-init** (script): code-twin-init.sh — Scaffold estructura vacía de ACT para un proyecto
- **code-twin-lint** (script): code-twin-lint.sh — Valida Code Twin Files (CTF), CTI (index.md) y seeds JSONL
- **code-twin-load** (script): code-twin-load.sh — SPEC-190 Slice 8 (AC-10)
- **code-twin-simulate** (script): code-twin-simulate.sh — SPEC-190 Slice 5
- **code-twin-sync-check** (script): code-twin-sync-check.sh — SPEC-190 Slice 8 (AC-12)
- **code-twin-validate-spec** (script): code-twin-validate-spec.sh — SPEC-190 Slice 6
- **codebase-map** (cmd): Generar mapa de dependencias internas del workspace: comandos → agentes → reglas → skills
- **codebase-map** (skill): Usar cuando se necesita un mapa de dependencias del workspace (comandos→agentes→reglas→skills).
- **codegraph** (skill): Usar cuando se necesita indexación AST persistente para navegación de callers/callees en el código.
- **cognitive-debt** (script): cognitive-debt.sh — SPEC-107 Phase 1 entry point.
- **cognitive-status** (cmd): Show cognitive-debt telemetry status (SPEC-107 Phase 1 — opt-in)
- **competitive-design** (script): competitive-design.sh — Parallel design generation with 3 philosophies
- **component-search** (cmd): Buscar componentes en el marketplace claude-code-templates (5.788+ componentes)
- **comprehension-report** (cmd): Generate mental model report for an implemented task. Documents architectural decisions, failure heuristics, and 3AM debugging guide.
- **concession-judge** (agent): Recommendation Tribunal judge — detects position changes without new evidence (SPEC-192)
- **dag-execute** (cmd): Ejecutar pipeline SDD con agentes en paralelo según DAG
- **dag-plan** (cmd): Visualizar DAG de ejecución, camino crítico y ahorro de tiempo
- **dag-scheduling** (skill): Usar cuando se orquestan múltiples agentes SDD con dependencias entre ellos.
- **dag-typing-validate** (script): dag-typing-validate.sh — SE-034 Slice 1 prototype validator.
- **decide-architecture** (script): decide-architecture.sh — SPEC-158
- **deps-validate** (script): deps-validate.sh — SPEC-SE-020 Slice 1 schema validator for deps.yaml.
- **design-an-interface** (skill): Skill para disenar una interfaz con N=3 alternativas en paralelo y recomendar la mejor segun vocabulario arquitectonico del proyecto.
- **dev-orchestrator** (agent): Analiza specs y crea planes de implementación con slices, dependencias y presupuestos de contexto
- **dev-session** (cmd): Orquestar desarrollo de un spec mediante 5 fases con aislamiento de contexto y persistencia en disco
- **dev-session-discard** (script): dev-session-discard.sh — Discard a dev-session cleanly
- **dev-session-resume** (cmd): Reanudar una dev-session interrumpida desde el ultimo checkpoint
- **enterprise/api-key-create** (script): api-key-create.sh — SPEC-SE-036 Slice 2: API key creation CLI.
- **enterprise/api-key-list** (script): api-key-list.sh — SPEC-SE-036 Slice 2: API key inventory CLI.
- **enterprise/api-key-revoke** (script): api-key-revoke.sh — SPEC-SE-036 Slice 2: API key revocation CLI.
- **enterprise/delta-tier** (script): delta-tier.sh — SPEC-SE-035 helper
- **enterprise/jwt-mint** (script): jwt-mint.sh — SPEC-SE-036 Slice 1: short-lived JWT mint primitive.
- **enterprise/reconciliation-status** (script): reconciliation-status.sh — SPEC-SE-035 Slice 1+3: tenant reconciliation CLI.
- **epistemic-humility** (skill): Usar cuando se detecta riesgo de adulación, cesión sin evidencia, o claim repetido por el usuario asumido sin verificar. Trigger: tribunal SPEC-192 emite WARN/VETO o auto-detección léxica.
- **eval-agent** (cmd): Evaluate an agent against its golden set — precision, recall, hallucinations, bias (SPEC-036)
- **eval-agent** (script): eval-agent.sh — Agent Evaluation Runner (SPEC-036)
- **eval-run** (cmd): Execute evaluation against specified criteria
- **execution-supervisor** (script): execution-supervisor.sh — Advisory reflection trigger (SPEC-065)
- **failure-pattern-memory** (script): failure-pattern-memory.sh — SPEC-188 Fase 1: Failure Pattern Memory store
- **feasibility-probe** (cmd): Validate spec feasibility with a time-boxed prototype attempt
- **feasibility-probe** (skill): Usar cuando se necesita validar si una spec es técnicamente viable antes de implementarla.
- **feasibility-probe** (agent): Validates spec feasibility by attempting a time-boxed prototype. Produces viability report with score, blocking sections, and decomposition suggestions.
- **gaia-benchmark-harness** (script): gaia-benchmark-harness.sh — SPEC-100 Slice 1 GAIA benchmark harness.
- **gitagent-export** (script): gitagent-export.sh — SPEC-099 Slice 1 gitagent adapter.
- **graph-build** (cmd): Construye el grafo de conocimiento PM para un proyecto
- **graph-temporal-ops** (script): graph-temporal-ops.sh — SPEC-123
- **hook-portability-classifier** (script): hook-portability-classifier.sh — SPEC-127 Slice 2
- **human-code-map** (skill): Usar cuando se incorpora un dev nuevo, se toca un módulo sin mapa, o alguien re-lee el mismo código repetidamente.
- **image-relevance-filter** (script): image-relevance-filter.sh — SPEC-103 Slice 1: deterministic-first image triage primitive.
- **impact-analysis** (script): impact-analysis.sh — Analyze codebase impact of modifying files
- **index-rebuild** (cmd): >
- **install-git-hooks** (script): install-git-hooks.sh — Instala hooks de Git para PM‑Workspace en OpenCode
- **instinct-collapse-detector** (script): instinct-collapse-detector.sh — SPEC-045 Phase 1: detect exploration collapse
- **jwt-mint** (script): jwt-mint.sh — SPEC-SE-036: API key → JWT ephemeral mint
- **kg-export** (script): kg-export.sh — SE-218 S2: KG snapshot versionado (codebase-memory-mcp pattern)
- **llm-training/import-gguf** (script): import-gguf.sh — SPEC-080: Import fine-tuned GGUF model into Ollama
- **llm-training/prepare-training-data** (script): prepare-training-data.sh — SPEC-080: Extract training data from agent traces
- **localai-readiness-check** (script): localai-readiness-check.sh — SPEC-122
- **marketplace-install** (cmd): Install components from claude-code-templates marketplace
- **mcp-browse** (cmd): Explorar catálogo de MCPs disponibles (66+) via claude-code-templates
- **mcp-server** (cmd): Expone las herramientas de Savia como MCP server para otros proyectos Claude Code
- **nd-autoconfig** (script): nd-autoconfig.sh — SPEC-061: Auto-configure accessibility.md from neurodivergent.md
- **nidos-dev-lib** (script): nidos-dev-lib.sh — Dev server lifecycle for Savia nidos (SPEC-098).
- **opencode-hooks/run-hook** (script): run-hook.sh — Ejecuta un hook de PM‑Workspace con el input JSON adecuado
- **opencode-install** (script): opencode-install.sh — SE-077 Slice 1
- **opencode-migration-smoke** (script): opencode-migration-smoke.sh — SPEC-127 Slice 2b-ii (final migration prep)
- **opencode-monthly-canary** (script): opencode-monthly-canary.sh — SE-077 Slice 2
- **parallel-specs-cleanup-stale** (script): parallel-specs-cleanup-stale.sh — SE-074 Slice 3 — stale worktree cleanup
- **parallel-specs-db-sandbox** (script): parallel-specs-db-sandbox.sh — SE-074 Slice 3 — DB sandbox per worker
- **parallel-specs-merge-queue** (script): parallel-specs-merge-queue.sh — SE-074 Slice 2 — PR queue + cascade-rebase
- **parallel-specs-orchestrator** (script): parallel-specs-orchestrator.sh — SE-074 Slice 1 — orchestrates parallel spec execution
- **pdf-extract-probe** (script): pdf-extract-probe.sh — SPEC-102 Slice 1 feasibility probe.
- **pipeline-artifacts** (cmd): >
- **pipeline-create** (cmd): >
- **pipeline-engine** (script): pipeline-engine.sh — Orchestrate pipeline execution from YAML definition
- **pipeline-local-run** (cmd): Run a local pipeline defined as YAML — no Jenkins/Azure Pipelines needed
- **pipeline-logs** (cmd): >
- **pipeline-run** (cmd): >
- **pipeline-stage-runner** (script): pipeline-stage-runner.sh — Execute a single pipeline stage
- **pipeline-status** (cmd): >
- **pipeline-view** (cmd): ASCII table of all active pursuits with stage, value, and probability
- **portfolio-contention** (script): portfolio-contention.sh — SPEC-SE-020 Slice 4 contention detector.
- **portfolio-critical-path** (script): portfolio-critical-path.sh — SPEC-SE-020 Slice 3 critical path analyzer.
- **portfolio-deps-status** (script): portfolio-deps-status.sh — SPEC-SE-020 Slice 5 project status dashboard.
- **portfolio-graph** (script): portfolio-graph.sh — SPEC-SE-020 Slice 2 dependency graph builder.
- **pre-push-bats-critical** (script): pre-push-bats-critical.sh — SPEC-SE-012 Module 3.
- **prompt-suggestion-engine** (script): prompt-suggestion-engine.sh — SPEC-044 Phase 2: trace-driven prompt optimization
- **reaction-engine** (script): reaction-engine.sh — SPEC-050 Phase 1: Reaction Engine
- **rebuild-folder-indexes** (script): rebuild-folder-indexes.sh
- **recommendation-tribunal/aggregate** (script): aggregate.sh — SPEC-125 Slice 1: deterministic aggregation of 4 judge verdicts.
- **recommendation-tribunal/banner** (script): banner.sh — SPEC-125 Slice 1: render the tribunal verdict banner.
- **recommendation-tribunal/calibrate** (script): calibrate.sh — SPEC-125 Slice 3: derive feedback memories from followups.
- **recommendation-tribunal/classifier** (script): classifier.sh — SPEC-125 Slice 1: detect actionable recommendations in Savia's draft.
- **recommendation-tribunal/early-cancel** (script): early-cancel.sh — SPEC-196: Freeze-done elements en Recommendation Tribunal.
- **recommendation-tribunal/expertise-rewrite** (script): expertise-rewrite.sh — SPEC-125 Slice 2: Asymmetric-expertise rewrite.
- **recommendation-tribunal/followup-record** (script): followup-record.sh — SPEC-125 Slice 3: Memory feedback loop.
- **recommendation-tribunal/iterate** (script): iterate.sh — SPEC-195: Iterative tribunal loop controller.
- **reconciliation-pilot** (script): reconciliation-pilot.sh — SPEC-183 Slice 4: run reconciler pilot on pm-workspace docs
- **repetition-truth-judge** (agent): Recommendation Tribunal judge — detects user claims repeated and assumed true without verification (SPEC-192)
- **requirement-pushback** (script): requirement-pushback.sh — Analyze a spec and generate pushback questions
- **retro-patterns** (cmd): Análisis de patrones en retrospectivas — temas recurrentes, action items sin resolver
- **rpi-status** (cmd): Track progress of active RPI (Research → Plan → Implement) workflows.
- **rules-domain-index** (script): rules-domain-index.sh — SPEC-115
- **sdd-spec-writer** (agent): >
- **semantic-compact** (script): semantic-compact.sh — SPEC-022 F2: Smart compact summary generator
- **semantic-map** (script): semantic-map.sh — Generate compressed semantic maps of source code files
- **sentinel-regen** (script): Ref: SPEC-180 / docs/rules/domain/sentinel-safe-regen.md
- **setup-claude-permissions** (script): DEPRECATED: use setup-opencode-permissions.sh instead. This file kept for backward compatibility.
- **setup-opencode-permissions** (script): setup-claude-permissions.sh — Genera settings.local.json con permisos recomendados
- **setup-savia-web** (script): Setup, build, and serve savia-web on http://localhost:8081
- **skill-loader** (script): skill-loader.sh — SPEC-144: Context-Aware Skill Loading
- **slm-deploy** (script): slm-deploy.sh — Orchestrate post-training deployment scaffolding.
- **slm-registry** (script): slm-registry.sh — Model registry for trained SLMs (SPEC-SE-027 registry).
- **smart-routing** (skill): Usar cuando se necesita descubrir o enrutar a un comando específico entre los 400+ disponibles.
- **sovereignty-pack** (script): sovereignty-pack.sh — Build fully offline Savia USB installer
- **spec-156-migrate-token-budget** (script): SPEC-156 — Add token_budget frontmatter to all agents.
- **spec-approval-gate** (script): spec-approval-gate.sh — SE-051 Slice 1 Rule #8 enforcement gate.
- **spec-budget** (script): spec-budget.sh — SE-074 Slice 1.5 — dynamic retry budget per spec effort
- **spec-design** (cmd): Genera diseño técnico a partir de una spec existente — decisiones, flujo de datos, estrategia de testing.
- **spec-driven-development** (skill): Usar cuando se escribe, valida o implementa una spec ejecutable SDD.
- **spec-explore** (cmd): Explore and analyze specification documents
- **spec-frontmatter-migrate** (script): spec-frontmatter-migrate.sh — SE-036 Slice 1.
- **spec-generate** (cmd): Genera una Spec ejecutable a partir de una Task de Azure DevOps, lista para implementación.
- **spec-id-duplicates-check** (script): spec-id-duplicates-check.sh — SE-044 Slice 1 spec ID uniqueness gate.
- **spec-implement** (cmd): Implementa una Spec según su developer_type — lanza agente o asigna a humano.
- **spec-judge** (agent): Code Review Court judge — implementation vs approved spec, acceptance criteria
- **spec-opencode-plan-audit** (script): Audit: every APPROVED/IMPLEMENTED spec post-2026-04-26 must include
- **spec-quality-auditor** (script): spec-quality-auditor.sh — Deterministic quality scorer for SDD specs
- **spec-review** (cmd): Review specification for completeness and coherence
- **spec-slice** (cmd): Analizar un spec y dividirlo en slices de implementación optimizados para contexto
- **spec-status** (cmd): Check specification status and approval state
- **spec-status-drift-audit** (script): spec-status-drift-audit.sh — Detect specs marked PROPOSED but implemented on disk.
- **spec-status-normalize** (script): spec-status-normalize.sh — audit and normalize `status:` field across all
- **spec-verify** (cmd): Verify implementation against specification criteria
- **spec-verify-ui** (cmd): Verificación spec↔UI — comprueba que el componente implementado cumple su spec SDD
- **spec156-migrate-token-budget** (script): SPEC-156 Slice 2 prep — migrate flat token_budget to nested object.
- **specs-frontmatter-normalize** (script): specs-frontmatter-normalize.sh — SE-054 Slice 2+3 frontmatter normalization.
- **statusline-provider** (script): statusline-provider.sh — HUD data provider for Claude Code statusline
- **sycophancy-judge** (agent): Recommendation Tribunal judge — detects empty social validation in conversational drafts (SPEC-192)
- **tech-research** (cmd): Launch autonomous technical research — investigates topics, generates reports, notifies designated human
- **tech-research-agent** (skill): Usar cuando se necesita investigación técnica autónoma sobre un tema específico.
- **timeline-append** (script): timeline-append.sh — Append a bi-temporal timeline entry to a spec/decision file
- **timeline-status-guard** (script): timeline-status-guard.sh — SPEC-182 Slice 4: suggest timeline-append when status changes
- **tolaria-open** (cmd): Open Tolaria desktop knowledge base on the Savia workspace (or specified path)
- **tribunal-async-runner** (script): tribunal-async-runner.sh — SPEC-159: Async Tribunal Fan-out
- **tribunal-benchmark** (script): tribunal-benchmark.sh — SPEC-106 Phase 3.
- **twin-anonymize** (script): twin-anonymize.sh — Genera vista N1 de un twin sin datos de organización (SPEC-169 AC-6)
- **twin-load** (script): twin-load.sh — Carga y muestra el twin de un proyecto (SPEC-169 AC-2, AC-5)
- **twin-refresh** (script): twin-refresh.sh — Recalcula predicciones del twin sin LLM (SPEC-169 AC-3, AC-V2)
- **ua-onboard** (cmd): Generate a guided onboarding tour for any codebase
- **understand-anything** (skill): Usar cuando se necesita analizar un codebase con Understand-Anything para generar knowledge graphs estructurales y de dominio.
- **validate-consensus** (cmd): Lanzar panel de 3 jueces para validar specs, PRs y decisiones
- **validate-pbi-spec-links** (script): validate-pbi-spec-links.sh — Check bidirectional PBI ↔ Spec links
- **validate-spec** (script): validate-spec.sh — SPEC-071: Declarative spec validation without LLM
- **verification-middleware** (script): verification-middleware.sh — Orchestrate 3 verification checks post-implementation
- **verify-layer** (cmd): Run specific verification layer for debugging
- **wireframe-check** (cmd): Validate implementation against wireframe/mockup designs. Register reference designs and verify implementation fidelity against specifications.
- **workload-balance** (cmd): Equilibrado objetivo de carga de trabajo respetando especialidades del equipo
- **workspace-doctor** (script): workspace-doctor.sh — Health check pm-workspace (SPEC-031)
- **worktree-setup** (cmd): >
- **zoom-out** (skill): Elevates perspective from trees to forest. Maps architecture, dependencies, and second-order effects before implementation decisions. Use when designing, when evaluating trade-offs, or at the start of design sessions.
