# memory — Savia Capability Map (L1)
> 94 resources

- **auto-compact** (script): auto-compact.sh — Disparado automáticamente cuando contexto > 85%
- **cache-analytics** (cmd): Métricas de hit rate, tokens ahorrados, latencia, ahorro de costes
- **changelog-consolidate** (script): changelog-consolidate.sh — consolidate CHANGELOG.d/*.md fragments into
- **changelog-consolidate-if-needed** (script): changelog-consolidate-if-needed.sh — SE-053 Slice 1 post-merge automation.
- **company-show** (cmd): Mostrar perfil consolidado de la empresa — resumen ejecutivo del contexto organizacional
- **configurator** (agent): Centralizes workspace dispatch decisions: selects skills, agents, rules, and memory queries for each user intent. Emits structured JSON decisions for orchestrators to consume.
- **content-fingerprint** (script): content-fingerprint.sh — SE-151 consolidation skill
- **context-aging** (script): ── context-aging.sh ───────────────────────────────────────────────────────
- **context-budget** (cmd): Presupuesto de contexto por sesión — tokens usados/disponibles, distribución por capa, sugerencias de optimización
- **context-budget-check** (script): ── context-budget-check.sh ──────────────────────────────────────────────────
- **context-caching** (skill): Usar cuando se optimiza el orden de carga de contexto para maximizar cache hits.
- **context-calibration-measure** (script): context-calibration-measure.sh — Measure context usage patterns
- **context-capability-check** (script): context-capability-check.sh — SE-221 Slice 3 — Capability metadata validator
- **context-condenser** (script): context-condenser.sh — SE-200: rolling window context compression
- **context-distortion-measure** (script): context-distortion-measure.sh — SE-029-M
- **context-dome** (skill): >
- **context-dome-generate** (script): context-dome-generate.sh -- Genera CONTEXT_DOME.md por modulo con BF bajo.
- **context-drop-after-use** (script): context-drop-after-use.sh — SE-221 Slice 2 — Drop-After-Use decision engine
- **context-drop-metrics** (script): context-drop-metrics.sh — SE-221 Slice 2 — Drop-After-Use metrics
- **context-engineering-report** (script): context-engineering-report.sh — SE-221 Slice 4 — Weekly report generator
- **context-frozen-check** (script): context-frozen-check.sh — SE-029-F
- **context-greedy-budget** (script): context-greedy-budget.sh — SPEC-189: Greedy context budget selection.
- **context-interview** (cmd): Entrevista estructurada de contexto para proyectos y clientes
- **context-interview-conductor** (skill): Usar cuando se necesita recopilar contexto estructurado de un usuario mediante entrevista guiada.
- **context-meter** (script): context-meter.sh — SE-219 S2: context window % as first-class metric (abtop pattern)
- **context-optimized-dev** (skill): Usar cuando se desarrolla con presupuesto de contexto limitado.
- **context-origin-tag** (script): context-origin-tag.sh — SE-221 Slice 1 — Context Origin Tagging
- **context-preflight-check** (script): ─────────────────────────────────────────────────────────────────────────────
- **context-receipts-validate** (script): context-receipts-validate.sh — SE-030
- **context-restate-anchor** (script): context-restate-anchor.sh — SE-029-R
- **context-rot-strategy** (skill): Usar cuando una sesión larga se aproxima al límite de contexto y hay que decidir qué compactar.
- **context-rotation** (script): context-rotation.sh — SE-033: Automated context rotation (daily/weekly/monthly)
- **context-snapshot** (script): context-snapshot.sh — Save/load session context between sessions
- **context-status** (cmd): Show context window usage, model tier, and optimization recommendations
- **context-task-classifier** (skill): Usar antes de compactar contexto para clasificar la tarea del turno actual.
- **context-task-classifier** (script): context-task-classifier.sh — SE-029-C
- **context-task-classify** (script): context-task-classify.sh — SE-029 Slice 2 task-class classifier.
- **context-tracker** (script): ── context-tracker.sh ─────────────────────────────────────────────────────
- **digest-to-memory** (script): digest-to-memory.sh — Bridge: digest agents -> memory-store + graph
- **entity-recall** (cmd): >
- **focal-switch** (script): focal-switch.sh — Off-load de contexto antes de cambiar de nido (SE-230 Slice 1)
- **generate-blocklist** (script): generate-blocklist.sh — Dynamic blocklist from workspace context
- **generate-context-index** (script): generate-context-index.sh — Generate context index files for workspace and projects
- **generate-global-context** (script): Generate compact global context for agent injection.
- **iterative-compress** (script): iterative-compress.sh — Iterative context compression with summary preservation
- **lesson-search** (cmd): Search cross-project lessons by keyword or domain
- **memory-access** (script): memory-access.sh — SE-073 Slice 1 — increment access_count + last_access
- **memory-agent** (agent): Gestiona la memoria persistente de pm-workspace via lenguaje natural.
- **memory-backup-pm** (script): memory-backup-pm.sh — Backup memory indices to PM repo (N4b, max privacy)
- **memory-cache-rebuild** (script): memory-cache-rebuild.sh — Rebuild SQLite cache from .md memory files
- **memory-canary-check** (script): memory-canary-check.sh — SE-073 Output Filtering + Canary Tokens
- **memory-check** (cmd): >
- **memory-check** (script): memory-check.sh — Health check of all Savia memory layers
- **memory-conflict-check** (script): memory-conflict-check.sh — SE-214: detect conflicting memory entries
- **memory-conflict-judge** (agent): Recommendation Tribunal judge — detects when a draft recommendation contradicts the active user's auto-memory (feedback_*, user_*)
- **memory-consolidate** (cmd): Consolidate and compress memory entries to save context
- **memory-context** (cmd): >
- **memory-feedback-post-merge** (script): memory-feedback-post-merge.sh — Writes a memory entry when a PR is merged.
- **memory-hygiene** (script): memory-hygiene.sh — SPEC-142: Limpieza automática de auto-memory
- **memory-index-rebuild** (script): memory-index-rebuild.sh — rebuild auto/MEMORY.md index from JSONL store
- **memory-liveness-check** (script): scripts/memory-liveness-check.sh — SE-257 Slice 2
- **memory-recall** (cmd): Retrieve relevant memories for current context
- **memory-recall-audit** (script): memory-recall-audit.sh — SE-212: measure MEMORY.md recall budget utilization
- **memory-rotate** (cmd): Execute context rotation manually — daily, weekly, monthly cycles
- **memory-save** (script): memory-save.sh — Save, upsert, entity, session-summary (sourced by memory-store.sh)
- **memory-search** (script): memory-search.sh — Search, context, stats (sourced by memory-store.sh)
- **memory-stack-load** (script): memory-stack-load.sh — Token-budgeted progressive memory loading
- **memory-status-check** (script): memory-status-check.sh — Tabla de estado de todas las capas de memoria de Savia
- **memory-store** (script): memory-store.sh — JSONL persistent memory store for pm-workspace
- **memory-sync-index** (script): memory-sync-index.sh — Sync auto-memory markdown → JSONL vector index
- **memory-tier-rotate** (script): memory-tier-rotate.sh — SE-073 Slice 1 — 2-tier rotation for auto-memory
- **memory-verify** (script): memory-verify.sh — Quality gate for memory compression (SPEC-041 P3)
- **memvid-probe** (script): memvid-probe.sh — SE-041 Slice 1 memvid portable memory viability probe.
- **my-focus** (cmd): Modo focus — identifica el item más prioritario y carga todo su contexto
- **nl-query** (cmd): Consultas en lenguaje natural — habla con Savia sin memorizar comandos
- **post-compaction** (script): post-compaction.sh - Hook que inyecta contexto de memoria tras compactación
- **recursion-guard-export** (script): scripts/recursion-guard-export.sh — Sets SAVIA_LOOP_CONTEXT for recursion prevention
- **save-nudge** (script): scripts/save-nudge.sh — SE-256 Slice 1
- **session-action-log** (script): session-action-log.sh — Append-only session action log (SPEC-065)
- **session-cleanup** (script): session-cleanup.sh — SE-219 S3: orphan process cleanup (abtop pattern)
- **session-event-log** (script): session-event-log.sh — Managed Agents pattern: durable session log
- **session-init-bootstrap** (script): session-init-bootstrap.sh — SE-045 Slice 1 async bootstrap.
- **session-registry** (script): session-registry.sh — Session coordination registry (SE-229 Slice 1)
- **session-resume-index** (script): session-resume-index.sh — Multica pattern: session resumption metadata
- **session-state-machine** (script): session-state-machine.sh — SPEC-051 Phase 1: Session State Machine
- **session-status** (script): session-status.sh — SE-219 S1: consultable session snapshot (abtop pattern)
- **setup-memory** (script): setup-memory.sh — Inicializa estructura de auto memory para un proyecto
- **skill-optimize** (cmd): Auto-optimizar el prompt de un skill o agente con bucle AutoResearch
- **slice-context-chain** (script): slice-context-chain.sh — Knowledge chain between dev-session slices
- **tool-search** (cmd): Buscar comandos, skills y agentes por palabra clave
- **ua-chat** (cmd): Semantic search the knowledge graph using natural language
- **ubiquitous-language** (skill): Usar cuando se necesita extraer o consolidar el glosario de términos de dominio de un proyecto. Trigger: usuario dice 'extrae glosario', 'ubiquitous language', '/glossary', o hay >5 términos repetidos sin CONTEXT.md.
- **web-research** (cmd): Search the web to resolve context gaps — documentation, versions, CVEs, best practices. Auto-starts SearxNG Docker if available, falls back to WebSearch.
- **web-research** (skill): Usar cuando se necesita buscar en la web para resolver gaps de contexto (docs, versiones, CVEs).
