# planning — Savia Capability Map (L1)
> 555 resources

- **/accreditation-track** (cmd): >
- **/decide-architecture** (cmd): Clasifica una tarea como WORKFLOW (deterministica) o AGENT (loop). Bias hacia workflow per Anthropic. Sugiere plantilla inicial. Mide accuracy contra corpus curado de 20 tareas.
- **/drive-setup** (cmd): Create Google Drive folder structure with role-based permissions
- **/drive-sync** (cmd): Bidirectional sync between local workspace and Google Drive
- **/health-kpi** (cmd): >
- **/incident-register** (cmd): >
- **/pdca-cycle** (cmd): >
- **Compartir Recurso Entre Tenants** (cmd): Comparte recursos (playbooks, templates, skills, reglas) entre tenants con flujo de aprobación controlado, versionado y prevención de deriva de configuración
- **Crear Tenant** (cmd): Crea un workspace aislado por departamento/equipo con perfiles de usuario, configuración de proyecto, herencia de perfiles empresariales y control de acceso basado en roles
- **Error Investigate** (cmd): Investigación asistida de errores en producción con root cause analysis y correlación de datos
- **Incident Correlate** (cmd): Correlación cruzada de datos de múltiples fuentes para análisis integral de incidentes
- **_template** (skill): TEMPLATE — copia este directorio para crear una skill nueva. NO se carga en runtime.
- **accessibility-mode** (cmd): Toggle rápido de accesibilidad — activa, desactiva o muestra el estado
- **accessibility-setup** (cmd): Configura las preferencias de accesibilidad de Savia para adaptarse a tus necesidades
- **adaptive-halting** (script): adaptive-halting.sh — SE-074 Slice 1.5 — double-criterion halting check
- **adaptive-strategy-selector** (script): adaptive-strategy-selector.sh — Select loading strategy based on model tier
- **adb-run** (script): adb-run.sh — Execute adb-wrapper functions without compound && chains
- **add-maturity-levels** (script): add-maturity-levels.sh — Add maturity field to all skill frontmatter
- **ado-bridge** (script): ado-bridge.sh — Azure DevOps REST API v7.1 bridge for Savia PM commands
- **adoption-assess** (cmd): Evaluar madurez de adopción de IA del equipo usando modelo ADKAR
- **adoption-plan** (cmd): Plan personalizado de adopción de Savia por rol — qué aprender, en qué orden
- **adoption-sandbox** (cmd): Entorno seguro de práctica — experimentar con Savia sin miedo a errores
- **adoption-track** (cmd): Tracking de adopción — comandos usados por rol, curva de aprendizaje, puntos de fricción
- **adr-create** (cmd): >
- **advisor-config** (script): advisor-config.sh — Generate Anthropic Advisor Strategy configuration
- **agents-catalog-sync** (script): agents-catalog-sync.sh — SE-047 Slice 1 agents catalog auto-sync.
- **agents-md-drift-check** (script): agents-md-drift-check.sh — SE-078
- **agents-md-generate** (script): agents-md-generate.sh — SE-078
- **ai-boundary** (cmd): Definir matriz de límites explícitos: qué puede hacer Savia autónomamente vs requiere aprobación
- **ai-confidence** (cmd): Transparencia: Savia muestra confianza, razonamiento, datos y limitaciones de cada recomendación
- **ai-incident** (cmd): Registrar y analizar incidentes donde recomendaciones de Savia fueron incorrectas
- **ai-labor-impact** (skill): Usar cuando se analiza el impacto de la IA en el trabajo del equipo o la organización.
- **ai-model-card** (cmd): Genera model card documentando agentes IA, modelos, tareas y decisiones
- **ai-safety-config** (cmd): Configurar 4 niveles de supervisión humana (inform/recommend/decide/execute) por tipo de acción
- **architect** (agent): >
- **architecture-intelligence** (skill): Usar cuando se diseña o revisa la arquitectura de un proyecto nuevo o existente.
- **ast-comprehend** (script): ast-comprehend.sh — Extractor estructural multi-lenguaje (ast-comprehension skill)
- **ast-comprehension** (skill): Usar cuando se explora código desconocido y se necesita comprensión estructural sin leer ficheros enteros.
- **ast-quality-gate** (skill): Usar cuando se verifica la calidad de código generado por IA antes de merge.
- **azdevops-queries** (script): =============================================================================
- **azure-devops-operator** (agent): >
- **azure-devops-queries** (skill): Usar cuando se necesitan consultas WIQL, actualización de work items o datos de sprint en Azure DevOps.
- **azure-pipelines** (skill): Usar cuando se gestiona o depura CI/CD con Azure Pipelines.
- **backlog-capture** (cmd): >
- **backlog-git** (cmd): Control de versiones para backlogs de proyectos
- **backlog-git-tracker** (skill): Usar cuando se capturan o comparan snapshots del backlog para detectar drift.
- **backlog-groom** (cmd): Grooming asistido — detectar items obsoletos, duplicados, sin criterios de aceptación
- **backlog-init** (script): backlog-init.sh — Initialize local backlog structure for a project
- **backlog-patterns** (cmd): Detecta PBIs duplicados o similares entre proyectos del portfolio
- **backlog-pbi-crud** (script): backlog-pbi-crud.sh — Create, read, update, archive PBIs in local backlog
- **backlog-prioritize** (cmd): Priorización automática RICE/WSJF con datos reales de esfuerzo y valor
- **backlog-query** (script): backlog-query.sh — Query local backlog PBIs by frontmatter fields
- **backlog-resolver** (script): backlog-resolver.sh — Resolve backlog data source (local-first, API fallback)
- **backlog-sync** (cmd): Sync local backlog with external PM tools (Azure DevOps, Jira, GitHub Issues)
- **backup** (cmd): Backup cifrado de perfiles, configuraciones y datos locales a NextCloud o Google Drive
- **backup** (script): backup.sh — Backup cifrado de datos locales a NextCloud/GDrive
- **banking-architecture** (skill): Usar cuando se diseña o revisa arquitectura para proyectos del sector bancario.
- **banking-bian** (cmd): Validar arquitectura contra estándar BIAN y generar diagramas ArchiMate
- **banking-detect** (cmd): Auto-detectar proyecto bancario por entidades BIAN, Kafka, Snowflake, SWIFT
- **banking-eda-validate** (cmd): Validar pipelines Kafka/EDA — topologías, schemas, DLQ, Saga, idempotencia
- **baseline-tighten** (script): baseline-tighten.sh — SE-046 Slice 1 baseline auto-tighten.
- **bertopic-probe** (script): bertopic-probe.sh — SE-033 Slice 1 BERTopic viability probe.
- **billing-rate** (cmd): >
- **board-flow** (cmd): Analiza el flujo de trabajo del board — WIP actual, cuellos de botella y métricas de flujo.
- **burnout-radar** (cmd): Detección temprana de señales de burnout con análisis de riesgo por miembro del equipo
- **business-analyst** (agent): >
- **calendar-deadlines** (cmd): Deadlines proximos con estado de preparacion — nada se queda atras
- **calendar-plan** (cmd): Planificar semana con focus blocks automaticos y priorizacion Eisenhower
- **calendar-rebalance** (cmd): Rebalancear focus blocks tras cambio de prioridades o calendario
- **calendar-sync** (cmd): Sincronizar calendario Outlook/Teams via Microsoft Graph API
- **calendar-today** (cmd): Vista del dia con alertas, reuniones, focus blocks y recomendaciones
- **calibration-judge** (agent): Truth Tribunal judge — confidence statements match evidence strength
- **capacity-forecast** (cmd): Previsión de capacidad a medio plazo — planifica recursos para los próximos 3-6 sprints
- **capacity-forecast-telco** (cmd): Medición, previsión y planificación de capacidad de red con alertas automáticas
- **capacity-planning** (skill): Usar cuando se calcula la capacidad del equipo para un sprint o periodo.
- **case-init** (cmd): Scaffold a business case from pursuit and SOW data
- **case-kill-check** (cmd): Run valuation sentinel across all active cases for kill recommendations
- **case-validate** (script): case-validate.sh — SE-016: Validate business case directories
- **ceo-alerts** (cmd): Panel de alertas estratégicas para dirección — solo decisiones que requieren nivel C
- **ceremony-health** (cmd): Métricas de salud de ceremonias — duración, participación, resolution rate
- **changelog-assemble** (script): changelog-assemble.sh — Assemble CHANGELOG.md from CHANGELOG.d/ fragments
- **changelog-fragment** (script): changelog-fragment.sh — create a CHANGELOG fragment for the current PR
- **changelog-update** (cmd): >
- **check-daemon-auth** (script): check-daemon-auth.sh
- **ci-failure-tracker** (script): ci-failure-tracker.sh — Track CI pipeline failures for signal/noise analysis
- **ci-health** (cmd): Muestra tasa de fallo de pipelines CI a partir del log local de ejecuciones.
- **claude-md-drift-check** (script): claude-md-drift-check.sh — Valida que los conteos en CLAUDE.md coincidan con
- **client-profile** (cmd): Gestión de perfiles de cliente en SaviaHub
- **client-profile-manager** (skill): Usar cuando se crean, actualizan o consultan perfiles de cliente en SaviaHub.
- **cobol-developer** (agent): >
- **coherence-judge** (agent): Truth Tribunal judge — internal consistency (sums, dates, entities)
- **coherence-validator** (agent): >
- **commit-guardian** (agent): >
- **company-edit** (cmd): Editar secciones del perfil de empresa — identity, structure, strategy, policies, technology, vertical
- **company-messaging** (skill): Usar cuando se envían mensajes internos cifrados entre miembros de la organización vía Company Savia.
- **company-repo** (cmd): >
- **company-repo** (script): company-repo.sh — Git operations for company repo lifecycle
- **company-repo-ops** (script): company-repo-ops.sh — Connect, status, and sync operations
- **company-repo-templates** (script): company-repo-templates.sh — Heredoc templates for company repo init
- **company-repo-templates-init** (script): company-repo-templates-init.sh — Heredoc templates for repo initialization
- **company-setup** (cmd): Onboarding conversacional de empresa — genera el perfil organizacional completo
- **company-vertical** (cmd): Detectar y configurar la vertical de la empresa — regulaciones, frameworks y mejores prácticas del sector
- **competence-score** (script): competence-score.sh — Calculate competence scores from tracking log
- **compile-agent-index** (script): compile-agent-index.sh — Compiled agent reference index for LLM routing
- **compress-skip-frozen** (script): compress-skip-frozen.sh — SE-029 Slice 3 frozen-core advisory.
- **confidence-calibrate** (script): confidence-calibrate.sh - Confidence Calibration Analytics
- **confidentiality-check** (script): confidentiality-check.sh — Verify project files comply with confidentiality levels
- **confidentiality-scan** (script): confidentiality-scan.sh — Scan for PII, credentials, real project names.
- **conflict-check** (cmd): >
- **confluence-publish** (cmd): >
- **consensus-validation** (skill): Usar cuando una decisión técnica o recomendación necesita validación por panel de jueces.
- **content-fingerprint** (skill): Usar cuando se necesita un identificador corto, deterministico y reproducible derivado del contenido de una cadena o fichero — cache keys, ids de patrones, fingerprints de docs.
- **contribute** (cmd): Contribuir mejoras, ideas o correcciones al repositorio de pm-workspace en GitHub
- **contribute** (script): contribute.sh — Capa de interacción con GitHub para comunidad
- **cost-center** (cmd): Cost management and billing — timesheets, budgets, forecasting, invoicing
- **cost-management** (skill): Usar cuando se gestionan timesheets, presupuestos, facturas o forecasting de costes.
- **count-commands** (script): count-commands.sh — SE-095: canonical counter for slash commands.
- **court-calendar** (cmd): >
- **credential-proxy** (script): credential-proxy.sh — Managed Agents pattern: credential isolation
- **credential-scan** (cmd): >
- **criticality** (script): criticality.sh — Dispatcher for criticality operations
- **criticality-assess** (cmd): Evaluar criticidad de un item con desglose de 5 dimensiones y perfil CoD
- **criticality-dashboard** (cmd): Vista cross-project de items criticos P0-P3 con heatmap por equipo
- **criticality-engine** (script): criticality-engine.sh — Operations: assess, dashboard, rebalance. Sourced by criticality.sh.
- **criticality-rebalance** (cmd): Redistribuir carga de trabajo del equipo respetando criticidad y capacidad
- **criticality-scoring** (script): criticality-scoring.sh — Pure scoring functions. Sourced by criticality-engine.sh.
- **daily-activation-plan** (script): daily-activation-plan.sh — SE-034: Daily Agent Activation Plan
- **daily-plan** (cmd): Generate or show today's agent activation plan with token budgets
- **daily-routine** (cmd): Rutina diaria adaptativa según el rol del usuario — Savia sugiere los comandos más relevantes para tu jornada
- **dataset-version** (cmd): >
- **deep-work** (cmd): Planificador de bloques de trabajo profundo basado en calendario y carga. Framework de Cal Newport aplicado a equipos de desarrollo.
- **dependency-map** (cmd): >
- **developer-experience** (skill): Usar cuando se mide o mejora la experiencia de desarrollo del equipo.
- **devops-validate** (cmd): >
- **devops-validation** (skill): Usar cuando se conecta un proyecto nuevo a Azure DevOps para validar su configuración Agile.
- **diagram-architect** (agent): >
- **diagram-config** (cmd): >
- **diagram-generate** (cmd): >
- **diagram-generation** (skill): Usar cuando se necesita generar diagramas de arquitectura o flujo desde código o infraestructura.
- **diagram-import** (cmd): >
- **diagram-import** (skill): Usar cuando se importa un diagrama existente para extraer entidades y crear PBIs.
- **diagram-status** (cmd): >
- **doc-quality-feedback** (skill): Usar cuando se recopila feedback de calidad de documentación tras usar skills y reglas.
- **dotnet-developer** (agent): >
- **dual-estimate** (script): dual-estimate.sh — Dual estimation engine: agent-time vs human-time
- **dx-core4** (cmd): Marco DX Core 4 completo: velocidad, efectividad, calidad e impacto. Genera scorecard de experiencia del desarrollador.
- **dx-dashboard** (cmd): Dashboard DX con métricas automatizables de feedback loops, cognitive load y satisfacción
- **dx-recommendations** (cmd): Análisis de friction points y recomendaciones para mejorar la experiencia del equipo
- **dx-survey** (cmd): Genera encuesta DX Core 4 adaptada al equipo y procesa respuestas
- **ecosystem-watcher** (skill): Usar una vez al mes para detectar cambios relevantes en el ecosistema de herramientas externas.
- **emergency-fallback** (script): emergency-fallback.sh — Operaciones PM sin LLM
- **emergency-mode** (cmd): Gestionar el modo emergencia con LLM local cuando el proveedor cloud no está disponible
- **emergency-mode** (skill): Usar cuando la API de Anthropic está caída y se necesita continuar operando con LocalAI.
- **emergency-plan** (cmd): Pre-descargar Ollama y modelo LLM en caché local para instalación offline
- **emergency-plan** (script): emergency-plan.sh — Pre-descarga de Ollama y modelo LLM para modo offline
- **emergency-setup** (script): emergency-setup.sh — Setup rápido de LLM local para modo emergencia
- **emergency-status** (script): emergency-status.sh — Estado del sistema de emergencia PM-Workspace
- **emotional-state-tracker** (script): emotional-state-tracker.sh — Track session stress state for Savia
- **ensure-daemons-auth** (script): ensure-daemons-auth.sh
- **enterprise-analytics** (skill): Usar cuando se necesitan métricas SPACE, aggregación de portfolio o forecasting empresarial.
- **enterprise-onboarding** (skill): Usar cuando se incorporan múltiples personas a la organización de forma masiva.
- **epic-plan** (cmd): >
- **estimate-calibrate** (script): estimate-calibrate.sh — Recompute empirical agent speedups from actuals log
- **estimate-convert** (script): estimate-convert.sh — Convert human-days to agent-hours using dual ratios
- **ethics-protocol** (cmd): >
- **eval-ablation-run** (script): eval-ablation-run.sh — SE-030-A
- **eval-create** (cmd): Create and configure evaluation criteria for outputs
- **eval-output** (cmd): >
- **eval-workspace** (script): eval-workspace.sh — Evaluación integral de pm-workspace contra sala-reservas
- **evaluate-repo** (cmd): >
- **evaluations-framework** (skill): Usar cuando se diseñan o ejecutan evaluaciones de calidad de agentes y prompts.
- **exit** (cmd): >
- **experiment-log** (cmd): >
- **factuality-judge** (agent): Truth Tribunal judge — factual accuracy of claims against verifiable sources
- **feature-impact** (cmd): Análisis de impacto de features — esfuerzo vs valor, ROI, priorización
- **feedback** (cmd): Abrir incidencias, ideas o mejoras como issues en el repositorio de pm-workspace
- **figma-extract** (cmd): >
- **flow-backlog-groom** (cmd): Review and prioritize backlog items
- **flow-board** (cmd): Visualizar tablero dual-track de Savia Flow (exploración + producción)
- **flow-burndown** (cmd): Show sprint burndown chart data
- **flow-intake** (cmd): Intake continuo — mover items Spec-Ready a Production y asignar a builders
- **flow-metrics** (cmd): Dashboard de métricas de flujo Savia Flow (cycle time, lead time, throughput, CFR)
- **flow-protect** (cmd): Detector de context-switching y protector de flow state. Analiza densidad de reuniones, patrones de interrupciones, sobrecarga WIP.
- **flow-setup** (cmd): Configurar proyecto en Azure DevOps para Savia Flow (dual-track, campos custom, áreas)
- **flow-spec** (cmd): Crear spec ejecutable desde outcome de exploración (puente exploration → production)
- **flow-spec-create** (cmd): Create a new SDD specification document
- **flow-sprint-board** (cmd): Display sprint board with task counts by column
- **flow-sprint-close** (cmd): Close sprint, move pending tasks to backlog, generate report
- **flow-sprint-create** (cmd): Create a new sprint with goal and dates
- **flow-task-assign** (cmd): Assign task to a team member
- **flow-task-create** (cmd): Create a new task in Savia Flow with frontmatter metadata
- **flow-task-move** (cmd): Move task between board columns (todo, in-progress, review, done)
- **flow-timesheet** (cmd): Log hours spent on a task
- **flow-timesheet-report** (cmd): Generate timesheet report for date range
- **flow-velocity** (cmd): Show historical velocity metrics
- **focus-mode** (cmd): Modo single-task — carga una sola tarea y oculta distracciones
- **fork-agents** (script): fork-agents.sh — Lanza N invocaciones paralelas de Claude con prefijo cacheable
- **frontend-developer** (agent): >
- **frontier-strategy** (script): frontier-strategy.sh — SE-216 Slice 3: frontier selection strategies
- **gdrive-upload** (cmd): >
- **generate-capability-map** (script): ── generate-capability-map.sh — Thin wrapper around the Python generator.
- **generate-critical-facts** (script): scripts/generate-critical-facts.sh
- **generate-index** (script): generate-index.sh — Generate discoverable index of all workspace components
- **github-activity** (cmd): >
- **github-issues** (cmd): >
- **github-projects** (cmd): Integración con GitHub Projects v2 para gestión ágil desde pm-workspace
- **go-developer** (agent): >
- **grant-track** (cmd): >
- **graph-impact** (cmd): Analiza el impacto en cascada de cambios en entidades PM
- **graph-query** (cmd): Consulta el grafo de conocimiento en lenguaje natural
- **graphrag-quality-gate** (script): graphrag-quality-gate.sh — SE-030-T
- **guided-work** (cmd): Trabajo guiado — Savia te acompaña paso a paso con preguntas, adaptando el ritmo a tus necesidades
- **hallucination-fast-judge** (agent): Recommendation Tribunal judge — verifies that entities cited in a draft (files, functions, flags, libs, paths, commands) actually exist via tool calls
- **hallucination-judge** (agent): Truth Tribunal judge — detects invented facts via SelfCheck-style consistency
- **hashline-edit** (script): hashline-edit.sh — Safe edit wrapper with stale-file protection (SE-149)
- **hashline-guard** (script): hashline-guard.sh — Stale-file protection for L3 agent edits (SE-149)
- **health-dashboard** (cmd): Dashboard de salud del proyecto unificado — Savia muestra una vista rápida adaptada al rol
- **heat-scheduler** (script): heat-scheduler.sh — Lightweight heat-based parallelism for dev sessions
- **help** (cmd): Catálogo de comandos y primeros pasos pendientes.
- **hook-bench-all** (script): hook-bench-all.sh — SE-037 Slice 1 probe: measure latency of all hooks.
- **hook-latency-bench** (script): hook-latency-bench.sh — Mide la latencia media de cada hook registrado
- **hook-pii-gate** (script): hook-pii-gate.sh — PII Quality Gate Pre-Commit Hook
- **hook-profile** (cmd): View or change the active SAVIA_HOOK_PROFILE (minimal/standard/strict/ci)
- **hook-profile** (script): hook-profile.sh — Get/set the active SAVIA_HOOK_PROFILE
- **hooks-integrity-check** (script): hooks-integrity-check.sh — SE-094: detect orphan and phantom hooks.
- **hw-bom** (cmd): >
- **hw-revision** (cmd): >
- **import-sprint-story** (cmd): >
- **incident-postmortem** (cmd): Template de postmortem — timeline, root cause analysis, action items
- **index-compact** (cmd): >
- **index-status** (cmd): >
- **infrastructure-agent** (agent): >
- **install-savia-bridge-system** (script): install-savia-bridge-system.sh — Promote savia-bridge to a SYSTEM systemd unit.
- **install-watchdog** (script): install-watchdog.sh — Installs savia-watchdog as systemd service
- **instinct-manage** (cmd): >
- **insurance-claim** (cmd): >
- **integration-status** (cmd): Dashboard de estado de todas las integraciones — APIs, webhooks, MCP, conectividad
- **inventory-manage** (cmd): Gestiona inventario: stock, reordenes, transferencias, conteos, alertas
- **java-developer** (agent): >
- **jira-connect** (cmd): Conectar y sincronizar con Jira Cloud como alternativa a Azure DevOps
- **jira-sync** (cmd): >
- **kg-query** (script): kg-query.sh — SE-218 S3: query KG con qualified names
- **knowledge-graph** (skill): Usar cuando se construye o consulta el grafo de conocimiento de entidades del proyecto.
- **knowledge-graph** (script): knowledge-graph.sh — SE-162: Shell wrapper for knowledge-graph.py
- **knowledge-prime** (cmd): Generar documento de priming AI desde código y configuración del proyecto
- **legacy-assess** (cmd): >
- **legal-deadline** (cmd): >
- **legal-template** (cmd): >
- **legalize-es** (script): legalize-es.sh — Gestión del corpus legislativo español (legalize-es)
- **lesson-extract** (cmd): Extract a cross-project lesson from the current task
- **lesson-pipeline** (script): lesson-pipeline.sh — SE-032: Cross-Project Lessons Pipeline
- **lib/adb-wrapper** (script): ============================================================================
- **lib/concurrent-executor** (script): concurrent-executor.sh — Semaphore-bounded parallel task execution
- **lib/enterprise-helpers** (script): enterprise-helpers.sh — Sourceable helpers for Enterprise module checks
- **lib/llm-healer** (script): llm-healer.sh — SE-076 Slice 3
- **lib/mock-env** (script): mock-env.sh — Reusable mock environment library for pm-workspace scripts
- **lib/os-detect** (script): scripts/lib/os-detect.sh — Portable OS detection and path defaults
- **lib/slm-common** (script): slm-common.sh — Shared helpers for SLM subcommands (SE-049 Slice 1).
- **linear-sync** (cmd): Sincronización bidireccional con Linear — issues, cycles, métricas unificadas
- **managed-content** (skill): Usar cuando se regeneran secciones auto-generadas en documentos con marcadores de seguridad.
- **managed-scan** (cmd): Scan managed content for stale or outdated sections
- **managed-sync** (cmd): Synchronize and regenerate managed content markers
- **marketplace-publish** (cmd): Publish components to marketplace registry
- **masked-unmask** (script): masked-unmask.sh — Unmask a Claude response back to real entities
- **mcp-recommend** (cmd): >
- **mcp-server-config** (cmd): Configure MCP servers and connection settings
- **mcp-server-start** (cmd): Start and initialize MCP server instances
- **mcp-server-status** (cmd): Check status and health of active MCP servers
- **memvid-backup** (skill): Usar cuando se crea un backup portable de la memoria externa de Savia.
- **mobile-developer** (agent): >
- **model-capability-resolver** (script): model-capability-resolver.sh — Resolve model capabilities from YAML registry
- **my-learning** (cmd): Detección de tech stack gaps — código del developer vs best practices del proyecto
- **my-sprint** (cmd): Vista personal del sprint — items asignados, progreso, cycle time, PRs pendientes
- **nidos** (cmd): Manage parallel terminal isolation with named git worktrees (Savia Nidos)
- **nidos** (script): nidos.sh — Savia Nidos: parallel terminal isolation via named git worktrees
- **nidos-lib** (script): nidos-lib.sh — Shared utilities for Savia Nidos
- **notion-sync** (cmd): >
- **nuclei-scanning** (skill): Usar cuando se escanean vulnerabilidades conocidas (CVEs, misconfigs) con Nuclei.
- **obs-connect** (cmd): Conectar Savia a plataformas de observabilidad — Grafana, Datadog, Azure App Insights, OpenTelemetry
- **obs-query** (cmd): Consultas en lenguaje natural a datos de observabilidad — PromQL, KQL, Datadog Query Language
- **obs-status** (cmd): Health check de todas las fuentes de observabilidad conectadas
- **okr-align** (cmd): Visualizar alineación proyecto→OKR→estrategia corporativa
- **okr-define** (cmd): Definir Objectives y Key Results vinculados a proyectos
- **okr-track** (cmd): Tracking automático de progreso OKR desde métricas de sprint
- **ollama-classify** (script): ollama-classify.sh — Clasificacion local de texto con Ollama
- **ollama-hardware-check** (script): ── ollama-hardware-check.sh ─────────────────────────────────────────────────
- **onboard** (cmd): >
- **onboard-enterprise** (cmd): Enterprise onboarding at scale — batch import, per-role checklists, knowledge transfer
- **onboarding-dev** (cmd): Technical onboarding with AI Buddy — auto-generates project docs, personalized plan, and 3-layer buddy agent
- **onboarding-dev** (skill): Usar cuando se incorpora un desarrollador nuevo al proyecto y necesita buddy IA.
- **operational-point-selector** (script): operational-point-selector.sh — SE-029 Slice 4.
- **opus47-calibration-scorecard** (script): opus47-calibration-scorecard.sh — SE-070 Slice 1
- **orchestration-protocol** (script): scripts/orchestration-protocol.sh — SE-205: typed inter-agent messaging
- **orgchart-import** (cmd): >
- **orgchart-import** (skill): Usar cuando se importa un organigrama para extraer la estructura del equipo.
- **oumi-probe** (script): oumi-probe.sh — SE-028 Slice 1 oumi integration viability probe.
- **outcome-track** (cmd): Tracking de outcomes post-release — ¿la feature entregó el valor esperado?
- **output-compress** (script): output-compress.sh — Compress verbose tool output (stdin -> stdout)
- **overnight-sprint** (skill): Usar cuando se quiere ejecutar tareas de bajo riesgo de forma autónoma durante la noche.
- **path-redact** (script): path-redact.sh — Redact absolute paths containing $HOME from text
- **pbi-assign** (cmd): Assign or reassign tasks based on intelligent allocation
- **pbi-decompose** (cmd): Decompose a PBI into granular technical tasks
- **pbi-decompose-batch** (cmd): Decompose multiple PBIs into technical tasks
- **pbi-decomposition** (skill): Usar cuando se descompone un PBI en tasks y se estiman las horas.
- **pbi-from-rules** (cmd): Map business rules to PBIs with traceability matrix
- **pbi-from-rules-report** (cmd): Generate traceability matrix report without creating PBIs
- **pbi-jtbd** (cmd): >
- **pbi-plan-sprint** (cmd): Plan and allocate PBIs to upcoming sprint
- **pbi-prd** (cmd): >
- **personal-vault** (skill): Usar cuando se lee o escribe el repositorio personal del usuario (perfil, preferencias, memoria).
- **php-developer** (agent): >
- **platform-migrate** (cmd): Migración asistida entre plataformas — Azure DevOps ↔ Jira ↔ GitHub Projects ↔ Linear
- **playbook-create** (cmd): Crear playbooks evolutivos para tareas repetitivas con framework ACE
- **playbook-evolve** (cmd): Evolucionar playbook con insights — ciclo Generator→Reflector→Curator (ACE)
- **playbook-library** (cmd): Biblioteca compartida de playbooks maduros entre proyectos
- **playbook-reflect** (cmd): Reflexión post-ejecución de playbooks — framework ACE Reflector
- **plugin-export** (cmd): Empaquetar pm-workspace como plugin distributable con validación de estructura
- **plugin-validate** (cmd): Validar estructura de plugin — skills, agents, commands e integridad
- **po-wizard** (cmd): Interactive wizard for product owner onboarding
- **portfolio-deps** (cmd): Grafo de dependencias inter-proyecto — visualiza y alerta sobre cuellos de botella entre proyectos
- **portfolio-overview** (cmd): Vista bird's-eye de todos los proyectos — semáforo, velocidad comparada, dependencias
- **postmortem-create** (cmd): Create incident postmortem with structured analysis
- **postmortem-heuristics** (cmd): Extract debugging heuristics from postmortems
- **pre-commit-sovereignty** (script): NOTE: -e omitted intentionally — grep returns 1 on no-match which would
- **pre-output-validator** (script): pre-output-validator.sh — TTSR-inspired pre-output rule validator (SE-150)
- **privacy-check-company** (script): privacy-check-company.sh — Privacy filter for company repo content
- **probe-devops** (script): probe-devops.sh — diagnóstico de acceso a Azure DevOps usando la
- **product-catalog** (cmd): Gestiona el catálogo de productos: añadir, actualizar, listar, buscar y exportar
- **product-discovery** (skill): Usar antes de descomponer PBIs, cuando se necesita análisis JTBD y PRD del producto.
- **profile-discover** (script): profile-discover.sh — SE-219 S4: auto multi-profile discovery (abtop pattern)
- **profile-edit** (cmd): Savia actualiza tu perfil — editar una sección.
- **profile-setup** (cmd): Savia te conoce — configuración del perfil en conversación natural.
- **profile-show** (cmd): Savia muestra tu perfil actual.
- **profile-switch** (cmd): Savia cambia de usuario — cambiar perfil activo.
- **project-activate** (cmd): Activa un proyecto como contexto activo en Savia: actualiza active-user.md y crea el directorio de memoria por proyecto si no existe. (SPEC-SE-093-ZERO-LEAK)
- **project-assign** (cmd): >
- **project-audit** (cmd): >
- **project-context** (script): project-context.sh — Project isolation for Savia (SE-093)
- **project-isolation-check** (script): project-isolation-check.sh — Verifica aislamiento de contexto por proyecto (SPEC-SE-093-ZERO-LEAK)
- **project-kickoff** (cmd): >
- **project-new** (cmd): >
- **project-release-plan** (cmd): >
- **project-roadmap** (cmd): >
- **project-switch** (cmd): Cambia el proyecto activo de Savia para aislamiento de contexto (SE-093).
- **project-update** (skill): Usar cuando se necesita una actualización integral del proyecto activo desde todas las fuentes.
- **project-update-devops** (script): project-update-devops.sh — wrapper que resuelve config real desde
- **prompt-optimizer** (skill): Usar cuando se optimiza el prompt de un skill o agente para mejorar su efectividad.
- **propuestas-index-gen** (script): propuestas-index-gen.sh — SE-222 S2: auto-generate INDEX.md for docs/propuestas/
- **protect-project-privacy** (script): protect-project-privacy.sh — Barrera de protección contra publicación accidental de proyectos
- **pursuit-bid** (cmd): Record bid/no-bid decision for a qualified pursuit
- **pursuit-close** (cmd): Close a pursuit as won or lost and trigger post-mortem analysis
- **pursuit-draft** (cmd): Generate proposal sections from library assets for a pursuit
- **pursuit-handoff** (cmd): Generate sales-to-delivery handoff package for a won pursuit
- **pursuit-init** (cmd): Scaffold a new pursuit opportunity directory with template files
- **pursuit-qualify** (cmd): Run BANT + MEDDIC qualification scoring on a pursuit
- **pursuit-validate** (script): pursuit-validate.sh — SE-015: Validate pursuit directories
- **push-pr** (script): push-pr.sh — CI + sign + push + create PR + release (zero re-sign commits)
- **python-developer** (agent): >
- **query-lib-index** (script): query-lib-index.sh — SE-031
- **query-lib-nl** (script): query-lib-nl.sh — SE-031 slice 2
- **query-lib-resolve** (script): query-lib-resolve.sh — SE-031
- **rbac-manager** (script): rbac-manager.sh — RBAC backend for Savia Enterprise multi-tenant
- **readiness-check** (script): readiness-check.sh — Deterministic capability checklist
- **recommendation-tribunal-orchestrator** (agent): Recommendation Tribunal orchestrator — convenes 4 fast judges in parallel, aggregates scores, applies vetos, mutates output with banner. SYNC, <3s p95.
- **record-export** (cmd): Export recorded session or data in multiple formats
- **record-replay** (cmd): Replay and analyze recorded sessions or events
- **record-stop** (cmd): Stop active recording session
- **recover-savia** (script): recover-savia.sh — Launch a clean Claude session OUTSIDE pm-workspace
- **ref-list** (cmd): List available resource references and their types
- **reflection-validation** (skill): Usar cuando una respuesta o decisión importante necesita validación metacognitiva (System 2).
- **reflection-validator** (agent): >
- **refresh-agent-maps** (script): refresh-agent-maps.sh
- **release-backfill** (script): release-backfill.sh — Create missing GitHub releases from git tags
- **repos-branches** (cmd): >
- **repos-list** (cmd): >
- **repos-pr-create** (cmd): >
- **repos-pr-list** (cmd): >
- **reranker** (skill): Usar cuando se recibe un top-K ruidoso de búsqueda en memoria y se necesita reordenar por relevancia.
- **reranker-probe** (script): reranker-probe.sh — SE-032 Slice 1 reranker viability probe.
- **resolve-all-open-prs** (script): resolve-all-open-prs.sh — one-shot helper that runs resolve-pr-conflicts.sh
- **resolve-pr-conflicts** (script): resolve-pr-conflicts.sh — auto-resolver for the recurring conflicts that
- **resolver-md-generate** (script): resolver-md-generate.sh — SE-160
- **resource-references** (skill): Usar cuando se necesitan referencias a recursos y plantillas del workspace.
- **retro-actions** (cmd): >
- **rpi-start** (cmd): >
- **ruby-developer** (agent): >
- **rule-manifest-integrity** (script): rule-manifest-integrity.sh — SE-057 Slice 1 rule-manifest + INDEX integrity.
- **rule-usage-analyzer** (script): rule-usage-analyzer.sh — Analyze domain rule usage across the workspace
- **rule-violation-judge** (agent): Recommendation Tribunal judge — detects when a draft recommendation violates canonical rules (CLAUDE.md, autonomous-safety, radical-honesty, domain rules)
- **run-agent-evals** (script): run-agent-evals.sh — SE-204: evaluation harness for critical agents
- **rust-developer** (agent): >
- **sbom-generate** (cmd): >
- **scale-optimizer** (cmd): Scaling optimization — analyze, benchmark, recommend improvements for growing organizations
- **scaling-operations** (skill): Usar cuando se analiza el tier de escala de un servicio o se necesitan optimizaciones de capacidad.
- **scheduled-create** (cmd): Crear tarea programada con notificaciones automáticas
- **scheduled-list** (cmd): Listar todas las tareas programadas y su configuración de notificaciones
- **scheduled-messaging** (skill): Usar cuando se configuran mensajes automáticos programados a plataformas de comunicación.
- **scheduled-setup** (cmd): Wizard interactivo para configurar notificaciones automáticas en plataformas de mensajería
- **school-analytics** (cmd): Teacher class-wide analytics and progress dashboard
- **school-diary** (cmd): Student learning diary and reflection journal
- **school-enroll** (cmd): Enroll student using alias (NO real names — privacy-first)
- **school-evaluate** (cmd): Teacher evaluates student project using encrypted rubric
- **school-export** (cmd): GDPR Article 15 — Export all student data in portable format
- **school-forget** (cmd): GDPR Article 17 — Right to Erasure, complete data deletion
- **school-portfolio** (cmd): Student portfolio view and learning journey showcase
- **school-progress** (cmd): View student progress and portfolio
- **school-project** (cmd): Student creates a new project from template
- **school-rubric** (cmd): Create or edit evaluation rubrics for grading
- **school-setup** (cmd): Configure classroom and initialize Savia School vertical
- **school-submit** (cmd): Student submits completed project for evaluation
- **score-diff** (cmd): >
- **scrapling-fetch** (script): scrapling-fetch.sh — SE-061 Slice 2 adaptive fetch wrapper.
- **scrapling-probe** (script): scrapling-probe.sh — SE-061 Slice 1 Scrapling viability probe.
- **sdlc-advance** (cmd): Advance work item through SDLC state machine
- **sdlc-status** (cmd): Show current SDLC state and transitions
- **sentry-bugs** (cmd): >
- **sentry-health** (cmd): >
- **service-catalog-telco** (cmd): Gestión del catálogo de servicios de telecom con definiciones, configuración y precios
- **setup-merge-drivers** (script): setup-merge-drivers.sh — configure local git with the custom merge drivers
- **setup-savia-dual** (script): setup-savia-dual.sh — Installer for Savia Dual (Linux/macOS)
- **setup-savia-remote** (script): setup-savia-remote.sh — Run ONCE on the remote server as root/sudo.
- **sheets-setup** (cmd): Configure Google Sheets integration
- **sheets-sync** (cmd): Synchronize data with Google Sheets
- **shield-ner-hook** (script): shield-ner-hook.sh — Savia Shield Capa 1.5: NER via daemon (fast)
- **skill-detect** (cmd): Detect repeated patterns and propose new skills automatically
- **skill-detect** (script): skill-detect.sh — SE-030: Skill Self-Improvement Pipeline
- **skill-eval** (cmd): >
- **skill-evaluation** (skill): Usar cuando se necesita seleccionar el skill más apropiado para una tarea dada.
- **skill-feedback-log** (script): skill-feedback-log.sh — Append skill invocation to JSONL log
- **skill-feedback-rank** (script): skill-feedback-rank.sh — Compute skill effectiveness and generate ranking
- **skill-keyword-detector** (script): skill-keyword-detector.sh — SE-203: detect which skills to auto-load based on keyword triggers
- **skill-propose** (cmd): Proponer nuevo skill desde un workflow repetitivo — auto-genera scaffold si 3+ observaciones
- **skill-rank** (cmd): Show skill effectiveness ranking based on invocation data
- **skill-read** (cmd): Carga el contenido completo de un skill bajo demanda (progressive disclosure)
- **skill-routing-index** (script): skill-routing-index.sh — SE-152
- **skills-lock** (script): skills-lock.sh — SHA-256 integrity verification for skills
- **skills-md-generate** (script): Force C locale for deterministic sort + awk text handling across machines
- **skillssh-adapter** (script): ── skills.sh Adapter — Genera paquetes publicables para skills.sh ──
- **slm** (script): slm.sh — Unified SLM (Small Language Model) training toolchain dispatcher.
- **slm-data-collect** (script): slm-data-collect.sh — Collect training data from workspace artifacts.
- **slm-data-prep** (script): slm-data-prep.sh — Prepare project data for SLM fine-tuning
- **slm-dataset-prep** (script): slm-dataset-prep.sh — Phase 1 scaffolding for SLM training pipeline.
- **slm-dataset-validate** (script): slm-dataset-validate.sh — Validate a JSONL dataset before SLM training.
- **slm-eval-compare** (script): slm-eval-compare.sh — A/B compare eval results between 2 SLM versions.
- **slm-eval-harness-setup** (script): slm-eval-harness-setup.sh — Phase 5 scaffolding: eval config emission.
- **slm-export-gguf** (script): slm-export-gguf.sh — Generate llama.cpp conversion recipe for adapter→GGUF.
- **slm-modelfile-gen** (script): slm-modelfile-gen.sh — Generate Ollama Modelfile for a trained SLM.
- **slm-pipeline-validate** (script): slm-pipeline-validate.sh — Meta-validator for an SLM project directory.
- **slm-project-init** (script): slm-project-init.sh — Bootstrap a new SLM project with the canonical layout.
- **slm-synth** (script): slm-synth.sh — SE-028 slice 1
- **slm-synth-recipe** (script): slm-synth-recipe.sh — SE-028 Slice 1 scaffolding: emit oumi synth recipe YAML.
- **slm-train** (script): slm-train.sh — Fine-tune SLMs locally with Unsloth + export to Ollama
- **slm-train-config** (script): slm-train-config.sh — Phase 3 scaffolding: emit Unsloth/TRL YAML config.
- **smart-calendar** (skill): Usar cuando se gestiona la agenda inteligente con sincronización Outlook/Teams.
- **sovereignty-benchmark** (script): sovereignty-benchmark.sh — Benchmark pm-workspace prompts with local LLM
- **sovereignty-mask** (script): sovereignty-mask.sh — Wrapper for reversible data masking
- **sovereignty-ops** (script): sovereignty-ops.sh — Download operations for sovereignty-pack.sh
- **sovereignty-switch** (script): sovereignty-switch.sh — Switch between LLM providers for pm-workspace
- **sprint-autoplan** (cmd): Planificación inteligente de sprint — sugiere composición óptima desde backlog y capacidad
- **sprint-forecast** (cmd): Predicción de completitud del sprint basada en velocity histórica
- **sprint-management** (skill): Usar cuando se consulta el estado del sprint, se actualizan items o se genera el resumen.
- **sprint-plan** (cmd): Asiste en el Sprint Planning calculando capacity disponible y proponiendo la carga de trabajo.
- **sprint-release-notes** (cmd): >
- **sprint-retro** (cmd): Genera la plantilla de retrospectiva con datos del sprint para facilitar la ceremonia.
- **sprint-review** (cmd): Genera el resumen para la Sprint Review con todos los datos del sprint cerrado.
- **sprint-status** (cmd): Estado del sprint actual — progreso, burndown, alertas.
- **stakeholder-align** (cmd): Resolución de conflictos entre stakeholders con datos objetivos
- **start-bridge** (script): start-bridge.sh — Invoked by Savia Claw remote_host.restart_bridge()
- **strategy-map** (cmd): Mapa estratégico — iniciativas, dependencias, contribución a objetivos
- **subscriber-lifecycle** (cmd): Gestión integral del ciclo de vida del suscriptor desde onboarding hasta análisis de churn
- **sustainable-pace** (cmd): Cálculo de ritmo sostenible basado en histórico y capacidad real
- **sync-adapters/adapter-interface** (script): adapter-interface.sh — Common interface for backlog sync adapters
- **sync-adapters/azure-devops-adapter** (script): azure-devops-adapter.sh — Sync local backlog with Azure DevOps
- **sync-adapters/github-issues-adapter** (script): github-issues-adapter.sh — Sync local backlog with GitHub Issues
- **sync-adapters/jira-adapter** (script): jira-adapter.sh — Sync local backlog with Jira Cloud
- **sync-calendars** (cmd): Sincronizar disponibilidad entre calendarios de dos tenants Microsoft 365
- **sync-github-metadata** (script): sync-github-metadata.sh — Update GitHub repo metadata
- **sync-model-tiers** (script): sync-model-tiers.sh — Resolve abstract model tiers (heavy|mid|fast) to provider-
- **sync-tags-from-changelog** (script): sync-tags-from-changelog.sh — Create missing git tags from CHANGELOG.md
- **task-create** (cmd): Add a task to Savia's todo list. Usage: /task-create Investigate this site...
- **task-decomposer** (script): task-decomposer.sh — Classify tasks as atomic/composite and decompose recursively
- **team-coordination** (skill): Usar cuando se coordinan múltiples equipos, se asignan miembros o se detectan bloqueantes cross-team.
- **team-evaluate** (cmd): >
- **team-onboarding** (cmd): >
- **team-onboarding** (skill): Usar cuando se incorpora un nuevo miembro al equipo y se evalúan sus competencias.
- **team-orchestrator** (cmd): Multi-team coordination — create teams, assign members, track cross-team dependencies and blockers
- **team-privacy-notice** (cmd): >
- **team-sentiment** (cmd): Análisis de sentimiento del equipo desde retros, standups y comunicaciones
- **team-skills-matrix** (cmd): Matriz de skills del equipo — quién sabe qué, bus factor, pair programming
- **team-workload** (cmd): Muestra la carga de trabajo por persona — items asignados, horas remaining y balance de equipo.
- **tech-radar** (cmd): Radar tecnológico del proyecto — librerías, versiones, adopt/trial/hold/retire
- **tech-writer** (agent): >
- **terraform-developer** (agent): >
- **threat-model** (cmd): >
- **tier3-probes** (skill): Usar cuando se valida la viabilidad de herramientas Tier 3 antes de adoptarlas en el workspace.
- **timeline-query** (script): timeline-query.sh — Query historical value of a field from bi-temporal timeline
- **token-estimator** (script): token-estimator.sh — Estimate token cost before execution
- **tool-catalog** (cmd): Catálogo categorizado de herramientas (400+ comandos)
- **tool-result-trim** (script): tool-result-trim.sh — Deterministic hard cap for tool result output
- **topic-cluster** (skill): Usar cuando se agrupan retros, PBIs o incidentes en topics para detectar patrones transversales.
- **travel-clean** (cmd): Elimina rastros de Savia de una máquina temporal.
- **travel-pack** (cmd): Empaca tu workspace en una unidad USB con cifrado AES-256.
- **travel-sync** (cmd): Sincroniza workspace bidireccional entre máquina y USB.
- **travel-unpack** (cmd): Desempaca tu workspace desde USB en una nueva máquina.
- **travel-verify** (cmd): Verifica integridad de un paquete de viaje en USB.
- **tribunal-critic** (script): tribunal-critic.sh — SE-201: quantitative scoring for tribunal verdicts
- **tribunal-status** (cmd): Show Truth Tribunal queue depth, recent verdicts, and pending evaluations
- **truth-tribunal-orchestrator** (agent): Truth Tribunal orchestrator — convenes 7 judges, aggregates scores, applies vetos, drives iteration
- **truth-tribunal-runbook** (skill): operational runbook for multi-judge evaluation orchestration
- **truth-tribunal-worker** (script): truth-tribunal-worker.sh — Consume queued Truth Tribunal verification
- **twin-decay-check** (script): twin-decay-check.sh — Escanea todos los twins y marca STALE los que superaron stale_after_days
- **typescript-developer** (agent): >
- **ua-bridge** (script): ua-bridge.sh — Bridge between Savia and Understand-Anything
- **ua-dashboard** (cmd): Start the interactive knowledge graph dashboard in browser
- **ua-install** (cmd): Install or update the Understand-Anything knowledge graph plugin
- **ua-install** (script): ua-install.sh — Install Understand-Anything plugin for Savia
- **underwriting-rule** (cmd): >
- **update** (cmd): Comprobar y aplicar actualizaciones de pm-workspace desde GitHub, preservando datos locales
- **update** (script): update.sh — Sistema de actualización de pm-workspace
- **user-profile** (cmd): Gestiona perfiles de miembros del equipo — ver, crear o editar.
- **validate-agent-permissions** (script): validate-agent-permissions.sh — Verify agent permission_level matches tools
- **validate-changelog-links** (script): validate-changelog-links.sh — Verifica que cada ## [X.Y.Z] tiene su enlace [X.Y.Z]: URL
- **validate-ci-local** (script): ── validate-ci-local.sh — Parallel CI validation ────────────────────────
- **validate-commands** (script): ─────────────────────────────────────────────────────────────────────
- **validate-critical-facts-cap** (script): scripts/validate-critical-facts-cap.sh
- **validate-devops** (script): =============================================================================
- **validate-devops-checks** (script): shellcheck shell=bash
- **validate-filesize** (cmd): Validar que ficheros del workspace cumplen ≤150 líneas
- **validate-handoff** (script): validate-handoff.sh — Validate handoff structure with termination_reason
- **validate-layer-contract** (script): validate-layer-contract.sh — SE-001 layer contract validator
- **validate-schema** (cmd): Validar schema de frontmatter y settings.json
- **validate-settings-local** (script): validate-settings-local.sh — Detect private/session data in settings.local.json
- **value-stream-map** (cmd): Mapa de valor end-to-end — idea→producción, waste, cuellos de botella
- **vault** (script): vault.sh — Personal Vault dispatcher (N3)
- **vault-export** (cmd): Exportar Personal Vault cifrado para portabilidad offline
- **vault-init** (cmd): Inicializar Personal Vault del usuario
- **vault-ops** (script): vault-ops.sh — Personal Vault operations library (N3). Sourced by vault.sh.
- **vault-restore** (cmd): Restaurar Personal Vault en nueva maquina
- **vault-status** (cmd): Estado del Personal Vault
- **vault-sync** (cmd): Sincronizar Personal Vault
- **velocity-trend** (cmd): Tendencia de velocity con media móvil, detección de anomalías y factores explicativos
- **verify-full** (cmd): Run 5-layer verification pipeline on task/branch
- **vertical-propose** (cmd): Proponer extensión vertical para un sector no-software detectado en el proyecto
- **volunteer-manage** (cmd): >
- **vuln-scan** (script): vuln-scan.sh — Vulnerability scanner for pm-workspace scripts
- **wave-executor** (script): wave-executor.sh — Generic wave execution engine for DAG task graphs
- **wave-executor-lib** (script): wave-executor-lib.sh — Helper functions for wave-executor.sh
- **webhook-config** (cmd): Configurar webhooks para recibir eventos push de Azure DevOps, GitHub y otras fuentes
- **wellbeing-guardian** (cmd): Proactive individual wellbeing system — break reminders, after-hours alerts, work-life balance nudges
- **wellbeing-guardian** (skill): Usar cuando se monitorizan señales de bienestar individual en el equipo.
- **wiki-publish** (cmd): >
- **wiki-sync** (cmd): >
- **workspace-doctor** (cmd): >
- **workspace-health** (script): workspace-health.sh — Comprehensive health dashboard for pm-workspace
- **write-a-skill** (skill): Guia para crear una nueva skill correctamente en pm-workspace. Usar cuando una tarea se repite 2+ veces o tarda mas de 15 min.
