"""Context Guard — MCP Server.

Exposes two MCP tools:
  - summarize(turns, run_id, threshold_pct?, recent_turns?, tier?, confidentiality?)
  - recall_summary(run_id, summary_id?)

Spec §2.5, §2.7 (D-7 Expone MCP server savia-context-guard).
Spec §2.8: confidencialidad — summary N3/N4 NOT accessible from N1 context.
Rule #26: Python for structured logic.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Any

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent, Tool

from scripts.lib.context_guard.monitor import ContextGuardConfig, ContextMonitor, TurnMessage
from scripts.lib.context_guard.store import SummaryStore
from scripts.lib.context_guard.summarizer import Summarizer, SummarizationError, build_summarizer_prompt
from scripts.lib.context_guard.tokenizer import TierTokenizer

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Confidentiality level ordering (higher index = more restricted)
# ---------------------------------------------------------------------------
_CONFIDENTIALITY_ORDER: list[str] = ["N1", "N2", "N3", "N4", "N4b"]

SERVER_NAME = "savia-context-guard"
SERVER_VERSION = "0.2.0"


def _confidentiality_index(level: str) -> int:
    try:
        return _CONFIDENTIALITY_ORDER.index(level)
    except ValueError:
        return 0


def _check_access(
    caller_level: str,
    resource_level: str,
) -> None:
    """Raise PermissionError if caller cannot access resource_level.

    Spec §2.8: un summary N3 no es accesible desde un contexto N1.
    Rule: caller must have equal or higher confidentiality level.
    """
    if _confidentiality_index(caller_level) < _confidentiality_index(resource_level):
        raise PermissionError(
            f"Access denied: caller confidentiality={caller_level!r} cannot access "
            f"summary with confidentiality={resource_level!r}. "
            "Spec §2.8 — summaries never exposed to lower confidentiality contexts."
        )


def _build_mock_invoke_fn(tier: str) -> Any:
    """Build a summarizer invoke_fn stub for the MCP context.

    In production this would call the actual OpenCode/Anthropic API.
    The MCP server operates in-process; the real invocation path is via
    the context-summarizer agent (separate process). This stub produces
    a valid summary_v1 YAML so the MCP server can be tested end-to-end
    without a live LLM call.
    """
    import yaml  # local import — only needed here

    def _invoke(turns_text: str, invoke_tier: str) -> str:
        word_count = len(turns_text.split())
        payload: dict[str, Any] = {
            "summary_v1": {
                "turn_count": turns_text.count("\n[") + 1,
                "time_span": {
                    "first_turn_at": "",
                    "last_turn_at": "",
                },
                "key_decisions": [],
                "artifacts_produced": [],
                "errors_encountered": [],
                "tools_invoked": [],
                "prose_summary": (
                    f"Summary generated by savia-context-guard MCP server "
                    f"(tier={invoke_tier}, words={word_count})."
                ),
            }
        }
        return yaml.dump(payload, allow_unicode=True)

    return _invoke


def _parse_turns(raw_turns: list[dict[str, Any]]) -> list[TurnMessage]:
    """Convert raw dicts from MCP input into TurnMessage objects."""
    result: list[TurnMessage] = []
    for item in raw_turns:
        if not isinstance(item, dict):
            raise ValueError(f"Each turn must be a dict, got {type(item).__name__}.")
        result.append(
            TurnMessage(
                role=str(item.get("role", "user")),
                content=str(item.get("content", "")),
                timestamp=item.get("timestamp"),
                is_artifact=bool(item.get("is_artifact", False)),
            )
        )
    return result


# ---------------------------------------------------------------------------
# MCP server factory
# ---------------------------------------------------------------------------


def build_server(base_dir: Path | None = None) -> Server:
    """Build and return the configured MCP server.

    Args:
        base_dir: Root directory for context-guard output.
            Defaults to ``<repo_root>/output/context-guard``.
    """
    if base_dir is None:
        # Resolve to <workspace>/output/context-guard at import time
        _here = Path(__file__).resolve()
        _workspace = _here.parents[3]  # scripts/lib/context_guard → workspace
        base_dir = _workspace / "output" / "context-guard"

    server: Server = Server(SERVER_NAME)

    @server.list_tools()  # type: ignore[misc]
    async def list_tools() -> list[Tool]:
        return [
            Tool(
                name="summarize",
                description=(
                    "Summarize a list of conversation turns and persist the summary. "
                    "Returns the summary_id and summary contents."
                ),
                inputSchema={
                    "type": "object",
                    "properties": {
                        "turns": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "role": {"type": "string"},
                                    "content": {"type": "string"},
                                    "timestamp": {"type": "string"},
                                    "is_artifact": {"type": "boolean"},
                                },
                                "required": ["role", "content"],
                            },
                            "description": "Conversation turns to summarize.",
                        },
                        "run_id": {
                            "type": "string",
                            "description": "Unique identifier for this run/session.",
                        },
                        "threshold_pct": {
                            "type": "integer",
                            "minimum": 50,
                            "maximum": 95,
                            "default": 75,
                            "description": "Trigger threshold as % of context window.",
                        },
                        "recent_turns": {
                            "type": "integer",
                            "minimum": 1,
                            "default": 5,
                            "description": "Number of recent turns to preserve unsummarized.",
                        },
                        "tier": {
                            "type": "string",
                            "enum": ["heavy", "mid", "fast"],
                            "default": "fast",
                            "description": "Summarizer model tier.",
                        },
                        "confidentiality": {
                            "type": "string",
                            "enum": ["N1", "N2", "N3", "N4", "N4b"],
                            "default": "N1",
                            "description": "Confidentiality level inherited by the summary.",
                        },
                        "caller_confidentiality": {
                            "type": "string",
                            "enum": ["N1", "N2", "N3", "N4", "N4b"],
                            "default": "N1",
                            "description": "Confidentiality level of the calling context.",
                        },
                        "force": {
                            "type": "boolean",
                            "default": False,
                            "description": (
                                "Force summarization even if threshold not crossed. "
                                "Uses threshold_pct=1 internally to guarantee trigger."
                            ),
                        },
                    },
                    "required": ["turns", "run_id"],
                },
            ),
            Tool(
                name="recall_summary",
                description=(
                    "Retrieve a previously stored summary. "
                    "Returns the latest summary if summary_id is omitted."
                ),
                inputSchema={
                    "type": "object",
                    "properties": {
                        "run_id": {
                            "type": "string",
                            "description": "Run identifier used when the summary was created.",
                        },
                        "summary_id": {
                            "type": "string",
                            "description": (
                                "Specific summary id (e.g. 'summary-001'). "
                                "Omit to get the latest."
                            ),
                        },
                        "caller_confidentiality": {
                            "type": "string",
                            "enum": ["N1", "N2", "N3", "N4", "N4b"],
                            "default": "N1",
                            "description": "Confidentiality level of the calling context.",
                        },
                    },
                    "required": ["run_id"],
                },
            ),
        ]

    @server.call_tool()  # type: ignore[misc]
    async def call_tool(
        name: str,
        arguments: dict[str, Any],
    ) -> list[TextContent]:
        if name == "summarize":
            return await _handle_summarize(arguments, base_dir)
        if name == "recall_summary":
            return await _handle_recall_summary(arguments, base_dir)
        raise ValueError(f"Unknown tool: {name!r}")

    return server


# ---------------------------------------------------------------------------
# Tool handlers
# ---------------------------------------------------------------------------


async def _handle_summarize(
    args: dict[str, Any],
    base_dir: Path,
) -> list[TextContent]:
    """Handle the summarize() MCP tool call."""
    import json

    raw_turns: list[dict[str, Any]] = args.get("turns", [])
    run_id: str = str(args.get("run_id", ""))
    threshold_pct: int = int(args.get("threshold_pct", 75))
    recent_turns_count: int = int(args.get("recent_turns", 5))
    tier: str = str(args.get("tier", "fast"))
    confidentiality: str = str(args.get("confidentiality", "N1"))
    caller_confidentiality: str = str(args.get("caller_confidentiality", "N1"))
    force: bool = bool(args.get("force", False))

    if not run_id:
        return [TextContent(type="text", text='{"error": "run_id is required"}')]

    # Confidentiality check: caller must be >= resource
    try:
        _check_access(caller_confidentiality, confidentiality)
    except PermissionError as exc:
        return [
            TextContent(
                type="text",
                text=json.dumps({"error": "403 Forbidden", "detail": str(exc)}),
            )
        ]

    try:
        turns = _parse_turns(raw_turns)
    except ValueError as exc:
        return [
            TextContent(
                type="text",
                text=json.dumps({"error": f"Invalid turns input: {exc}"}),
            )
        ]

    # Monitor
    effective_threshold = 1 if force else threshold_pct
    config = ContextGuardConfig(
        enabled=True,
        threshold_pct=max(50, effective_threshold),
        recent_turns=recent_turns_count,
    )
    tokenizer = TierTokenizer(tier=tier)  # type: ignore[arg-type]
    monitor = ContextMonitor(config=config, tokenizer=tokenizer, tier=tier)  # type: ignore[arg-type]

    # When force=True we bypass the monitor threshold check
    if force:
        turns_to_summarize = turns[: max(0, len(turns) - recent_turns_count)]
        if not turns_to_summarize:
            turns_to_summarize = turns
    else:
        decision = monitor.check(turns)
        if not decision.should_summarize:
            return [
                TextContent(
                    type="text",
                    text=json.dumps(
                        {
                            "triggered": False,
                            "pct_used": round(decision.pct_used, 2),
                            "threshold_pct": threshold_pct,
                            "message": "Threshold not crossed. No summarization performed.",
                        }
                    ),
                )
            ]
        turns_to_summarize = decision.turns_to_summarize

    turns_text = "\n".join(
        f"[{t.role}] {t.content}" for t in turns_to_summarize
    )
    tokens_before = sum(tokenizer.count(t.content) for t in turns_to_summarize)

    # Summarize
    invoke_fn = _build_mock_invoke_fn(tier)
    summarizer = Summarizer(invoke_fn=invoke_fn, initial_tier=tier)  # type: ignore[arg-type]

    try:
        result = summarizer.summarize(turns_text=turns_text, tokens_before=tokens_before)
    except SummarizationError as exc:
        return [
            TextContent(
                type="text",
                text=json.dumps({"error": f"Summarization failed: {exc}"}),
            )
        ]

    # Persist
    store = SummaryStore(base_dir=base_dir, confidentiality=confidentiality)  # type: ignore[arg-type]
    summary_path = store.save(run_id=run_id, result=result)
    store.write_trace_event(run_id=run_id, result=result, summary_path=summary_path)

    return [
        TextContent(
            type="text",
            text=json.dumps(
                {
                    "triggered": True,
                    "summary_id": summary_path.stem,
                    "run_id": run_id,
                    "tokens_before": result.tokens_before,
                    "tokens_after": result.tokens_after,
                    "tier_used": result.tier_used,
                    "retried": result.retried,
                    "confidentiality": confidentiality,
                    "summary": result.summary.model_dump(),
                },
                ensure_ascii=False,
            ),
        )
    ]


async def _handle_recall_summary(
    args: dict[str, Any],
    base_dir: Path,
) -> list[TextContent]:
    """Handle the recall_summary() MCP tool call."""
    import json

    run_id: str = str(args.get("run_id", ""))
    summary_id: str | None = args.get("summary_id") or None
    caller_confidentiality: str = str(args.get("caller_confidentiality", "N1"))

    if not run_id:
        return [TextContent(type="text", text='{"error": "run_id is required"}')]

    # Try all confidentiality levels to find where this run lives.
    # We enforce the access check based on what we find.
    _levels = ["N4b", "N4", "N3", "N2", "N1"]
    data: dict | None = None
    found_level: str = "N1"

    for lvl in _levels:
        store = SummaryStore(base_dir=base_dir, confidentiality=lvl)  # type: ignore[arg-type]
        try:
            data = store.load(run_id=run_id, summary_id=summary_id)
            found_level = lvl
            break
        except FileNotFoundError:
            continue

    if data is None:
        return [
            TextContent(
                type="text",
                text=json.dumps({"error": f"No summaries found for run_id={run_id!r}"}),
            )
        ]

    # Enforce access: caller must be >= found resource level
    resource_confidentiality = data.get("_meta", {}).get("confidentiality", found_level)
    try:
        _check_access(caller_confidentiality, resource_confidentiality)
    except PermissionError as exc:
        return [
            TextContent(
                type="text",
                text=json.dumps({"error": "403 Forbidden", "detail": str(exc)}),
            )
        ]

    return [
        TextContent(
            type="text",
            text=json.dumps(data, ensure_ascii=False, default=str),
        )
    ]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def run_server(base_dir: Path | None = None) -> None:
    """Run the MCP server over stdio."""
    server = build_server(base_dir=base_dir)
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options(),
        )


def main() -> None:
    import asyncio

    logging.basicConfig(level=logging.WARNING, stream=sys.stderr)
    asyncio.run(run_server())


if __name__ == "__main__":
    main()
